project:
  type: website
bibliography: bibliography.bib
csl: media/ieee-with-url.csl
filters:
  - acronyms
acronyms:
  loa_title: "List of Acronyms"
  include_unused: false
  insert_loa: "end"
  insert_links: true
  id_prefix: "acronyms_"
  sorting: "alphabetical"
  non_existing: "key"
  style: "long-short"
  fromfile:
    - media/acronyms.yml


website:
  title: "OPDI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - concepts.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



