project:
  type: website
bibliography: bibliography.bib
csl: media/ieee-with-url.csl


website:
  title: "OPDI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data.qmd
      - concepts.qmd
      - methodology.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



