project:
  type: website
bibliography: bibliography.bib
csl: media/ieee-with-url.csl

execute:
  echo: false
  warning: false


filters:
  - acronyms

acronyms:
  loa_title: "List of Acronyms"
  include_unused: false
  insert_loa: "end"
  insert_links: false
  id_prefix: "acronyms_"
  sorting: "alphabetical"
  non_existing: "key"
  style: "long-short"
  fromfile:
    - media/acronyms.yml


website:
  title: "OPDI"
  # TODO: add GA4 measurement ID when in production (UA property deprecated)
  # google-analytics: "G-XXXXXXXXXX"

  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - data.qmd
      - concepts.qmd
      - methodology.qmd
      - roadmap.qmd
      - href: data-preview.qmd
        text: Data Preview
      - about.qmd

  navbar:
  # Note: You need to install: ```quarto install extension mcanouil/quarto-iconify```
  # For the icons to work.
    background: dark
    search: true
    collapse-below: xl
    title: 'Open Performance Data Initiative (OPDI)'
    logo: "media/EUROCONTROL-logo-standard-rgb.png"
    right:
      - text: "Home"
        href: https://ansperformance.eu/
      - text: "Performance areas"
        menu:
          - text: "{{< iconify fa6-solid table-cells-large >}}&nbsp;Balanced scorecard"
            href: "https://www.eurocontrol.int/Economics/BalancedScorecard.html"
          - text: "{{< iconify fa6-solid plane-departure >}}&nbsp;Traffic"
            href: https://ansperformance.eu/traffic/
          - text: "Daily traffic dashboard"
            href: "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"
          - text: "Service units"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
          - text: "Traffic forecast"
            href: https://ansperformance.eu/traffic/statfor/
          - text: "{{< iconify fa6-solid calendar >}}&nbsp;Punctuality"
            href: https://ansperformance.eu/traffic/punctuality/
          - text: "Daily punctuality dashboard"
            href: "https://www.eurocontrol.int/Economics/DailyPunctuality-States.html"
          - text: "Network punctuality"
            href: https://ansperformance.eu/traffic/punctuality/#eurocontrol-area-network-view-1
          - text: "State & airport punctuality"
            href: https://ansperformance.eu/traffic/punctuality/#state-view-1
          - text: "{{< iconify fa6-solid clock >}}&nbsp;En-route & airport delays"
            href: https://ansperformance.eu/capacity/
          - text: "Daily ATFM delays dashboard"
            href: "https://www.eurocontrol.int/Economics/DailyDelay-States.html"
          - text: "En-route ATFM delays"
            href: https://ansperformance.eu/capacity/atfm_ert/
          - text: "Airport ATFM delays"
            href: https://ansperformance.eu/capacity/atfm_apt/
          - text: "All-causes delays"
            href: https://ansperformance.eu/capacity/tot_dly
          - text: "{{< iconify fa6-solid leaf >}}&nbsp;Efficiency & environment"
            href: https://ansperformance.eu/efficiency/
          - text: "CO<sub>2</sub> emissions"
            href: https://ansperformance.eu/efficiency/emissions/
          - text: "Horizontal flight efficiency"
            href: https://ansperformance.eu/efficiency/hfe/
          - text: "Vertical flight efficiency"
            href: https://ansperformance.eu/efficiency/vfe/
          - text: "Terminal holdings"
            href: https://ansperformance.eu/efficiency/asma/
          - text: "Taxi-out"
            href: https://ansperformance.eu/efficiency/taxiout/
          - text: "Taxi-in"
            href: https://ansperformance.eu/efficiency/taxiin/
          - text: "{{< iconify fa6-solid euro-sign >}}&nbsp;Economics"
            href: https://ansperformance.eu/economics/
          - text: "ATM cost-effectiveness (ACE)"
            href: https://ansperformance.eu/economics/ace-overview/
          - text: "Unit rates and costs"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteUnitRates.html"
          - text: "Service units"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
          - text: "ANSPs financial dashboard"
            href: https://ansperformance.eu/economics/finance/
          - text: "Standard Inputs for Economic Analyses"
            href: https://ansperformance.eu/economics/cba/

      - text: "Stakeholder views"
        menu:
          - text: "{{< iconify fa6-solid plane-arrival >}}&nbsp;Airports"
            href: https://ansperformance.eu/dashboard/stakeholder/airport/
          - text: "{{< iconify fa6-solid compass >}}&nbsp;Air navigation service provider"
            href: https://ansperformance.eu/dashboard/stakeholder/ansp/
          - text: "{{< iconify fa6-solid globe >}}&nbsp;States"
            href: https://ansperformance.eu/dashboard/stakeholder/state/

      - text: "Data"
        href: https://ansperformance.eu/data/

      - text: "Publications"
        href: https://ansperformance.eu/publications/

      - text: "Reference"
        menu:
          - text: "{{< iconify fa6-solid marker >}}&nbsp;Definitions"
            href: https://ansperformance.eu/definition/
          - text: "{{< iconify fa6-solid wrench >}}&nbsp;Methodology"
            href: https://ansperformance.eu/methodology/
          - text: "{{< iconify fa6-solid quote-left >}}&nbsp;Acronyms"
            href: https://ansperformance.eu/acronym/
          - text: "{{< iconify fa6-solid book >}}&nbsp;Bibliography"
            href: https://ansperformance.eu/bibliography/

      - text: "Links"
        menu:
          - text: "EUROCONTROL <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://www.eurocontrol.int/"
          - text: "Single European Sky (SES) portal <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://www.eurocontrol.int/prudata/dashboard/"
          - text: "ICAO GANP <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://www4.icao.int/ganpportal/"
          - text: "Connectivity dashboard <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://ext.eurocontrol.int/connectivity_web/from"
          - text: "PRC Transformation Strategy"
            href: https://ansperformance.eu/transformation/
          - text: "PRC Open Performance Data Initiative"
            href: "https://opdi.aero"

      - text: "About"
        menu:
          - text: "About the PRC"
            href: https://ansperformance.eu/about/prc/
          - text: "About the AIU"
            href: https://ansperformance.eu/about/aiu/
          - text: "About the PRU"
            href: https://ansperformance.eu/about/us/
          - text: "Release notes"
            href: https://ansperformance.eu/post/
          - text: "Disclaimer"
            href: https://ansperformance.eu/about/disclaimer/

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    css:
      - templates/css/custom.css
      - styles.css
    include-after-body: templates/footer.html
