---
title: "About"
---

## Performance Review Commission

The Performance Review Commission (PRC) was established in 1998 by EUROCONTROL’s Permanent Commission.

It provides objective information and independent advice to EUROCONTROL’s governing bodies on European air traffic management (ATM) performance, based on extensive research, data analysis and consultation with stakeholders. Its purpose is “to ensure the effective management of the European air traffic management System through a strong, transparent and independent performance review,” as stated in Article 1 of the PRC Terms of Reference and Rules of Procedure.

The PRC reports to the EUROCONTROL Permanent Commission through the Provisional Council and is supported by the [Performance Review Unit (PRU)](https://ansperformance.eu/about/us/) operating under the EUROCONTROL Agency with the appropriate level of independence.

For more information about the Performance Review Commission, see [here](https://ansperformance.eu/about/prc/).


## Open Performance Data Initiative

In 2022, the PRC launched the Open Performance Data Initiative (OPDI) with a view to establish a data platform, to support higher levels of transparency and reproducibility of performance related monitoring and associated analyses. This initiative addresses the requirement to establish a level playing field for all stakeholders, ranging from the interested public, operational and strategic planners, to political decision-makers. Pursuing an open data-based approach will allow all interested parties to tap into a harmonised data environment to build their assessments, validate results published by other parties, and reproduce findings in support of the political and operational discussion about observed performance. 

The upcoming challenges to our industry require that stakeholders can embrace and tap into a harmonised and consolidated data set to drive the discussion on higher performance levels, performance expectations in terms of targets, or realised performance benefits following the deployment of new capabilities. 

For more information about the Open Performance Data Initiative, see [here](https://www.eurocontrol.int/publication/performance-insight-5-open-performance-data). 

## Benefits of Open Access and Open Data for Performance Monitoring

To understand the depth of the proposed Open Performance Data Initiative it is vital to define the key terminology upfront.

* **Open Access**: Open Access refers to the process of managing copyright and licensing terms and access to the data. This access mode is vital to overcome today’s limitation and remove barriers such as price (including subscriptions, licensing fees, user-pay-principles, or even view fees), and permission (e.g., licensing restrictions) to enable free access and use of the data.
* **Open Data**: The term Open Data refers to data - typically managed and available online – which is free of cost and accessible data. Open data can be freely used, reused, and distributed provided that the data source is attributed.
* **Open-Source Software**: Open-Source Software is software which source code can be openly accessed, inspected, modified, and enhanced by anyone. 

The focus of the Open Performance Data Initiative is on open data, in particular open access and open use of data for non-commercial purposes. It is understood that potential developments of novel algorithms and techniques can produce tools that are made available to the community as open-source software.

There exists a huge body of literature highlighting the impact of open data. Across the different sources the following impact areas emerge:

* Transparency and accountability
* Innovation, participation, and joint
development
* Stakeholder performance, service delivery
and actor effectiveness
* Public and stakeholder engagement and
empowerment

Open data and performance analytics are often viewed as separate practices, however, both are inextricable when it comes to the operations of modern governance. To ensure transparent and independent review, open data provides the underlying “raw material” for the analysis and monitoring of performance. In that respect, PRC’s Open Performance Data Initiative aims at increasing transparency, supporting higher levels of data access and information availability for decision-making, engaging and increasing accountability of involved stakeholders.

### Transparency and accountability
A key tenet of the performance-based approach is independent and impartial monitoring to provide the evidence for achieved performance levels and to identify and share best practice for further performance enhancements in ATM.

Higher levels of transparency and accountability provide the foundation for a democratisation of air traffic management. Public and stakeholder access to data is also seen as a key ingredient to establish accountability. This also requires a culture change
that is implicitly built into the performance-based approach. Observed levels of performance are publicly communicated and tracked. Associated performance measurement algorithms are published and the monitoring results are reproducible.

### Innovation, participation, and joint development

Open data from both public and private sources are adding a new dimension2 to the data
revolution. It also is a key ingredient to leverage the promises of “big data”, or supporting data-analytical advances in artificial intelligence/machine-learning.

A clear driver for innovation is the opportunity to understand how systems work, where bottlenecks emerge or certain patterns manifest. At the same time, it is important to understand the parameters and conditions for good and best-in-class performance. Sharing and access to data therefore fosters to have another view on performance by observing new developments with different priorities/ perspectives, or other organisational /institutional factors limiting the use and value creation from data, including its combination with additional data and resources.

The ability of public, interested researchers, policymakers/think tanks, or strategic planners to access the data and exploit it creates joint communities of interest. This may enhance the value of the data to drive joint developments ranging from data standardisation, including access and storage, but also to build on the data. The latter may range from methodological approaches, operational solutions and other tools.

### Effectiveness
At the heart of the performance-based approach is the potential to achieve higher levels of performance and associated decision-making through data-driven decision-making. This may affect day-to-day decision-making, but also longterm decision such as the need for adopting new operational concepts or deploying operational capabilities.

Open data goes beyond the classical – potentially limited –sharing of data in support of use-case analyses, projects or activities. It is a continual process which allows to champion and demonstrate observed performance levels. In that respect open performance data can also serve as a tool to improve communication and partnerships
in terms of data sharing.

### Engagement and Empowerment

The most direct impact of open data for engagement and empowerment is related to its
transparency effects. Air transportation and air traffic management are at a crossroad. Future political goals and expected performance levels require higher levels of transparency and the existence of a data basis in support of verification and validation/reproduction of results. The transparency discussion will result from a higher
pressure on the industry to demonstrate – for example – its contribution to climate change and greenhouse gas emissions. There is also a discussion on the success of air navigation system modernisation (i.e., transformation) in general. This requires demonstration of operational performance benefits derived from funding and modernisation activities.

The need to address the societal challenges and political goals will require a wider engagement of air navigation with the public and policy level, but also facilitate such an engagement with the industry and interested public. The PRC is confident that the practice of the past to provide a platform to validate and reproduce performance observations will facilitate higher levels of engagement and empowerment with and between
stakeholders and public. Open data can be a key enabler to facilitate this engagement and ensure the appropriate level of independent transparency to drive and inform the public debate, political and strategic decision-making.

For more information about the potential benefits of the Open Access and Open Data for Performance Monitoring, see [here](https://www.eurocontrol.int/publication/performance-insight-5-open-performance-data). 
