---
title: "Download Flight List v0.0.2 Datasets"
format: html
acronyms:
  insert_loa: false
---

Below you will find links to download flight list v.0.0.2 data files from January 2022 to November 2024. Each file is in Parquet format, providing a highly efficient way to store and manage large datasets.

## Available Datasets

Each dataset corresponds to a specific month and year, listed below for easy access.

::: {.callout-tip}
## Automated Download

If you want to automate your downloads, you can generate the link for downloading using the following format where YYYY is the year of interest and MM the month (using two digits): 
```https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_{YYYY}{MM}.parquet```
:::

### 2022

- **January 2022**  
  [Download flight_list_202201.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202201.parquet)

- **February 2022**  
  [Download flight_list_202202.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202202.parquet)

- **March 2022**  
  [Download flight_list_202203.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202203.parquet)

- **April 2022**  
  [Download flight_list_202204.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202204.parquet)

- **May 2022**  
  [Download flight_list_202205.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202205.parquet)

- **June 2022**  
  [Download flight_list_202206.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202206.parquet)

- **July 2022**  
  [Download flight_list_202207.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202207.parquet)

- **August 2022**  
  [Download flight_list_202208.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202208.parquet)

- **September 2022**  
  [Download flight_list_202209.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202209.parquet)

- **October 2022**  
  [Download flight_list_202210.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202210.parquet)

- **November 2022**  
  [Download flight_list_202211.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202211.parquet)

- **December 2022**  
  [Download flight_list_202212.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202212.parquet)

### 2023

- **January 2023**  
  [Download flight_list_202301.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202301.parquet)

- **February 2023**  
  [Download flight_list_202302.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202302.parquet)

- **March 2023**  
  [Download flight_list_202303.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202303.parquet)

- **April 2023**  
  [Download flight_list_202304.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202304.parquet)

- **May 2023**  
  [Download flight_list_202305.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202305.parquet)

- **June 2023**  
  [Download flight_list_202306.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202306.parquet)

- **July 2023**  
  [Download flight_list_202307.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202307.parquet)

- **August 2023**  
  [Download flight_list_202308.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202308.parquet)

- **September 2023**  
  [Download flight_list_202309.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202309.parquet)

- **October 2023**  
  [Download flight_list_202310.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202310.parquet)

- **November 2023**  
  [Download flight_list_202311.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202311.parquet)

- **December 2023**  
  [Download flight_list_202312.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202312.parquet)

### 2024

- **January 2024**  
  [Download flight_list_202401.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202401.parquet)

- **February 2024**  
  [Download flight_list_202402.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202402.parquet)

- **March 2024**  
  [Download flight_list_202403.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202403.parquet)

- **April 2024**  
  [Download flight_list_202404.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202404.parquet)

- **May 2024**  
  [Download flight_list_202405.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202405.parquet)

- **June 2024**  
  [Download flight_list_202406.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202406.parquet)
  
- **July 2024**  
  [Download flight_list_202407.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202407.parquet)
  
- **August 2024**  
  [Download flight_list_202408.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202408.parquet)
  
- **September 2024**  
  [Download flight_list_202409.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202409.parquet)
  
- **October 2024**  
  [Download flight_list_202410.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202410.parquet)
  
- **November 2024**  
  [Download flight_list_202411.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202411.parquet)

---

We hope you find these datasets useful for your analysis and research. If you have any questions or require further assistance, please contact us at [support@ansperformance.eu](mailto:support@ansperformance.eu).
