---
title: "Download Flight Events v0.0.2 Datasets"
format: html
---

Below you will find links to download flight events v0.0.2 data files from January 1, 2022, to July 9, 2024. Each file is in Parquet format, providing a highly efficient way to store and manage large datasets. The datasets are separated into 10-day intervals. Please note that each dataset covers data up to, but not including, the last day listed in its name.

::: {.callout-caution}
## Disclaimer

Please note that due to occasional system maintenance and technical issues experienced by our data provider, OpenSky Network, some of the datasets may have incomplete data for certain periods. We are continuously working with OpenSky to ensure data quality and integrity and will resolve this in the upcoming release.

Affected periods include **December 2023**, **January 2024**, **February 2024**, **March 2024**, and **April 2024**. Please review the data carefully before use and, if possible, exclude these periods in your analysis.
:::

## Available Datasets

Each dataset corresponds to a specific 10-day period and is listed below for easy access.

::: {.callout-tip}
## Automated Download

If you want to automate your downloads, you can generate the link for downloading using the following format where `YYYYMMDD` is the start date of the 10-day period:
```https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_{YYYYMMDD}_{YYYYMMDD_next10}.parquet```

The first date to start generating intervals for is 1 January 2022. As an example, for January 1, 2022, to January 10, 2022, the link would be:  
```https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220101_20220111.parquet```
:::

### 2022

- **January 1 - 10, 2022**  
  [Download flight_events_20220101_20220111.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220101_20220111.parquet)

- **January 11 - 20, 2022**  
  [Download flight_events_20220111_20220121.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220111_20220121.parquet)

- **January 21 - 30, 2022**  
  [Download flight_events_20220121_20220131.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220121_20220131.parquet)

- **January 31 - February 9, 2022**  
  [Download flight_events_20220131_20220210.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220131_20220210.parquet)

- **February 10 - 19, 2022**  
  [Download flight_events_20220210_20220220.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220210_20220220.parquet)

- **February 20 - March 1, 2022**  
  [Download flight_events_20220220_20220302.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220220_20220302.parquet)

- **March 2 - 11, 2022**  
  [Download flight_events_20220302_20220312.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220302_20220312.parquet)

- **March 12 - 21, 2022**  
  [Download flight_events_20220312_20220322.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220312_20220322.parquet)

- **March 22 - 31, 2022**  
  [Download flight_events_20220322_20220401.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220322_20220401.parquet)

- **April 1 - 10, 2022**  
  [Download flight_events_20220401_20220411.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220401_20220411.parquet)

- **April 11 - 20, 2022**  
  [Download flight_events_20220411_20220421.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220411_20220421.parquet)

- **April 21 - 30, 2022**  
  [Download flight_events_20220421_20220501.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220421_20220501.parquet)

- **May 1 - 10, 2022**  
  [Download flight_events_20220501_20220511.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220501_20220511.parquet)

- **May 11 - 20, 2022**  
  [Download flight_events_20220511_20220521.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220511_20220521.parquet)

- **May 21 - 30, 2022**  
  [Download flight_events_20220521_20220531.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220521_20220531.parquet)

- **May 31 - June 9, 2022**  
  [Download flight_events_20220531_20220610.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220531_20220610.parquet)

- **June 10 - 19, 2022**  
  [Download flight_events_20220610_20220620.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220610_20220620.parquet)

- **June 20 - 29, 2022**  
  [Download flight_events_20220620_20220630.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220620_20220630.parquet)

- **June 30 - July 9, 2022**  
  [Download flight_events_20220630_20220710.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220630_20220710.parquet)

- **July 10 - 19, 2022**  
  [Download flight_events_20220710_20220720.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220710_20220720.parquet)

- **July 20 - 29, 2022**  
  [Download flight_events_20220720_20220730.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220720_20220730.parquet)

- **July 30 - August 8, 2022**  
  [Download flight_events_20220730_20220809.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220730_20220809.parquet)

- **August 9 - 18, 2022**  
  [Download flight_events_20220809_20220819.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220809_20220819.parquet)

- **August 19 - 28, 2022**  
  [Download flight_events_20220819_20220829.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220819_20220829.parquet)

- **August 29 - September 7, 2022**  
  [Download flight_events_20220829_20220908.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220829_20220908.parquet)

- **September 8 - 17, 2022**  
  [Download flight_events_20220908_20220918.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220908_20220918.parquet)

- **September 18 - 27, 2022**  
  [Download flight_events_20220918_20220928.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220918_20220928.parquet)

- **September 28 - October 7, 2022**  
  [Download flight_events_20220928_20221008.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20220928_20221008.parquet)

- **October 8 - 17, 2022**  
  [Download flight_events_20221008_20221018.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221008_20221018.parquet)

- **October 18 - 27, 2022**  
  [Download flight_events_20221018_20221028.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221018_20221028.parquet)

- **October 28 - November 6, 2022**  
  [Download flight_events_20221028_20221107.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221028_20221107.parquet)

- **November 7 - 16, 2022**  
  [Download flight_events_20221107_20221117.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221107_20221117.parquet)

- **November 17 - 26, 2022**  
  [Download flight_events_20221117_20221127.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221117_20221127.parquet)

- **November 27 - December 6, 2022**  
  [Download flight_events_20221127_20221207.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221127_20221207.parquet)

- **December 7 - 16, 2022**  
  [Download flight_events_20221207_20221217.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221207_20221217.parquet)

- **December 17 - 26, 2022**  
  [Download flight_events_20221217_20221227.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221217_20221227.parquet)

- **December 27, 2022 - January 5, 2023**  
  [Download flight_events_20221227_20230106.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20221227_20230106.parquet)

### 2023

- **January 6 - 15, 2023**  
  [Download flight_events_20230106_20230116.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230106_20230116.parquet)

- **January 16 - 25, 2023**  
  [Download flight_events_20230116_20230126.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230116_20230126.parquet)

- **January 26 - February 4, 2023**  
  [Download flight_events_20230126_20230205.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230126_20230205.parquet)

- **February 5 - 14, 2023**  
  [Download flight_events_20230205_20230215.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230205_20230215.parquet)

- **February 15 - 24, 2023**  
  [Download flight_events_20230215_20230225.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230215_20230225.parquet)

- **February 25 - March 6, 2023**  
  [Download flight_events_20230225_20230307.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230225_20230307.parquet)

- **March 7 - 16, 2023**  
  [Download flight_events_20230307_20230317.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230307_20230317.parquet)

- **March 17 - 26, 2023**  
  [Download flight_events_20230317_20230327.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230317_20230327.parquet)

- **March 27 - April 5, 2023**  
  [Download flight_events_20230327_20230406.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230327_20230406.parquet)

- **April 6 - 15, 2023**  
  [Download flight_events_20230406_20230416.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230406_20230416.parquet)

- **April 16 - 25, 2023**  
  [Download flight_events_20230416_20230426.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230416_20230426.parquet)

- **April 26 - May 5, 2023**  
  [Download flight_events_20230426_20230506.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230426_20230506.parquet)

- **May 6 - 15, 2023**  
  [Download flight_events_20230506_20230516.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230506_20230516.parquet)

- **May 16 - 25, 2023**  
  [Download flight_events_20230516_20230526.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230516_20230526.parquet)

- **May 26 - June 4, 2023**  
  [Download flight_events_20230526_20230605.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230526_20230605.parquet)

- **June 5 - 14, 2023**  
  [Download flight_events_20230605_20230615.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230605_20230615.parquet)

- **June 15 - 24, 2023**  
  [Download flight_events_20230615_20230625.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230615_20230625.parquet)

- **June 25 - July 4, 2023**  
  [Download flight_events_20230625_20230705.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230625_20230705.parquet)

- **July 5 - 14, 2023**  
  [Download flight_events_20230705_20230715.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230705_20230715.parquet)

- **July 15 - 24, 2023**  
  [Download flight_events_20230715_20230725.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230715_20230725.parquet)

- **July 25 - August 3, 2023**  
  [Download flight_events_20230725_20230804.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230725_20230804.parquet)

- **August 4 - 13, 2023**  
  [Download flight_events_20230804_20230814.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230804_20230814.parquet)

- **August 14 - 23, 2023**  
  [Download flight_events_20230814_20230824.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230814_20230824.parquet)

- **August 24 - September 2, 2023**  
  [Download flight_events_20230824_20230903.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230824_20230903.parquet)

- **September 3 - 12, 2023**  
  [Download flight_events_20230903_20230913.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230903_20230913.parquet)

- **September 13 - 22, 2023**  
  [Download flight_events_20230913_20230923.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230913_20230923.parquet)

- **September 23 - October 2, 2023**  
  [Download flight_events_20230923_20231003.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20230923_20231003.parquet)

- **October 3 - 12, 2023**  
  [Download flight_events_20231003_20231013.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231003_20231013.parquet)

- **October 13 - 22, 2023**  
  [Download flight_events_20231013_20231023.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231013_20231023.parquet)

- **October 23 - November 1, 2023**  
  [Download flight_events_20231023_20231102.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231023_20231102.parquet)

- **November 2 - 11, 2023**  
  [Download flight_events_20231102_20231112.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231102_20231112.parquet)

- **November 12 - 21, 2023**  
  [Download flight_events_20231112_20231122.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231112_20231122.parquet)

- **November 22 - December 1, 2023**  
  [Download flight_events_20231122_20231202.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231122_20231202.parquet)

- **December 2 - 11, 2023**  
  [Download flight_events_20231202_20231212.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231202_20231212.parquet)

- **December 12 - 21, 2023**  
  [Download flight_events_20231212_20231222.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231212_20231222.parquet)

- **December 22 - 31, 2023**  
  [Download flight_events_20231222_20240101.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20231222_20240101.parquet)

### 2024

- **January 1 - 10, 2024**  
  [Download flight_events_20240101_20240111.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240101_20240111.parquet)

- **January 11 - 20, 2024**  
  [Download flight_events_20240111_20240121.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240111_20240121.parquet)

- **January 21 - 30, 2024**  
  [Download flight_events_20240121_20240131.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240121_20240131.parquet)

- **January 31 - February 9, 2024**  
  [Download flight_events_20240131_20240210.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240131_20240210.parquet)

- **February 10 - 19, 2024**  
  [Download flight_events_20240210_20240220.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240210_20240220.parquet)

- **February 20 - 29, 2024**  
  [Download flight_events_20240220_20240301.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240220_20240301.parquet)

- **March 1 - 10, 2024**  
  [Download flight_events_20240301_20240311.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240301_20240311.parquet)

- **March 11 - 20, 2024**  
  [Download flight_events_20240311_20240321.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240311_20240321.parquet)

- **March 21 - 30, 2024**  
  [Download flight_events_20240321_20240331.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240321_20240331.parquet)

- **March 31 - April 9, 2024**  
  [Download flight_events_20240331_20240410.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240331_20240410.parquet)

- **April 10 - 19, 2024**  
  [Download flight_events_20240410_20240420.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240410_20240420.parquet)

- **April 20 - 29, 2024**  
  [Download flight_events_20240420_20240430.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240420_20240430.parquet)

- **April 30 - May 9, 2024**  
  [Download flight_events_20240430_20240510.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240430_20240510.parquet)

- **May 10 - 19, 2024**  
  [Download flight_events_20240510_20240520.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240510_20240520.parquet)

- **May 20 - 29, 2024**  
  [Download flight_events_20240520_20240530.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240520_20240530.parquet)

- **May 30 - June 8, 2024**  
  [Download flight_events_20240530_20240609.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240530_20240609.parquet)

- **June 9 - 18, 2024**  
  [Download flight_events_20240609_20240619.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240609_20240619.parquet)

- **June 19 - 28, 2024**  
  [Download flight_events_20240619_20240629.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240619_20240629.parquet)

- **June 29 - July 8, 2024**  
  [Download flight_events_20240629_20240709.parquet](https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_events/flight_events_20240629_20240709.parquet)

---

We hope you find these datasets useful for your analysis and research. If you have any questions or require further assistance, please contact us at [support@ansperformance.eu](mailto:support@ansperformance.eu).
