---
title: "Roadmap"
---



The plan is to release subsequent improvements of the \acr{OPDI} data sets roughly every two months as data and validations become available. 

## Upcoming focus

The next planned updates aim to include the following improvements:

- Inclusion of new event types and occurrences:
  * off-block
  * in-block
  * \acr{FIR} crossing

### Candidate topics for future releases

In the longer term the \acr{OPDI} aims to include the following improvements:

- Include more events
  * start and stop of holdings
- Use third party trajectory data (aside from the available via \acr{OSN}).
- Validate flight events and measurements using third party data.
- Provide easy access to \acr{OSN} state vector trajectories at 5-sec granularity
- Provide cleaned up state vector based trajectories, i.e. remove vertical glitches
  (via `filter()` in [`traffic`](https://traffic-viz.github.io/index.html) library), associate meteorological information (via
  [`fastmeteo`](https://github.com/junzis/fastmeteo) library), remove dirty trajectories (too small/short), ...

## Past Releases

An overview of past releases and the various versions were used in each OPDI version can be seen below.

| OPDI version | Release date   | Flight List | Flight Event | Measurements | Period |
|--------------|----------------|---------------------|----------------------|----------------------|----------|
| OPDI v0.0.1  | 2023-12-01| Flight List v0.0.1  | Flight Event v0.0.1  | Measurements v0.0.1  | 2 months |
| OPDI v0.0.2 (release 1) | 2024-03-01| Flight List v0.0.2  | Flight Event v0.0.2  | Measurements v0.0.2  | 1.5 years |
| OPDI v0.0.2 (release 2) | 2024-08-01| Flight List v0.0.2  | Flight Event v0.0.2  | Measurements v0.0.2  | 2.5 years |
| OPDI v0.0.2 (release 3) | 2024-12-01| Flight List v0.0.2  | Flight Event v0.0.2  | Measurements v0.0.2  | 3 years |

## Contact

If you notice any bugs, or if you have any feature requests, please [contact us](mailto:pru-support@eurocontrol.int).


