<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="EUROCONTROL Performance Review Unit">
<meta name="dcterms.date" content="2026-08-05">

<title>Detecting departure and destination aerodromes from ADS-B – OPDI Papers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3fc44999f41da3927fa35e4e05887fd4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">OPDI Papers</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.eurocontrol.int/opdi"> 
<span class="menu-text">OPDI</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#why-this-is-hard" id="toc-why-this-is-hard" class="nav-link" data-scroll-target="#why-this-is-hard"><span class="header-section-number">1</span> Why this is hard</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#samples" id="toc-samples" class="nav-link" data-scroll-target="#samples"><span class="header-section-number">2.1</span> Samples</a></li>
  <li><a href="#trajectories" id="toc-trajectories" class="nav-link" data-scroll-target="#trajectories"><span class="header-section-number">2.2</span> Trajectories</a></li>
  <li><a href="#aircraft-selection" id="toc-aircraft-selection" class="nav-link" data-scroll-target="#aircraft-selection"><span class="header-section-number">2.3</span> Aircraft selection</a></li>
  <li><a href="#ground-truth" id="toc-ground-truth" class="nav-link" data-scroll-target="#ground-truth"><span class="header-section-number">2.4</span> Ground truth</a></li>
  </ul></li>
  <li><a href="#how-methods-are-scored" id="toc-how-methods-are-scored" class="nav-link" data-scroll-target="#how-methods-are-scored"><span class="header-section-number">3</span> How methods are scored</a></li>
  <li><a href="#the-candidate-methods" id="toc-the-candidate-methods" class="nav-link" data-scroll-target="#the-candidate-methods"><span class="header-section-number">4</span> The candidate methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5</span> Results</a></li>
  <li><a href="#cascade" id="toc-cascade" class="nav-link" data-scroll-target="#cascade"><span class="header-section-number">6</span> The cascade, and why it fails</a></li>
  <li><a href="#abstention-on-the-endpoint" id="toc-abstention-on-the-endpoint" class="nav-link" data-scroll-target="#abstention-on-the-endpoint"><span class="header-section-number">7</span> Abstention on the endpoint</a>
  <ul class="collapse">
  <li><a href="#which-operating-points-beat-production" id="toc-which-operating-points-beat-production" class="nav-link" data-scroll-target="#which-operating-points-beat-production"><span class="header-section-number">7.1</span> Which operating points beat production</a></li>
  </ul></li>
  <li><a href="#per-aerodrome-movement-counts" id="toc-per-aerodrome-movement-counts" class="nav-link" data-scroll-target="#per-aerodrome-movement-counts"><span class="header-section-number">8</span> Per-aerodrome movement counts</a></li>
  <li><a href="#recommendation" id="toc-recommendation" class="nav-link" data-scroll-target="#recommendation"><span class="header-section-number">9</span> Recommendation</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">10</span> Limitations</a></li>
  <li><a href="#reproducing" id="toc-reproducing" class="nav-link" data-scroll-target="#reproducing"><span class="header-section-number">11</span> Reproducing</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Detecting departure and destination aerodromes from ADS-B</h1>
<p class="subtitle lead">A methodology comparison against EUROCONTROL APDF ground truth</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>EUROCONTROL Performance Review Unit </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>The OPDI flight list assigns each flight a departure aerodrome (ADEP) and a destination aerodrome (ADES) from ADS-B alone. The production algorithm tests the sign of a smoothed altitude trend near each candidate aerodrome and discards every flight whose trend is ambiguous. It is accurate where it speaks — 97.50% on ADEP — and silent on almost half of all flights.</p>
<p>We compared seven methodologies against EUROCONTROL APDF ground truth over two three-day samples a year apart, 187,961 flights in total. Three findings:</p>
<ol type="1">
<li><p><strong>Coverage is the problem, not accuracy.</strong> Every trend-based method scores above 94% where it fires, and none covers more than 57% of flights.</p></li>
<li><p><strong>The vertical-trend machinery earns nothing.</strong> Attributing a cascade’s answers to the rung that supplied them shows that the simplest possible rule — <em>the nearest aerodrome to the track’s first and last sample</em> — is at least as accurate as every trend-based method <strong>on that method’s own flights</strong>, in both samples. A five-stage cascade built on those methods collapses exactly onto the one-line rule, to two decimal places, in both months.</p></li>
<li><p><strong>Replacing the trend logic with explicit abstention improves departures, and does not improve arrivals.</strong> Naming the nearest aerodrome to the endpoint, but staying silent unless that endpoint is credibly <em>at</em> an aerodrome, beats the production algorithm on coverage and accuracy at once for ADEP — by 8 to 10 percentage points of coverage — in both samples. For ADES the same construction wins in one sample and not in the other, so we do not claim it.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What changed since the first draft
</div>
</div>
<div class="callout-body-container callout-body">
<p>An earlier version of this page reported a single day and stated finding 3 without restricting it to departures. Scoring the second sample removed that claim for arrivals: in 2024-06 endpoint abstention beats production on ADES by +4.47 pp of coverage at matched accuracy, and in 2025-06 the best it can do is -0.28 pp.&nbsp;Fitting on one month and validating on the other is what caught it.</p>
</div>
</div>
</section>
<section id="why-this-is-hard" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="why-this-is-hard"><span class="header-section-number">1</span> Why this is hard</h2>
<p>An ADS-B trajectory does not carry its origin or destination. Both must be inferred from where the aircraft was and what it was doing, and the inference fails in a specific, asymmetric way: reception near the ground is patchy. A receiver 50 NM from a regional aerodrome sees an aircraft in the cruise perfectly and never sees it below 2,000 ft. So the evidence that would settle the question — surface movement, the take-off roll, the flare — is exactly the evidence most often missing.</p>
<p>Three consequences shape everything below:</p>
<ul>
<li><strong>Tracks frequently begin or end in mid-air.</strong> A track that starts in the cruise has no departure evidence at all, and any method that names an aerodrome for it is guessing.</li>
<li><strong>Departure and destination are not symmetric.</strong> Departure evidence is a climb from a known point; destination evidence is a descent to one. This asymmetry turns out to drive the study’s main negative result.</li>
<li><strong>Nearby aerodromes compete.</strong> Within 30 NM of a major hub there are often several licensed aerodromes and, with heliports, dozens.</li>
</ul>
</section>
<section id="data" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data"><span class="header-section-number">2</span> Data</h2>
<section id="samples" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="samples"><span class="header-section-number">2.1</span> Samples</h3>
<p>Two three-day samples, <strong>2025-06-05 to 07</strong> and <strong>2024-06-05 to 07</strong>, chosen a year apart so that a threshold fitted on one can be validated on the other.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 44%">
<col style="width: 26%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Days</th>
<th style="text-align: right;">Ground-truth flights</th>
<th style="text-align: right;">State vectors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">2024-06-05, 2024-06-06, 2024-06-07</td>
<td style="text-align: right;">92,825</td>
<td style="text-align: right;">111,487,350</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">2025-06-05, 2025-06-06, 2025-06-07</td>
<td style="text-align: right;">95,136</td>
<td style="text-align: right;">105,734,448</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The sample is small in <em>days</em>, not in flights. What a longer run would buy is representativeness across day of week and season, not statistical power; the year-apart design addresses the part of that which matters most.</p>
</section>
<section id="trajectories" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="trajectories"><span class="header-section-number">2.2</span> Trajectories</h3>
<p>State vectors come from the OpenSky Network historical archive, filtered to the OPDI European bounding box and decimated to 5 s — byte-for-byte the filter the production ingestion applies, so the benchmark evaluates the same population the pipeline ingests. Tracks are built with OPDI’s own track-splitting algorithm, imported and called rather than reimplemented, since <code>track_id</code> continuity with published data depends on it.</p>
</section>
<section id="aircraft-selection" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="aircraft-selection"><span class="header-section-number">2.3</span> Aircraft selection</h3>
<p>Only aeroplanes are in scope. Helicopters defeat every aerodrome-based method — they depart from and arrive at places no aerodrome database lists — and they are 9.8% of classified airframes in the OpenSky aircraft database. Filtering uses the ICAO Doc 8643 aircraft class, keeping <code>L</code> (landplane) and <code>A</code> (amphibian). The field is present on ~73% of the database; these results <strong>exclude</strong> unknowns, protecting precision at some cost to coverage.</p>
</section>
<section id="ground-truth" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="ground-truth"><span class="header-section-number">2.4</span> Ground truth</h3>
<p>APDF <code>flights_tidy</code> provides ADEP, ADES and off-block time per flight. <code>AIRCRAFT_ADDRESS</code> is the ICAO 24-bit address, the join key to ADS-B; flights match on <code>(icao24, callsign, date)</code>. 2.42% of those keys collide — same-day multi-leg rotations — and are resolved by proximity to actual off-block time.</p>
</section>
</section>
<section id="how-methods-are-scored" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="how-methods-are-scored"><span class="header-section-number">3</span> How methods are scored</h2>
<p>Ground truth is the denominator throughout. For real flights <span class="math inline">\(G\)</span> and a method answering on <span class="math inline">\(A \subseteq G\)</span>:</p>
<ul>
<li><strong>Coverage</strong> <span class="math inline">\(= |A| / |G|\)</span> — the fraction of real flights answered at all. A flight whose trajectory was never seen counts as a miss.</li>
<li><strong>Accuracy</strong> <span class="math inline">\(= |\text{correct}| / |A|\)</span> — how often it is right <em>when it speaks</em>.</li>
<li><strong>Overall</strong> <span class="math inline">\(= |\text{correct}| / |G|\)</span> — coverage times accuracy.</li>
</ul>
<p>All three matter, because the production algorithm and its alternatives sit at opposite ends of one trade: one is nearly always right and usually silent, the other nearly always speaks and is often wrong.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The coverage ceiling
</div>
</div>
<div class="callout-body-container callout-body">
<p>No method exceeds ~73% coverage, because that is roughly the share of APDF flights with a usable ADS-B track in the sample at all. The remaining ~27% is a data-availability limit, not an algorithmic one.</p>
</div>
</div>
</section>
<section id="the-candidate-methods" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-candidate-methods"><span class="header-section-number">4</span> The candidate methods</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Method</th>
<th>Signal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>M0</strong></td>
<td><em>Current production</em></td>
<td>Sign of a 5-sample rolling-mean altitude difference near each candidate aerodrome, margin of 4; ambiguous flights dropped</td>
</tr>
<tr class="even">
<td><strong>M1</strong></td>
<td><em>traffic library</em></td>
<td>Nearest aerodrome to the track’s first sample (ADEP) and last sample (ADES). No altitude, no trend, no ground state</td>
</tr>
<tr class="odd">
<td><strong>M2</strong></td>
<td><em>On-ground</em></td>
<td>Aerodrome at the surface samples bracketing the airborne phase</td>
</tr>
<tr class="even">
<td><strong>M3</strong></td>
<td><em>Vertical rate</em></td>
<td>Sign of the measured <code>vert_rate</code> near each candidate aerodrome</td>
</tr>
<tr class="odd">
<td><strong>M5</strong></td>
<td><em>Lowest and nearest</em></td>
<td>Aerodrome where the track is lowest and closest, split at the track midpoint</td>
</tr>
<tr class="even">
<td><strong>M6</strong></td>
<td><em>Cascade</em></td>
<td>Take the most precise available answer, falling through when a rung is silent</td>
</tr>
<tr class="odd">
<td><strong>M7</strong></td>
<td><em>Endpoint with abstention</em></td>
<td>M1’s naming rule, silent unless the endpoint is close to the aerodrome and low over it</td>
</tr>
</tbody>
</table>
<p>M1 recreates <code>TakeoffAirportInference</code> / <code>LandingAirportInference</code> from the <code>traffic</code> library. M2 and M3 use columns the production algorithm already selects and never reads: <code>on_ground</code> and <code>vert_rate</code>.</p>
</section>
<section id="results" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="results"><span class="header-section-number">5</span> Results</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Coverage, accuracy and overall correctness by method and sample, sorted within each sample by ADEP overall correctness.</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">ADEP cov</th>
<th style="text-align: right;">ADEP acc</th>
<th style="text-align: right;">ADEP overall</th>
<th style="text-align: right;">ADES cov</th>
<th style="text-align: right;">ADES acc</th>
<th style="text-align: right;">ADES overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M6_cascade</td>
<td style="text-align: right;">73.48%</td>
<td style="text-align: right;">84.60%</td>
<td style="text-align: right;">62.16%</td>
<td style="text-align: right;">73.46%</td>
<td style="text-align: right;">75.31%</td>
<td style="text-align: right;">55.32%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M1_traffic</td>
<td style="text-align: right;">71.75%</td>
<td style="text-align: right;">86.63%</td>
<td style="text-align: right;">62.16%</td>
<td style="text-align: right;">70.44%</td>
<td style="text-align: right;">78.51%</td>
<td style="text-align: right;">55.30%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">56.55%</td>
<td style="text-align: right;">99.05%</td>
<td style="text-align: right;">56.01%</td>
<td style="text-align: right;">48.87%</td>
<td style="text-align: right;">97.22%</td>
<td style="text-align: right;">47.51%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M3_vert_rate</td>
<td style="text-align: right;">54.94%</td>
<td style="text-align: right;">97.04%</td>
<td style="text-align: right;">53.31%</td>
<td style="text-align: right;">51.52%</td>
<td style="text-align: right;">94.93%</td>
<td style="text-align: right;">48.91%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M5_min_alt</td>
<td style="text-align: right;">68.03%</td>
<td style="text-align: right;">77.26%</td>
<td style="text-align: right;">52.56%</td>
<td style="text-align: right;">67.85%</td>
<td style="text-align: right;">72.54%</td>
<td style="text-align: right;">49.22%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M0_current</td>
<td style="text-align: right;">52.22%</td>
<td style="text-align: right;">97.57%</td>
<td style="text-align: right;">50.95%</td>
<td style="text-align: right;">51.11%</td>
<td style="text-align: right;">94.34%</td>
<td style="text-align: right;">48.22%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M2_on_ground</td>
<td style="text-align: right;">23.59%</td>
<td style="text-align: right;">97.78%</td>
<td style="text-align: right;">23.07%</td>
<td style="text-align: right;">26.21%</td>
<td style="text-align: right;">96.43%</td>
<td style="text-align: right;">25.28%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M1_traffic</td>
<td style="text-align: right;">67.96%</td>
<td style="text-align: right;">86.99%</td>
<td style="text-align: right;">59.13%</td>
<td style="text-align: right;">66.78%</td>
<td style="text-align: right;">78.30%</td>
<td style="text-align: right;">52.29%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M6_cascade</td>
<td style="text-align: right;">69.66%</td>
<td style="text-align: right;">84.87%</td>
<td style="text-align: right;">59.13%</td>
<td style="text-align: right;">69.60%</td>
<td style="text-align: right;">75.15%</td>
<td style="text-align: right;">52.31%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">54.63%</td>
<td style="text-align: right;">99.03%</td>
<td style="text-align: right;">54.10%</td>
<td style="text-align: right;">46.86%</td>
<td style="text-align: right;">97.01%</td>
<td style="text-align: right;">45.46%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M3_vert_rate</td>
<td style="text-align: right;">53.58%</td>
<td style="text-align: right;">96.90%</td>
<td style="text-align: right;">51.92%</td>
<td style="text-align: right;">50.10%</td>
<td style="text-align: right;">95.68%</td>
<td style="text-align: right;">47.94%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M5_min_alt</td>
<td style="text-align: right;">65.32%</td>
<td style="text-align: right;">78.60%</td>
<td style="text-align: right;">51.34%</td>
<td style="text-align: right;">65.10%</td>
<td style="text-align: right;">73.66%</td>
<td style="text-align: right;">47.95%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M0_current</td>
<td style="text-align: right;">51.10%</td>
<td style="text-align: right;">97.50%</td>
<td style="text-align: right;">49.82%</td>
<td style="text-align: right;">49.71%</td>
<td style="text-align: right;">95.65%</td>
<td style="text-align: right;">47.55%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M2_on_ground</td>
<td style="text-align: right;">23.19%</td>
<td style="text-align: right;">95.63%</td>
<td style="text-align: right;">22.17%</td>
<td style="text-align: right;">26.83%</td>
<td style="text-align: right;">93.16%</td>
<td style="text-align: right;">24.99%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The shape of the table is the first finding, and it is the same in both samples. The production algorithm M0 is among the <strong>most accurate</strong> methods tested and among the <strong>worst</strong> by overall correctness, because it declines to answer nearly half the flights. <code>traffic</code>’s one-line nearest-aerodrome rule, with no aviation logic in it whatsoever, gets more flights right in absolute terms than any trend-based method.</p>
<p>That is not an argument for adopting M1 as it stands — an 86.99% ADEP accuracy would be a serious regression for a flight list downstream users treat as authoritative. It is an argument that the trend logic is not where the value is.</p>
</section>
<section id="cascade" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="cascade"><span class="header-section-number">6</span> The cascade, and why it fails</h2>
<p>The natural response is a cascade: take M0’s answer when it speaks, fall through to M3, then M2, and use M1 only as a last resort. The strong signals keep their precision and M1 supplies coverage where they are silent.</p>
<p>It does not work, and the way it fails is instructive.</p>
<p>A cascade’s accuracy is <em>not</em> bounded below by its rungs’ accuracies, because each rung is scored only on the flights the rungs above it could not answer, which are the harder ones. So a cascade scoring below every method it is built from is not by itself evidence of a bug. What it must not do is score below its own fallback rung used alone — that means some rung is actively overwriting better answers.</p>
<p>To test that, every cascade answer is attributed to the rung that supplied it, and that rung is scored against a control on <strong>the same flights</strong>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>ADEP attribution for the precision-ordered cascade M0 -&gt; M3 -&gt; M2 -&gt; M1 -&gt; M5, with M1 as the control. A negative lift means the rung overwrote a better answer.</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 25%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Rung</th>
<th style="text-align: right;">Flights answered</th>
<th style="text-align: right;">Share of all</th>
<th style="text-align: right;">Its accuracy</th>
<th style="text-align: right;">M1 on the same flights</th>
<th style="text-align: right;">Lift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">m0</td>
<td style="text-align: right;">48,477</td>
<td style="text-align: right;">52.22%</td>
<td style="text-align: right;">97.57%</td>
<td style="text-align: right;">99.07%</td>
<td style="text-align: right;">-1.51 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">m3</td>
<td style="text-align: right;">2,726</td>
<td style="text-align: right;">2.94%</td>
<td style="text-align: right;">88.85%</td>
<td style="text-align: right;">93.21%</td>
<td style="text-align: right;">-4.37 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">m2</td>
<td style="text-align: right;">313</td>
<td style="text-align: right;">0.34%</td>
<td style="text-align: right;">13.42%</td>
<td style="text-align: right;">46.96%</td>
<td style="text-align: right;">-33.55 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">m1</td>
<td style="text-align: right;">15,182</td>
<td style="text-align: right;">16.36%</td>
<td style="text-align: right;">46.00%</td>
<td style="text-align: right;">46.00%</td>
<td style="text-align: right;">+0.00 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">m5</td>
<td style="text-align: right;">1,509</td>
<td style="text-align: right;">1.63%</td>
<td style="text-align: right;">0.20%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">+0.20 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">m0</td>
<td style="text-align: right;">48,617</td>
<td style="text-align: right;">51.10%</td>
<td style="text-align: right;">97.50%</td>
<td style="text-align: right;">99.20%</td>
<td style="text-align: right;">-1.70 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">m3</td>
<td style="text-align: right;">2,510</td>
<td style="text-align: right;">2.64%</td>
<td style="text-align: right;">85.14%</td>
<td style="text-align: right;">91.95%</td>
<td style="text-align: right;">-6.81 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">m2</td>
<td style="text-align: right;">782</td>
<td style="text-align: right;">0.82%</td>
<td style="text-align: right;">7.42%</td>
<td style="text-align: right;">44.37%</td>
<td style="text-align: right;">-36.96 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">m1</td>
<td style="text-align: right;">12,859</td>
<td style="text-align: right;">13.52%</td>
<td style="text-align: right;">41.74%</td>
<td style="text-align: right;">41.74%</td>
<td style="text-align: right;">+0.00 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">m5</td>
<td style="text-align: right;">1,507</td>
<td style="text-align: right;">1.58%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">+0.00 pp</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The lift is negative in every row of both samples. So the trend methods do not look precise because they reason well about trajectories. They look precise because they <em>fire on easy flights</em> — those with unambiguous low-altitude coverage near a single aerodrome — and on exactly those flights, “which aerodrome is nearest the endpoint” is already the right answer, slightly more often than the trend vote is.</p>
<p>Running the same cascade with M1 <strong>first</strong> confirms it: the cascade’s overall correctness becomes indistinguishable from M1 alone.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The cascade collapses onto its fallback rung. Four independent comparisons, agreeing to two decimal places.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: right;">M1 ADEP overall</th>
<th style="text-align: right;">M6 ADEP overall</th>
<th style="text-align: right;">M1 ADES overall</th>
<th style="text-align: right;">M6 ADES overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: right;">62.16%</td>
<td style="text-align: right;">62.16%</td>
<td style="text-align: right;">55.30%</td>
<td style="text-align: right;">55.32%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: right;">59.13%</td>
<td style="text-align: right;">59.13%</td>
<td style="text-align: right;">52.29%</td>
<td style="text-align: right;">52.31%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The reframing
</div>
</div>
<div class="callout-body-container callout-body">
<p>The five methods differ in <em>when they are willing to answer</em>, not in <em>what they answer</em>. Their apparent precision is an abstention policy wearing a naming rule’s clothes — and an expensive one, since it discards half the flights to buy accuracy it does not deliver.</p>
<p>So the design question is not which signal should name the aerodrome. It is when to stay silent. And that is a property of the endpoint, not of the trajectory’s shape.</p>
</div>
</div>
</section>
<section id="abstention-on-the-endpoint" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="abstention-on-the-endpoint"><span class="header-section-number">7</span> Abstention on the endpoint</h2>
<p>M7 keeps M1’s naming rule and adds an explicit two-parameter test. An ADEP is emitted only if the track’s first sample is within <span class="math inline">\(d\)</span> NM of the nearest aerodrome and no more than <span class="math inline">\(h\)</span> ft above that aerodrome’s elevation; ADES uses the last sample. Height is measured above field elevation rather than above the ellipsoid, because a fixed 1,000 ft cut-off means nothing at an aerodrome sitting at 5,000 ft. A sample flagged <code>on_ground</code> satisfies the height test outright.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/frontier-plot-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Coverage/accuracy frontier for endpoint abstention, by sample and side. Each line is one distance threshold; points along it are height thresholds relaxing left to right, from on-ground-only to unrestricted. Dotted lines mark the production algorithm M0. The region up and to the right of their intersection beats M0 on both axes at once — populated for ADEP in both samples, and for ADES in 2024-06 only.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>The height threshold does nearly all the work.</strong> Moving the radius from 10 NM to 40 NM changes ADEP coverage by a fraction of a point; moving the height cut from on-ground-only to 5,000 ft AGL moves it by tens of points. An aircraft below 5,000 ft AGL is in the terminal area of the aerodrome it is nearest to, and being 30 NM out at that height does not make it ambiguous. The radius parameter, which is where the production algorithm spends its tuning effort, is close to irrelevant.</p>
<section id="which-operating-points-beat-production" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="which-operating-points-beat-production"><span class="header-section-number">7.1</span> Which operating points beat production</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Grid cells that beat the production algorithm on coverage AND accuracy simultaneously. For ADEP the region is large and consistent across samples; for ADES it is empty in 2025-06.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 25%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Side</th>
<th style="text-align: right;">Cells</th>
<th style="text-align: left;">Best point</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">M0 cov</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">M0 acc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">ADEP</td>
<td style="text-align: right;">18/70</td>
<td style="text-align: left;">20 NM, 15,000 ft</td>
<td style="text-align: right;">61.88%</td>
<td style="text-align: right;">52.22%</td>
<td style="text-align: right;">97.67%</td>
<td style="text-align: right;">97.57%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">ADES</td>
<td style="text-align: right;">7/70</td>
<td style="text-align: left;">40 NM, 10,000 ft</td>
<td style="text-align: right;">55.58%</td>
<td style="text-align: right;">51.11%</td>
<td style="text-align: right;">94.86%</td>
<td style="text-align: right;">94.34%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">ADEP</td>
<td style="text-align: right;">18/70</td>
<td style="text-align: left;">20 NM, 15,000 ft</td>
<td style="text-align: right;">59.04%</td>
<td style="text-align: right;">51.10%</td>
<td style="text-align: right;">97.67%</td>
<td style="text-align: right;">97.50%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">ADES</td>
<td style="text-align: right;">0/70</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">49.71%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">95.65%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>For <strong>departures</strong> the answer is unambiguous and it replicates: 18 of 70 grid cells beat production on both axes in each sample, and the best of them — <strong>20 NM and 15,000 ft AGL</strong> — reaches 59.04% coverage in 2025-06 and 61.88% in 2024-06, at 97.67% accuracy in <strong>both</strong>. That is 8 to 10 percentage points of coverage over production at slightly better accuracy.</p>
<p>For <strong>arrivals</strong> it does not replicate. In 2024-06 seven cells beat production, the best by +4.47 pp of coverage at matched accuracy. In 2025-06 <strong>none do</strong>: production already sits on the achievable frontier, and the closest M7 gets is -0.28 pp.&nbsp;Two three-day samples disagree, so the honest conclusion is that endpoint abstention does not demonstrably improve ADES.</p>
<p>Why the sides differ is not mysterious. A departure’s first sample is either at a stand or it is not, and the aircraft was stationary moments earlier. An arrival’s last sample is more often a <strong>loss of reception during descent</strong> than a landing — it can be anywhere on the approach, at any height, tens of miles out. The endpoint is simply a weaker instrument for arrivals, and no threshold on it recovers what was never observed.</p>
</section>
</section>
<section id="per-aerodrome-movement-counts" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="per-aerodrome-movement-counts"><span class="header-section-number">8</span> Per-aerodrome movement counts</h2>
<p>Flight-level accuracy can hide errors that cancel: a departure misattributed from A to B leaves both counts wrong and the total right. Movement counts per aerodrome are the number an operational user actually reads, so they are reported separately.</p>
<p>The comparison is restricted to aerodromes the method could ever have named — European large and medium airports inside the sampled bounding box. Ground truth names every destination a flight really had, including small fields and airports on other continents; an unrestricted comparison measures that mismatch rather than the method.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>M7 movement counts against APDF, restricted to in-scope aerodromes. A count ratio below 1 is an undercount.</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Movements</th>
<th style="text-align: right;">Aerodromes</th>
<th style="text-align: right;">Count ratio</th>
<th style="text-align: right;">Median recall</th>
<th style="text-align: right;">Median recall, 50+ movements</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">departures</td>
<td style="text-align: right;">670</td>
<td style="text-align: right;">0.618</td>
<td style="text-align: right;">33.33%</td>
<td style="text-align: right;">66.67%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">arrivals</td>
<td style="text-align: right;">669</td>
<td style="text-align: right;">0.533</td>
<td style="text-align: right;">22.08%</td>
<td style="text-align: right;">58.14%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">departures</td>
<td style="text-align: right;">683</td>
<td style="text-align: right;">0.599</td>
<td style="text-align: right;">27.27%</td>
<td style="text-align: right;">63.78%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">arrivals</td>
<td style="text-align: right;">677</td>
<td style="text-align: right;">0.511</td>
<td style="text-align: right;">22.22%</td>
<td style="text-align: right;">54.03%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Busiest aerodromes by APDF departures, 2025-06.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Aerodrome</th>
<th style="text-align: right;">APDF departures</th>
<th style="text-align: right;">OPDI assigned</th>
<th style="text-align: right;">Count ratio</th>
<th style="text-align: right;">Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LTFM</td>
<td style="text-align: right;">2,282</td>
<td style="text-align: right;">1,711</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">74.72%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EHAM</td>
<td style="text-align: right;">2,148</td>
<td style="text-align: right;">1,613</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">74.35%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDF</td>
<td style="text-align: right;">2,094</td>
<td style="text-align: right;">1,729</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">82.43%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFPG</td>
<td style="text-align: right;">2,084</td>
<td style="text-align: right;">1,616</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">77.06%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGLL</td>
<td style="text-align: right;">2,001</td>
<td style="text-align: right;">1,575</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">78.66%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEMD</td>
<td style="text-align: right;">1,773</td>
<td style="text-align: right;">1,346</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">75.92%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEBL</td>
<td style="text-align: right;">1,591</td>
<td style="text-align: right;">1,248</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">78.32%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDDM</td>
<td style="text-align: right;">1,573</td>
<td style="text-align: right;">1,273</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">80.80%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIRF</td>
<td style="text-align: right;">1,449</td>
<td style="text-align: right;">935</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">64.53%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTAI</td>
<td style="text-align: right;">1,435</td>
<td style="text-align: right;">723</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">50.03%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Two things stand out. <strong>The error is always an undercount</strong> — no aerodrome is credited with movements it did not have. That is the good failure mode: a systematic undercount can be corrected for, an overcount cannot. And <strong>recall scales with aerodrome size</strong>: 75–87% at the busiest hubs, around 65% median at aerodromes with 50 or more movements, and poor in the long tail. OPDI’s flight list is substantially more complete at large aerodromes than small ones, which is worth knowing before using it for a comparison across aerodrome classes.</p>
<p>The exception is instructive: <strong>LTAI (Antalya)</strong> sits at a count ratio of 0.50 in 2025-06 and 0.26 in 2024-06, far below every comparable hub. That is a receiver-coverage blackspot, not an algorithmic failure, and no change to the detection rule will fix it.</p>
</section>
<section id="recommendation" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="recommendation"><span class="header-section-number">9</span> Recommendation</h2>
<p><strong>For departures, adopt endpoint abstention.</strong> Nearest aerodrome to the track’s first sample, emitted only when that sample is within 20 NM and below 15,000 ft above field elevation. This is a smaller algorithm than the one it replaces — no smoothing window, no margin parameter, no per-aerodrome vote — and it gains 8 to 10 percentage points of ADEP coverage at slightly better accuracy, in both samples.</p>
<p><strong>For arrivals, do not change the algorithm on this evidence.</strong> The same construction wins in one sample and loses in the other. If ADES coverage is judged more valuable than the last point of accuracy, the frontier above gives the available trades explicitly — but that is a policy decision, not a finding.</p>
<p>In both cases the thresholds should be published alongside the flight list, and <strong>the abstention reason retained per flight</strong>, so downstream users can distinguish “no departure aerodrome” from “departure aerodrome not determinable”. The current algorithm collapses those into a null, a loss of information that costs nothing to preserve.</p>
</section>
<section id="limitations" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="limitations"><span class="header-section-number">10</span> Limitations</h2>
<ul>
<li><strong>Six days.</strong> Two three-day samples. What a longer run would buy is representativeness across day of week and season, not statistical power. The ADES result shows the exposure is real: two samples a year apart disagreed.</li>
<li><strong>No trajectory cleaning.</strong> State vectors are raw apart from the bounding box and decimation. OPDI’s cleaning stage is implemented and not yet applied here, and whether it helps is genuinely open: the stale-broadcast filter nulls repeated positions, which is precisely what a stationary aircraft at a gate transmits. It could remove the very samples the endpoint rule depends on. This will be measured as an ablation, not assumed.</li>
<li><strong>Aircraft filtering is one layer of three.</strong> The ADS-B emitter category — the only field naming surface vehicles — is dropped by the reference pipeline stage and would need retaining. A behavioural filter requiring a sustained airborne period is database-independent and would catch the 27% of airframes with no recorded class.</li>
<li><strong>Aerodrome set is fixed.</strong> All results use large and medium airports. Sweeping small airports and heliports is implemented but not yet reported.</li>
<li><strong>The two sides share one threshold pair.</strong> M7 applies the same <span class="math inline">\(d\)</span> and <span class="math inline">\(h\)</span> to departures and arrivals. Given how differently the two behave, fitting them separately is the obvious next step.</li>
</ul>
</section>
<section id="reproducing" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="reproducing"><span class="header-section-number">11</span> Reproducing</h2>
<p>Everything is in the <code>opdi</code> repository under <code>benchmarks/</code>, and every dataset written is registered in <code>benchmarks/DATASETS.md</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Sample state vectors from the OpenSky archive into S3</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/osn_sample.py 2025-06-05 2025-06-08</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Score every method</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/adep_ades.py <span class="at">--days</span> 2025-06-05 2025-06-06 2025-06-07 <span class="dt">\</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">--months</span> 202506 <span class="at">--methods</span> all <span class="at">--ladder</span> m1 m0 m3 m2 m5 <span class="at">--sweep-abstain</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Attribute the cascade's answers, and count movements per aerodrome</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/adep_ades.py <span class="at">--days</span> 2025-06-05 2025-06-06 2025-06-07 <span class="dt">\</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">--months</span> 202506 <span class="at">--methods</span> none <span class="at">--diagnose-cascade</span> <span class="at">--control</span> m1 <span class="dt">\</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">--per-airport</span> M7_abstain</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Refresh this page's CSV cache (both samples)</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/export_results.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Steps 1–3 run on the OpenSky Kubernetes cluster and need credentials; step 4 needs S3 read access. Rendering this page needs neither — no credentials, no database, no cluster.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>