<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="EUROCONTROL Performance Review Unit">
<meta name="dcterms.date" content="2026-08-06">

<title>Detecting departure and destination aerodromes from ADS-B – OPDI Papers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3fc44999f41da3927fa35e4e05887fd4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">OPDI Papers</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.eurocontrol.int/opdi"> 
<span class="menu-text">OPDI</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#what-changed-since-version-2" id="toc-what-changed-since-version-2" class="nav-link" data-scroll-target="#what-changed-since-version-2">What changed since version 2</a></li>
  <li><a href="#sec-ooa" id="toc-sec-ooa" class="nav-link" data-scroll-target="#sec-ooa"><span class="header-section-number">1</span> Reporting out-of-area</a></li>
  <li><a href="#sec-sched" id="toc-sec-sched" class="nav-link" data-scroll-target="#sec-sched"><span class="header-section-number">2</span> The military-airfield confusion</a></li>
  <li><a href="#sec-errors" id="toc-sec-errors" class="nav-link" data-scroll-target="#sec-errors"><span class="header-section-number">3</span> Where the remaining errors are</a></li>
  <li><a href="#sec-perside" id="toc-sec-perside" class="nav-link" data-scroll-target="#sec-perside"><span class="header-section-number">4</span> Per-side thresholds do not help</a></li>
  <li><a href="#everything-else-unchanged" id="toc-everything-else-unchanged" class="nav-link" data-scroll-target="#everything-else-unchanged"><span class="header-section-number">5</span> Everything else, unchanged</a></li>
  <li><a href="#sec-recommendations" id="toc-sec-recommendations" class="nav-link" data-scroll-target="#sec-recommendations"><span class="header-section-number">6</span> Recommendations</a>
  <ul class="collapse">
  <li><a href="#already-implemented-and-validated-in-this-study" id="toc-already-implemented-and-validated-in-this-study" class="nav-link" data-scroll-target="#already-implemented-and-validated-in-this-study"><span class="header-section-number">6.1</span> Already implemented and validated in this study</a></li>
  <li><a href="#outstanding-in-the-production-pipeline" id="toc-outstanding-in-the-production-pipeline" class="nav-link" data-scroll-target="#outstanding-in-the-production-pipeline"><span class="header-section-number">6.2</span> Outstanding in the production pipeline</a></li>
  </ul></li>
  <li><a href="#sec-patch" id="toc-sec-patch" class="nav-link" data-scroll-target="#sec-patch"><span class="header-section-number">7</span> Production patch proposal</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations"><span class="header-section-number">8</span> Limitations</a></li>
  <li><a href="#reproducing" id="toc-reproducing" class="nav-link" data-scroll-target="#reproducing"><span class="header-section-number">9</span> Reproducing</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Detecting departure and destination aerodromes from ADS-B</h1>
<p class="subtitle lead">Version 3 — what the residual errors are made of</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>EUROCONTROL Performance Review Unit </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>Version 3 follows a review of <a href="../adep-ades-detection-v2/index.html">version 2</a>. Auditing V2 against its own outputs found four review points only partly delivered and one delivered with a defect. Fixing them changed the results and, more usefully, changed what the <em>remaining</em> errors are made of.</p>
<p>Three things came out of it.</p>
<p><strong>The out-of-area rule was pre-empting good answers.</strong> The border test won unconditionally over a qualifying aerodrome match, so Ponta Delgada — which sits about 8 NM inside the western edge of the ingestion box — had its departures labelled “out of area” with the aircraft still on the runway. A qualifying aerodrome now wins and the border label is the fallback.</p>
<p><strong>Six of the seven most frequent departure errors were the same mistake:</strong> a scheduled civil airport losing to an adjacent military airfield. Izmir to Çiğli Airbase, Naples to Grazzanise, Cagliari to Decimomannu, Catania to Sigonella, Gdańsk to Cewice — 7 to 25 NM apart, and in every case the truth had scheduled service and the prediction did not. Ranking candidates on a distance penalised for aerodromes without scheduled service removes that class of error entirely.</p>
<p><strong>Out-of-area is reported separately now, and it does not work as well as V2 implied.</strong> Precision is high — when the rule says out-of-area it is right about 93% of the time — but recall is only 10 to 15%. The concept is right and the geometric test is weak, for a reason given in <a href="#sec-ooa" class="quarto-xref">Section&nbsp;1</a>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Departure detection: the production algorithm against endpoint abstention, headline and with out-of-area stripped out.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">ADEP cov</th>
<th style="text-align: right;">ADEP acc</th>
<th style="text-align: right;">in-area cov</th>
<th style="text-align: right;">in-area acc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M0_current</td>
<td style="text-align: right;">60.66%</td>
<td style="text-align: right;">97.55%</td>
<td style="text-align: right;">65.83%</td>
<td style="text-align: right;">97.64%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">72.41%</td>
<td style="text-align: right;">98.21%</td>
<td style="text-align: right;">77.70%</td>
<td style="text-align: right;">98.35%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M0_current</td>
<td style="text-align: right;">63.59%</td>
<td style="text-align: right;">97.45%</td>
<td style="text-align: right;">69.29%</td>
<td style="text-align: right;">97.53%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">74.85%</td>
<td style="text-align: right;">98.24%</td>
<td style="text-align: right;">80.05%</td>
<td style="text-align: right;">98.50%</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="what-changed-since-version-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="what-changed-since-version-2">What changed since version 2</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Out-of-area precedence fixed</strong> — an aerodrome match now beats the border label.</li>
<li><strong>Scheduled-service tie-break added</strong> — candidates ranked on distance penalised for aerodromes without scheduled service, swept rather than assumed.</li>
<li><strong>Out-of-area reported explicitly</strong> — recall, precision and in-area figures beside the headline, so naming skill and abstention skill cannot be conflated.</li>
<li><strong>Per-side thresholds actually run</strong> — and found not to help (<a href="#sec-perside" class="quarto-xref">Section&nbsp;4</a>).</li>
<li><strong>Residual errors analysed</strong> rather than described (<a href="#sec-errors" class="quarto-xref">Section&nbsp;3</a>).</li>
</ul>
<p>Version 1 and version 2 remain published unchanged. Their numbers are not restated here and are not comparable to these, because the scoring changed.</p>
</div>
</div>
</section>
<section id="sec-ooa" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="sec-ooa"><span class="header-section-number">1</span> Reporting out-of-area</h2>
<p>A flight from Dubai to Amsterdam has a departure aerodrome that no European ADS-B feed can name: the aircraft entered the area already airborne. V2 made <code>OOA</code> a valid answer and a valid truth, which was right. What it did not do was report the two abilities separately, and they are different abilities — naming an aerodrome, and recognising that no aerodrome can be named.</p>
<p>That matters because roughly one departure in twelve is genuinely out of area, so a method could buy accuracy by labelling liberally and an undecomposed table would show only the improvement.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Out-of-area detection for departures. Only M7 and M8 emit the label; the other methods never do, so their recall is zero by construction.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">truly OOA</th>
<th style="text-align: right;">labelled OOA</th>
<th style="text-align: right;">OOA recall</th>
<th style="text-align: right;">OOA precision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">7.94%</td>
<td style="text-align: right;">0.83%</td>
<td style="text-align: right;">9.69%</td>
<td style="text-align: right;">92.25%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M8_extrapolate</td>
<td style="text-align: right;">7.94%</td>
<td style="text-align: right;">1.67%</td>
<td style="text-align: right;">20.36%</td>
<td style="text-align: right;">96.78%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">8.30%</td>
<td style="text-align: right;">1.31%</td>
<td style="text-align: right;">14.84%</td>
<td style="text-align: right;">93.91%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M8_extrapolate</td>
<td style="text-align: right;">8.30%</td>
<td style="text-align: right;">1.17%</td>
<td style="text-align: right;">13.05%</td>
<td style="text-align: right;">92.79%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>High precision, low recall. The rule fires when a track <em>endpoint</em> sits within 30 NM of the bounding box edge — but an inbound flight’s first recorded sample appears wherever a receiver happens to pick it up, which is usually well inside the boundary rather than at it. Most out-of-area departures therefore never look like border cases at all.</p>
<p>The concept is sound; the geometric test is the wrong instrument. A phase-based test would fit the physics better: a track whose first sample is <strong>already in the cruise, neither near an aerodrome nor descending toward one</strong>, has an origin outside the observed area regardless of where it is. That is not implemented here and is the clearest single improvement available (<a href="#sec-limitations" class="quarto-xref">Section&nbsp;8</a>).</p>
</section>
<section id="sec-sched" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-sched"><span class="header-section-number">2</span> The military-airfield confusion</h2>
<p>The most frequent departure errors in version 2 formed one pattern:</p>
<table class="caption-top table">
<caption>In every case the truth had scheduled service and the prediction did not.</caption>
<colgroup>
<col style="width: 34%">
<col style="width: 46%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Truth (scheduled)</th>
<th>Predicted (not scheduled)</th>
<th>Apart</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LTBJ Izmir</td>
<td>LTBL Çiğli Airbase</td>
<td>14.9 NM</td>
</tr>
<tr class="even">
<td>LIRN Naples</td>
<td>LIRM Grazzanise Air Base</td>
<td>14.1 NM</td>
</tr>
<tr class="odd">
<td>LIEE Cagliari</td>
<td>LIED Decimomannu Air Base</td>
<td>7.2 NM</td>
</tr>
<tr class="even">
<td>LICC Catania</td>
<td>LICZ Sigonella Navy Air Base</td>
<td>7.9 NM</td>
</tr>
<tr class="odd">
<td>EPGD Gdańsk</td>
<td>EPCE Cewice Naval Air Base</td>
<td>24.6 NM</td>
</tr>
</tbody>
</table>
<p>A departing aircraft’s first recorded fix is often already a few miles into the climb, and where a military field sits between the airport and the departure track, the nearest-aerodrome rule takes it. Aviation knowledge resolves this without any new data: a commercial flight almost certainly used the aerodrome with scheduled service.</p>
<p>Candidates are therefore ranked on <strong>effective distance</strong> — real distance plus a fixed penalty for aerodromes without scheduled service — so a military field has to be clearly nearest rather than merely nearest. A penalty of zero reproduces the unbiased ranking exactly, which is why it is swept.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/sched-sweep-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Accuracy against the scheduled-service penalty, both samples and both sides. Coverage moves by less than 0.6 pp across the whole range, so this is very nearly a free choice; the curve peaking and turning is what shows the penalty is correcting a bias rather than simply favouring larger aerodromes.</figcaption>
</figure>
</div>
</div>
</div>
<p>Accuracy peaks between 10 and 15 NM on both sides in both samples, then turns over. Coverage falls by under 0.6 pp across the entire range. <strong>10 NM is the defensible choice</strong> — it is at or within a whisker of the peak in all four curves, and the flat top means the exact value is not load-bearing.</p>
</section>
<section id="sec-errors" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-errors"><span class="header-section-number">3</span> Where the remaining errors are</h2>
<p>The tie-break does not reduce errors uniformly. It removes one class and introduces another, and the honest way to report that is by composition.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Composition of the 783 most frequent departure errors after the tie-break.</caption>
<colgroup>
<col style="width: 79%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Flights</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Scheduled → unscheduled (the class the tie-break targets)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unscheduled → scheduled (the tie-break’s own cost)</td>
<td style="text-align: right;">464</td>
<td style="text-align: right;">59.26%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Truth out-of-area, an aerodrome named</td>
<td style="text-align: right;">192</td>
<td style="text-align: right;">24.52%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Truth an aerodrome, labelled out-of-area</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">2.94%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The class the tie-break targets is now <strong>empty</strong>. What dominates instead is its mirror image: genuine movements at non-scheduled aerodromes — Biggin Hill, Northolt — pulled to the nearby hub. That is the price of the preference, it is visible, and it is smaller than what it replaced, which is why accuracy rose.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Most frequent departure confusions after the fixes.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Truth</th>
<th style="text-align: left;">Predicted</th>
<th style="text-align: right;">Flights</th>
<th style="text-align: right;">Apart</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">LCLK</td>
<td style="text-align: left;">OLBA</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">112.0 NM</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">EGKB</td>
<td style="text-align: left;">EGLC</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">10.5 NM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">EGKB</td>
<td style="text-align: left;">EGLC</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">10.5 NM</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">OOA</td>
<td style="text-align: left;">LPPD</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">OOA</td>
<td style="text-align: left;">LPPD</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">LFMD</td>
<td style="text-align: left;">LFMN</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">13.1 NM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">OOA</td>
<td style="text-align: left;">GMMN</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">OJAI</td>
<td style="text-align: left;">OLBA</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">128.5 NM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">OOA</td>
<td style="text-align: left;">UGTB</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">EGWU</td>
<td style="text-align: left;">EGLL</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">5.2 NM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">EGWU</td>
<td style="text-align: left;">EGLL</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">5.2 NM</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">LFMD</td>
<td style="text-align: left;">LFMN</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">13.1 NM</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Two further groups are visible and neither is addressable by threshold tuning. <strong>Long-range misassignments</strong> — Larnaca predicted as Beirut, 112 NM apart — are tracks whose first sample is far from either, where nearest-aerodrome has no real information. <strong>Dense terminal areas</strong> — Biggin Hill against London City at 10.5 NM, Cannes against Nice at 13.1 NM — need runway-level discrimination, which the HexAero layouts OPDI already computes could provide and this study does not use.</p>
</section>
<section id="sec-perside" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-perside"><span class="header-section-number">4</span> Per-side thresholds do not help</h2>
<p>Version 2 noted that departures and arrivals behave differently and suggested fitting their thresholds separately. Doing it properly: fit each side’s threshold on <strong>2024-06</strong> by taking the most coverage available subject to beating the production algorithm’s accuracy, then apply to <strong>2025-06</strong>.</p>
<p>Both sides select the <strong>same</strong> cell, 40 NM and 15,000 ft AGL. The frontier’s shape is similar enough on the two sides that no separation emerges, so the asymmetry between departures and arrivals is not something a threshold can fix — it is in how much information the endpoint carries, not in where the cut-off should sit.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Validation on 2025-06 of thresholds fitted on the other sample.</caption>
<colgroup>
<col style="width: 53%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Configuration</th>
<th style="text-align: right;">ADEP cov</th>
<th style="text-align: right;">ADEP acc</th>
<th style="text-align: right;">ADES cov</th>
<th style="text-align: right;">ADES acc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Production (M0)</td>
<td style="text-align: right;">63.59%</td>
<td style="text-align: right;">97.45%</td>
<td style="text-align: right;">61.97%</td>
<td style="text-align: right;">95.55%</td>
</tr>
<tr class="even">
<td style="text-align: left;">M7 default (20 NM / 15,000 ft)</td>
<td style="text-align: right;">74.85%</td>
<td style="text-align: right;">98.24%</td>
<td style="text-align: right;">63.76%</td>
<td style="text-align: right;">95.11%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M7 fitted on 2024-06 (40 NM / 15,000 ft)</td>
<td style="text-align: right;">75.90%</td>
<td style="text-align: right;">97.86%</td>
<td style="text-align: right;">66.63%</td>
<td style="text-align: right;">93.75%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The fitted point transfers <strong>for departures</strong> — more coverage at better accuracy than production, on a sample it was not fitted to. It does not transfer for arrivals: it buys coverage at a real cost in accuracy. This is the third independent time this study has found that arrivals resist what works for departures.</p>
</section>
<section id="everything-else-unchanged" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="everything-else-unchanged"><span class="header-section-number">5</span> Everything else, unchanged</h2>
<p>The cascade still collapses onto its fallback rung, the aircraft denylist still outperforms the allowlist it replaced, trajectory extrapolation still fails on arrivals, cleaning is still incompatible with endpoint-based arrival detection, and <code>track_id</code> still merges and fragments flights at the rates version 2 measured. Those results are unaffected by the changes here and are not repeated; see <a href="../adep-ades-detection-v2/index.html">version 2</a>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>All methods, both samples, at the default configuration.</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">ADEP cov</th>
<th style="text-align: right;">ADEP acc</th>
<th style="text-align: right;">ADES cov</th>
<th style="text-align: right;">ADES acc</th>
<th style="text-align: right;">ADEP in-area cov</th>
<th style="text-align: right;">ADEP in-area acc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M8_extrapolate</td>
<td style="text-align: right;">76.29%</td>
<td style="text-align: right;">95.53%</td>
<td style="text-align: right;">53.20%</td>
<td style="text-align: right;">67.07%</td>
<td style="text-align: right;">80.35%</td>
<td style="text-align: right;">96.34%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M6_cascade</td>
<td style="text-align: right;">85.41%</td>
<td style="text-align: right;">84.50%</td>
<td style="text-align: right;">85.39%</td>
<td style="text-align: right;">75.42%</td>
<td style="text-align: right;">88.05%</td>
<td style="text-align: right;">89.03%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M1_traffic</td>
<td style="text-align: right;">83.42%</td>
<td style="text-align: right;">86.51%</td>
<td style="text-align: right;">81.96%</td>
<td style="text-align: right;">78.55%</td>
<td style="text-align: right;">87.45%</td>
<td style="text-align: right;">89.63%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">72.41%</td>
<td style="text-align: right;">98.21%</td>
<td style="text-align: right;">64.41%</td>
<td style="text-align: right;">95.63%</td>
<td style="text-align: right;">77.70%</td>
<td style="text-align: right;">98.35%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M3_vert_rate</td>
<td style="text-align: right;">63.79%</td>
<td style="text-align: right;">97.08%</td>
<td style="text-align: right;">59.97%</td>
<td style="text-align: right;">95.01%</td>
<td style="text-align: right;">69.16%</td>
<td style="text-align: right;">97.27%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M5_min_alt</td>
<td style="text-align: right;">79.26%</td>
<td style="text-align: right;">76.92%</td>
<td style="text-align: right;">79.05%</td>
<td style="text-align: right;">72.40%</td>
<td style="text-align: right;">83.45%</td>
<td style="text-align: right;">79.36%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M0_current</td>
<td style="text-align: right;">60.66%</td>
<td style="text-align: right;">97.55%</td>
<td style="text-align: right;">59.45%</td>
<td style="text-align: right;">94.40%</td>
<td style="text-align: right;">65.83%</td>
<td style="text-align: right;">97.64%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-06</td>
<td style="text-align: left;">M2_on_ground</td>
<td style="text-align: right;">27.33%</td>
<td style="text-align: right;">97.70%</td>
<td style="text-align: right;">30.34%</td>
<td style="text-align: right;">96.41%</td>
<td style="text-align: right;">29.58%</td>
<td style="text-align: right;">98.05%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M8_extrapolate</td>
<td style="text-align: right;">77.41%</td>
<td style="text-align: right;">95.60%</td>
<td style="text-align: right;">51.73%</td>
<td style="text-align: right;">65.15%</td>
<td style="text-align: right;">82.55%</td>
<td style="text-align: right;">96.33%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M1_traffic</td>
<td style="text-align: right;">84.90%</td>
<td style="text-align: right;">86.97%</td>
<td style="text-align: right;">83.45%</td>
<td style="text-align: right;">78.24%</td>
<td style="text-align: right;">89.34%</td>
<td style="text-align: right;">90.12%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M6_cascade</td>
<td style="text-align: right;">86.95%</td>
<td style="text-align: right;">84.92%</td>
<td style="text-align: right;">86.86%</td>
<td style="text-align: right;">75.19%</td>
<td style="text-align: right;">89.95%</td>
<td style="text-align: right;">89.52%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M7_abstain</td>
<td style="text-align: right;">74.85%</td>
<td style="text-align: right;">98.24%</td>
<td style="text-align: right;">63.76%</td>
<td style="text-align: right;">95.11%</td>
<td style="text-align: right;">80.05%</td>
<td style="text-align: right;">98.50%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M3_vert_rate</td>
<td style="text-align: right;">66.72%</td>
<td style="text-align: right;">96.90%</td>
<td style="text-align: right;">62.54%</td>
<td style="text-align: right;">95.53%</td>
<td style="text-align: right;">72.65%</td>
<td style="text-align: right;">97.05%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M5_min_alt</td>
<td style="text-align: right;">81.59%</td>
<td style="text-align: right;">78.17%</td>
<td style="text-align: right;">81.30%</td>
<td style="text-align: right;">73.41%</td>
<td style="text-align: right;">85.99%</td>
<td style="text-align: right;">80.88%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M0_current</td>
<td style="text-align: right;">63.59%</td>
<td style="text-align: right;">97.45%</td>
<td style="text-align: right;">61.97%</td>
<td style="text-align: right;">95.55%</td>
<td style="text-align: right;">69.29%</td>
<td style="text-align: right;">97.53%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2025-06</td>
<td style="text-align: left;">M2_on_ground</td>
<td style="text-align: right;">28.87%</td>
<td style="text-align: right;">95.43%</td>
<td style="text-align: right;">33.38%</td>
<td style="text-align: right;">92.74%</td>
<td style="text-align: right;">31.26%</td>
<td style="text-align: right;">96.10%</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="sec-recommendations" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-recommendations"><span class="header-section-number">6</span> Recommendations</h2>
<section id="already-implemented-and-validated-in-this-study" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="already-implemented-and-validated-in-this-study"><span class="header-section-number">6.1</span> Already implemented and validated in this study</h3>
<p>These need no further research. They are in <code>benchmarks/adep_ades.py</code> and are measured above.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Change</th>
<th>Evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treat out-of-area as an answer, not a silence</td>
<td><a href="#sec-ooa" class="quarto-xref">Section&nbsp;1</a></td>
</tr>
<tr class="even">
<td>Prefer a qualifying aerodrome over the border label</td>
<td><a href="#sec-ooa" class="quarto-xref">Section&nbsp;1</a></td>
</tr>
<tr class="odd">
<td>Rank candidates with a scheduled-service penalty (10 NM)</td>
<td><a href="#sec-sched" class="quarto-xref">Section&nbsp;2</a></td>
</tr>
<tr class="even">
<td>Drop only <em>confirmed</em> non-aeroplanes; keep unidentified airframes</td>
<td>V2</td>
</tr>
<tr class="odd">
<td>Restrict candidates to large and medium aerodromes</td>
<td>V2</td>
</tr>
<tr class="even">
<td>Report naming skill and abstention skill separately</td>
<td><a href="#sec-ooa" class="quarto-xref">Section&nbsp;1</a></td>
</tr>
</tbody>
</table>
</section>
<section id="outstanding-in-the-production-pipeline" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="outstanding-in-the-production-pipeline"><span class="header-section-number">6.2</span> Outstanding in the production pipeline</h3>
<p>None of the above has been applied to <code>src/opdi/pipeline/flights.py</code>. The production flight list still uses the altitude-trend vote and still emits a null for both “outside the observed area” and “not determined”. A patch proposal follows so that the change can be reviewed rather than assumed.</p>
</section>
</section>
<section id="sec-patch" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="sec-patch"><span class="header-section-number">7</span> Production patch proposal</h2>
<p>Scope is <code>src/opdi/pipeline/flights.py</code>. <code>tracks.py</code> is untouched, so <code>track_id</code> continuity with every published release is unaffected — this changes the flight list, not track construction.</p>
<p><strong>Replace</strong> <code>_categorize_landing_take_off</code>, which counts the sign of a 5-sample rolling-mean altitude difference and drops anything ambiguous, with the endpoint rule:</p>
<ol type="1">
<li>Take the first and last state vector of the track.</li>
<li>Find the nearest aerodrome by <strong>effective distance</strong> — great-circle distance plus 10 NM for aerodromes without scheduled service — among large and medium aerodromes only.</li>
<li>Emit that aerodrome when the endpoint is within 20 NM of it and no more than 15,000 ft above its elevation, or is flagged <code>on_ground</code>.</li>
<li>Otherwise, if the endpoint lies within 30 NM of the ingestion boundary, emit the out-of-area marker.</li>
<li>Otherwise emit null.</li>
</ol>
<p><strong>Add two columns</strong> to the flight list, <code>adep_source</code> and <code>ades_source</code>, taking <code>aerodrome</code>, <code>out_of_area</code> or <code>undetermined</code>. This is the change with the highest value per line: those three states are currently collapsed into a single null, and they mean entirely different things to a downstream user.</p>
<p><strong>Version.</strong> New <code>version</code> string for the flight list. Existing event types keep theirs, so published v0.0.2 data stays reproducible.</p>
<p><strong>Aerodrome elevation</strong> comes from OurAirports and is missing for 3.09% of large and medium aerodromes. Where it is missing, fall back to the <code>on_ground</code> flag rather than treating the elevation as sea level — at a 5,000 ft aerodrome that error is the entire height threshold.</p>
<p><strong>Before applying, a reviewer should check:</strong> that arrivals are <em>not</em> switched to this rule on the strength of the departure result, since arrivals fail to replicate every time; that the aerodrome reference used in production carries <code>scheduled_service</code>; and that the out-of-area marker is agreed with downstream consumers before it appears in a published column.</p>
</section>
<section id="sec-limitations" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="sec-limitations"><span class="header-section-number">8</span> Limitations</h2>
<ul>
<li><strong>Out-of-area recall is 10–15%.</strong> The geometric border test is the wrong instrument; a phase-based test — first sample already in the cruise, not near or descending toward an aerodrome — should be tried next, and is the single clearest improvement available.</li>
<li><strong>The scheduled-service preference has a cost</strong>, and it is now the largest single class of remaining departure errors: genuine movements at Biggin Hill and Northolt pulled to the nearby hub.</li>
<li><strong>Dense terminal areas are unresolved.</strong> Biggin Hill against London City, Cannes against Nice. Runway-level matching using the HexAero layouts OPDI already computes is the obvious next step and is not used here.</li>
<li><strong>Six days</strong>, two three-day samples a year apart.</li>
<li>Everything carried over from version 2: surface vehicles cannot be excluded by declaration, <code>track_id</code> is taken as given, and cleaning is not applied.</li>
</ul>
</section>
<section id="reproducing" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="reproducing"><span class="header-section-number">9</span> Reproducing</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/adep_ades.py <span class="at">--days</span> 2025-06-05 2025-06-06 2025-06-07 <span class="dt">\</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">--months</span> 202506 <span class="at">--methods</span> all <span class="at">--sweep-abstain</span> <span class="dt">\</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--error-pairs</span> M7_abstain <span class="at">--per-airport</span> M7_abstain <span class="dt">\</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">--diagnose-cascade</span> <span class="at">--control</span> m1 <span class="at">--sched-penalty-nm</span> 15 <span class="dt">\</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">--results-dir</span> <span class="op">&lt;</span>dir<span class="op">&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>--results-dir</code> writes the result tables as CSV to a local directory instead of S3. The bucket has a quota, and a write that exceeds it fails at the very end of a job — after the numbers are computed and printed but before they are stored.</p>
<p>Rendering this page needs no credentials, no database and no cluster.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>