<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="EUROCONTROL Performance Review Unit">
<meta name="dcterms.date" content="2026-08-23">

<title>Detecting departure and destination aerodromes from ADS-B – OPDI Papers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3fc44999f41da3927fa35e4e05887fd4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">OPDI Papers</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.eurocontrol.int/opdi"> 
<span class="menu-text">OPDI</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-this-version-changes" id="toc-what-this-version-changes" class="nav-link active" data-scroll-target="#what-this-version-changes"><span class="header-section-number">1</span> What this version changes</a></li>
  <li><a href="#sec-method" id="toc-sec-method" class="nav-link" data-scroll-target="#sec-method"><span class="header-section-number">2</span> How a flight gets its aerodromes</a>
  <ul class="collapse">
  <li><a href="#the-steps" id="toc-the-steps" class="nav-link" data-scroll-target="#the-steps"><span class="header-section-number">2.1</span> The steps</a></li>
  <li><a href="#trend-arrivals" id="toc-trend-arrivals" class="nav-link" data-scroll-target="#trend-arrivals"><span class="header-section-number">2.2</span> <code>trend</code>, arrivals</a></li>
  <li><a href="#trend-departures" id="toc-trend-departures" class="nav-link" data-scroll-target="#trend-departures"><span class="header-section-number">2.3</span> <code>trend</code>, departures</a></li>
  <li><a href="#endpoint-departures" id="toc-endpoint-departures" class="nav-link" data-scroll-target="#endpoint-departures"><span class="header-section-number">2.4</span> <code>endpoint</code>, departures</a></li>
  <li><a href="#endpoint-arrivals" id="toc-endpoint-arrivals" class="nav-link" data-scroll-target="#endpoint-arrivals"><span class="header-section-number">2.5</span> <code>endpoint</code>, arrivals</a></li>
  <li><a href="#where-the-two-datums-part-company" id="toc-where-the-two-datums-part-company" class="nav-link" data-scroll-target="#where-the-two-datums-part-company"><span class="header-section-number">2.6</span> Where the two datums part company</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#sec-bands" id="toc-sec-bands" class="nav-link" data-scroll-target="#sec-bands"><span class="header-section-number">3.1</span> The band breakdown, read first</a></li>
  <li><a href="#what-it-costs-and-why-that-settles-it" id="toc-what-it-costs-and-why-that-settles-it" class="nav-link" data-scroll-target="#what-it-costs-and-why-that-settles-it"><span class="header-section-number">3.2</span> What it costs, and why that settles it</a></li>
  <li><a href="#the-band-that-should-have-gained-most-and-did-not" id="toc-the-band-that-should-have-gained-most-and-did-not" class="nav-link" data-scroll-target="#the-band-that-should-have-gained-most-and-did-not"><span class="header-section-number">3.3</span> The band that should have gained most, and did not</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Detecting departure and destination aerodromes from ADS-B</h1>
<p class="subtitle lead">Version 6.1 — the altitude cut, and which datum it is measured against</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>EUROCONTROL Performance Review Unit </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="what-this-version-changes" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="what-this-version-changes"><span class="header-section-number">1</span> What this version changes</h2>
<p>Version 6 tuned <code>trend</code>’s altitude cut and left its <em>datum</em> alone. This version changes the datum, and measures what that is worth.</p>
<p><code>trend</code> admitted a state vector to its vote when the aircraft was below a <strong>flight level</strong> — pressure altitude above the standard datum, the same number everywhere. <code>endpoint</code> had never worked that way: since version 6 its height gate has been measured <strong>above the aerodrome’s own field elevation</strong>, on the stated grounds that “a fixed altitude cut-off means nothing at an aerodrome sitting at 5,000 ft”. Step 04’s ground-phase detection moved to the same datum for the same reason.</p>
<p><code>trend</code> was the last of the three still referenced to sea level. That is the asymmetry this version removes.</p>
<p>The consequence is not inaccuracy but <strong>silence</strong>, and it falls unevenly. At FL60 an aerodrome at sea level offers 6,000 ft of climb and descent for the vote to read. Madrid, at 1,998 ft, offers about 4,100. Ankara, at 3,125 ft, about 2,975. The altitude trace has progressively less room to rise or fall <em>clearly</em>, so the method abstains more often — and it abstains in proportion to how high the aerodrome sits.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What this change cannot do
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>trend</code> votes on the <strong>sign</strong> of a smoothed altitude change. Adding a constant offset to every altitude in a track cannot flip a sign, so the field elevation changes only <em>which samples are admitted to vote</em>, never how a vote is cast.</p>
<p>This is therefore a <strong>coverage</strong> result first. Any movement in accuracy is a second-order consequence of answering more flights, not of discriminating better between them. The report is written to keep those apart.</p>
</div>
</div>
</section>
<section id="sec-method" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-method"><span class="header-section-number">2</span> How a flight gets its aerodromes</h2>
<p>Version 6 describes the three methods and the reasoning behind them; this section does not repeat that. What it adds is the part version 6 states only in prose — the <strong>order</strong> the pipeline does things in, and which datum each altitude gate is measured against — because the change this version makes is a change to that order.</p>
<p>Both methods answer two questions per track, separately: which aerodrome the flight departed from (<code>ADEP</code>) and which it arrived at (<code>ADES</code>). The shipped configuration takes departures from <code>endpoint</code> and arrivals from <code>trend</code>.</p>
<section id="the-steps" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="the-steps"><span class="header-section-number">2.1</span> The steps</h3>
<p>Every box in the diagrams below is one of these.</p>
<p><strong>S1 — Read the track.</strong> One aircraft’s state vectors for one flight, already split into a track by step 02 and cleaned by step 02a.</p>
<p><strong>S2 — Smooth the altitude.</strong> A centred five-sample rolling mean over barometric altitude, computed over the <em>whole</em> track before any altitude cut. Smoothing after the cut would truncate the window exactly where altitude is changing fastest, which is the worst place to lose half of it.</p>
<p><strong>S3 — Pre-filter on pressure altitude.</strong> A cheap, deliberately loose cut whose only job is to keep the aerodrome join affordable. Its ceiling is the configured cap <em>plus the highest field elevation in the reference</em>, so it cannot discard a sample that the exact test at S6 would have kept.</p>
<p><strong>S4 — Join the aerodrome zones.</strong> Each sample is matched to candidate aerodromes through an H3 index at resolution 7, then narrowed to those within the detection radius by exact great-circle distance.</p>
<p><strong>S5 — Attach the field elevation.</strong> Each candidate aerodrome’s elevation, from OurAirports. A candidate whose elevation is unknown gets zero, which reduces the next step to the sea-level behaviour rather than dropping the aerodrome.</p>
<p><strong>S6 — Cut on altitude.</strong> <em>This is the step this version changes.</em> Samples above the ceiling are excluded from the vote. <code>trend</code> now measures that ceiling <strong>above field elevation</strong>; before this version it was a flight level.</p>
<p><strong>S7 — Vote.</strong> Each surviving sample votes on the sign of its smoothed altitude change: rising for a departure, falling for an arrival.</p>
<p><strong>S8 — Decide, or abstain.</strong> If one direction leads the other by more than the margin, the track is departing or arriving. Otherwise <code>trend</code> says nothing.</p>
<p><strong>E1 — Take the endpoint fix.</strong> <code>endpoint</code> reads one sample, not many: the track’s first fix for a departure, its last for an arrival.</p>
<p><strong>E2 — Test the gates.</strong> The fix must be within the radius, and either flagged on the ground or no higher than the height gate <strong>above field elevation</strong>.</p>
<p><strong>E3 — Rank the survivors.</strong> Nearest wins, on exact great-circle distance, plus a penalty for aerodromes without scheduled service so that a military or general-aviation field must be <em>clearly</em> nearest rather than merely nearest.</p>
<p><strong>E4 — Or say where it came from.</strong> Where the gates fail and the fix sits at the edge of the observed area, <code>endpoint</code> reports <strong>out-of-area</strong> rather than guessing. Precedence is aerodrome first, border second: Ponta Delgada lies about 8 NM inside the western edge, and the other order labelled its departures out-of-area with the aircraft still on the runway.</p>
</section>
<section id="trend-arrivals" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="trend-arrivals"><span class="header-section-number">2.2</span> <code>trend</code>, arrivals</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-trend-arrival" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trend-arrival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-trend-arrival">flowchart TD
    T[("S1 · track&lt;br/&gt;state vectors")] --&gt; SM["S2 · smooth baro_altitude&lt;br/&gt;&lt;i&gt;centred 5-sample mean&lt;/i&gt;"]
    SM --&gt; PRE["S3 · pre-filter&lt;br/&gt;&lt;i&gt;cap + highest field elevation&lt;/i&gt;"]
    PRE --&gt; J{{"S4 · join H3 aerodrome zones&lt;br/&gt;&lt;i&gt;res 7, then exact distance&lt;/i&gt;"}}
    J --&gt; EL["S5 · attach field elevation&lt;br/&gt;&lt;i&gt;OurAirports; unknown &amp;rarr; 0&lt;/i&gt;"]
    EL --&gt; CUT["&lt;b&gt;S6 · altitude cut&lt;/b&gt;&lt;br/&gt;&lt;b&gt;&lt;i&gt;height above field &amp;le; cap&lt;/i&gt;&lt;/b&gt;"]
    CUT --&gt; V["S7 · vote per sample&lt;br/&gt;&lt;i&gt;sign of smoothed change&lt;/i&gt;"]
    V --&gt; M{"S8 · descending votes&lt;br/&gt;lead by the margin?"}
    M --&gt;|yes| R["E3 · rank survivors&lt;br/&gt;&lt;i&gt;distance + scheduled penalty&lt;/i&gt;"]
    M --&gt;|no| U(["undetermined"])
    R --&gt; A(["ADES = nearest survivor"])
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trend-arrival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <code>trend</code> naming an arrival aerodrome (ADES). S6 is the step this version changes.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="trend-departures" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="trend-departures"><span class="header-section-number">2.3</span> <code>trend</code>, departures</h3>
<p>The same machinery reading the same samples; only the direction of the winning vote differs. <code>trend</code> has <strong>no out-of-area concept</strong> — it names an aerodrome or says nothing — which is why the shipped configuration does not use it for departures.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-trend-departure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trend-departure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-trend-departure">flowchart TD
    T[("S1 · track&lt;br/&gt;state vectors")] --&gt; SM["S2 · smooth baro_altitude&lt;br/&gt;&lt;i&gt;centred 5-sample mean&lt;/i&gt;"]
    SM --&gt; PRE["S3 · pre-filter&lt;br/&gt;&lt;i&gt;cap + highest field elevation&lt;/i&gt;"]
    PRE --&gt; J{{"S4 · join H3 aerodrome zones&lt;br/&gt;&lt;i&gt;res 7, then exact distance&lt;/i&gt;"}}
    J --&gt; EL["S5 · attach field elevation&lt;br/&gt;&lt;i&gt;OurAirports; unknown &amp;rarr; 0&lt;/i&gt;"]
    EL --&gt; CUT["&lt;b&gt;S6 · altitude cut&lt;/b&gt;&lt;br/&gt;&lt;b&gt;&lt;i&gt;height above field &amp;le; cap&lt;/i&gt;&lt;/b&gt;"]
    CUT --&gt; V["S7 · vote per sample&lt;br/&gt;&lt;i&gt;sign of smoothed change&lt;/i&gt;"]
    V --&gt; M{"S8 · climbing votes&lt;br/&gt;lead by the margin?"}
    M --&gt;|yes| R["E3 · rank survivors&lt;br/&gt;&lt;i&gt;distance + scheduled penalty&lt;/i&gt;"]
    M --&gt;|no| U(["undetermined&lt;br/&gt;&lt;i&gt;never out-of-area&lt;/i&gt;"])
    R --&gt; A(["ADEP = nearest survivor"])
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trend-departure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: <code>trend</code> naming a departure aerodrome (ADEP). Identical to the arrival case except at S8.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="endpoint-departures" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="endpoint-departures"><span class="header-section-number">2.4</span> <code>endpoint</code>, departures</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-endpoint-departure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-endpoint-departure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-endpoint-departure">flowchart TD
    T[("S1 · track&lt;br/&gt;state vectors")] --&gt; E1["E1 · take the FIRST fix"]
    E1 --&gt; J{{"S4 · candidate aerodromes&lt;br/&gt;&lt;i&gt;within the radius&lt;/i&gt;"}}
    J --&gt; EL["S5 · attach field elevation&lt;br/&gt;&lt;i&gt;OurAirports&lt;/i&gt;"]
    EL --&gt; G{"E2 · within radius AND&lt;br/&gt;(on ground OR&lt;br/&gt;&lt;b&gt;height above field &amp;le; gate&lt;/b&gt;)?"}
    G --&gt;|yes| R["E3 · rank survivors&lt;br/&gt;&lt;i&gt;distance + scheduled penalty&lt;/i&gt;"]
    G --&gt;|no| B{"E4 · fix at the edge&lt;br/&gt;of the observed area?"}
    R --&gt; A(["ADEP = nearest survivor"])
    B --&gt;|yes| OOA(["out-of-area"])
    B --&gt;|no| U(["undetermined"])
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-endpoint-departure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: <code>endpoint</code> naming a departure aerodrome (ADEP). One fix, two gates, three possible answers.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="endpoint-arrivals" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="endpoint-arrivals"><span class="header-section-number">2.5</span> <code>endpoint</code>, arrivals</h3>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-endpoint-arrival" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-endpoint-arrival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-endpoint-arrival">flowchart TD
    T[("S1 · track&lt;br/&gt;state vectors")] --&gt; E1["E1 · take the LAST fix"]
    E1 --&gt; J{{"S4 · candidate aerodromes&lt;br/&gt;&lt;i&gt;within the radius&lt;/i&gt;"}}
    J --&gt; EL["S5 · attach field elevation&lt;br/&gt;&lt;i&gt;OurAirports&lt;/i&gt;"]
    EL --&gt; G{"E2 · within radius AND&lt;br/&gt;(on ground OR&lt;br/&gt;&lt;b&gt;height above field &amp;le; gate&lt;/b&gt;)?"}
    G --&gt;|yes| R["E3 · rank survivors&lt;br/&gt;&lt;i&gt;distance + scheduled penalty&lt;/i&gt;"]
    G --&gt;|no| B{"E4 · fix at the edge&lt;br/&gt;of the observed area?"}
    R --&gt; A(["ADES = nearest survivor"])
    B --&gt;|yes| OOA(["out-of-area"])
    B --&gt;|no| U(["undetermined"])
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-endpoint-arrival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: <code>endpoint</code> naming an arrival aerodrome (ADES). The last fix rather than the first.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="where-the-two-datums-part-company" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="where-the-two-datums-part-company"><span class="header-section-number">2.6</span> Where the two datums part company</h3>
<p>Only <strong>S6</strong> and <strong>E2</strong> read an altitude, and until this version they read it against different references:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Threshold</th>
<th>Datum, before v6.1</th>
<th>Datum, from v6.1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>trend</code> S6</td>
<td><code>trend_max_height_ft</code></td>
<td>flight level (sea level)</td>
<td><strong>above field elevation</strong></td>
</tr>
<tr class="even">
<td><code>endpoint</code> E2</td>
<td><code>endpoint_height_ft</code></td>
<td>above field elevation</td>
<td>above field elevation</td>
</tr>
<tr class="odd">
<td>step 04 ground phase</td>
<td><code>phase_ground_ceiling_ft</code></td>
<td>above field elevation</td>
<td>above field elevation</td>
</tr>
<tr class="even">
<td><code>nearest</code></td>
<td><em>none</em></td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><code>nearest</code> applies no altitude condition at all, on any datum. That is deliberate: it is the naive <code>traffic</code>-faithful baseline the other methods are scored against, and giving it a gate would defeat its purpose.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>A flight level is not a height
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>FL60</code> is not the same cut as <code>6,000 ft</code>. The pipeline derives the flight level with an integer cast, so <code>flight_level &lt;= 60</code> admits everything below <strong>6,100 ft</strong>. The datum comparison in this report therefore holds the ceiling at 6,100 ft above field, not 6,000 — otherwise it would move the ceiling and the datum at the same time and could not attribute the result to either.</p>
</div>
</div>
</section>
</section>
<section id="results" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="results"><span class="header-section-number">3</span> Results</h2>
<section id="sec-bands" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="sec-bands"><span class="header-section-number">3.1</span> The band breakdown, read first</h3>
<p>This section comes before the headline deliberately. The headline is a single pair of numbers and it is consistent with several explanations; the band breakdown is the only part of this study that can distinguish between them. Read in the other order, it becomes a search for confirmation.</p>
<p>The prediction the design committed to, before any of this was run: <strong>no movement at sea-level aerodromes, and gains concentrated at elevated ones.</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals, 2025 sample. Δ is field minus sea level.</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 3%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Band</th>
<th style="text-align: right;">Aerodromes</th>
<th style="text-align: right;">Truth</th>
<th style="text-align: right;">Correct MSL</th>
<th style="text-align: right;">Correct field</th>
<th style="text-align: right;">Δ</th>
<th style="text-align: right;">Δ less top mover</th>
<th style="text-align: right;">Δ less busiest</th>
<th style="text-align: left;">Δ relative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">&lt;500</td>
<td style="text-align: right;">490</td>
<td style="text-align: right;">66,612</td>
<td style="text-align: right;">49,514</td>
<td style="text-align: right;">49,571</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">57</td>
<td style="text-align: left;">+0.12%</td>
</tr>
<tr class="even">
<td style="text-align: left;">500-1500</td>
<td style="text-align: right;">164</td>
<td style="text-align: right;">15,285</td>
<td style="text-align: right;">12,593</td>
<td style="text-align: right;">12,621</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">28</td>
<td style="text-align: left;">+0.22%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1500-3000</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">4,434</td>
<td style="text-align: right;">1,919</td>
<td style="text-align: right;">2,028</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">110</td>
<td style="text-align: left;">+5.68%</td>
</tr>
<tr class="even">
<td style="text-align: left;">&gt;3000</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">705</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">+0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">unknown</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">8,080</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">+0.00%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>The effect is where it was predicted to be.</strong> Measured against each band’s own base of correct arrivals — which is the honest denominator, since the bands differ in size by two orders of magnitude — the sea-level control band moves by +0.12% and the 1,500–3,000 ft band by <strong>+5.7%</strong>. That is a difference of roughly forty-fold between the band where the datum change is arithmetically a no-op and the band where it bites hardest.</p>
<p>It also survives both robustness checks. The census run before this study began showed each treatment band resting on a single aerodrome, so a band mean alone could not separate an elevation effect from a Madrid effect. Removing the largest mover leaves +70 of the +109; removing Madrid, the busiest field in the band, leaves +110 — very slightly <em>more</em>. The result is not one aerodrome’s result.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The control that had to hold, and did
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Departures move by exactly zero in every band.</strong> The shipped configuration takes departures from <code>endpoint</code>, which never reads <code>trend</code>’s altitude cut — so a non-zero number anywhere in that row would have meant this change was touching something it has no business touching. It is the cheapest available check that the intervention is the one described.</p>
</div>
</div>
</section>
<section id="what-it-costs-and-why-that-settles-it" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="what-it-costs-and-why-that-settles-it"><span class="header-section-number">3.2</span> What it costs, and why that settles it</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals through <code>process_dai</code> itself, 2025 sample.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Run</th>
<th style="text-align: left;">Coverage</th>
<th style="text-align: left;">Accuracy</th>
<th style="text-align: right;">Correct</th>
<th style="text-align: right;">Wrong</th>
<th style="text-align: right;">Score (k=2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">datum_msl</td>
<td style="text-align: left;">68.29%</td>
<td style="text-align: left;">98.58%</td>
<td style="text-align: right;">64,031</td>
<td style="text-align: right;">923</td>
<td style="text-align: right;">62,185</td>
</tr>
<tr class="even">
<td style="text-align: left;">datum_field</td>
<td style="text-align: left;">68.60%</td>
<td style="text-align: left;">98.42%</td>
<td style="text-align: right;">64,225</td>
<td style="text-align: right;">1,028</td>
<td style="text-align: right;">62,169</td>
</tr>
<tr class="odd">
<td style="text-align: left;">legacy</td>
<td style="text-align: left;">66.99%</td>
<td style="text-align: left;">98.19%</td>
<td style="text-align: right;">62,564</td>
<td style="text-align: right;">1,151</td>
<td style="text-align: right;">60,262</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Moving to the field datum buys <strong>194 more correct arrivals and 105 more wrong ones</strong>. Coverage rises 0.31 pp; accuracy falls 0.16 pp; the score at <em>k</em> = 2 moves from 62,185 to 62,169 — sixteen points the wrong way.</p>
<p>The adoption criteria fixed in the design were: coverage up by at least 0.5 pp, accuracy not falling, and the gain concentrated at elevated fields. <strong>The third holds and the first two do not.</strong> So on this evidence the change does not ship, and the honest summary is that the mechanism is real but too small, at this ceiling, to pay for itself.</p>
<p>That the criteria were written down before the numbers existed is what makes this a result rather than a negotiation. A study whose bar moves to meet its outcome has measured nothing.</p>
</section>
<section id="the-band-that-should-have-gained-most-and-did-not" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="the-band-that-should-have-gained-most-and-did-not"><span class="header-section-number">3.3</span> The band that should have gained most, and did not</h3>
<p>The <code>&gt;3000</code> band is the one where a fixed sea-level ceiling ought to hurt worst, and it shows <strong>no change at all: 5 correct arrivals out of 705, on both datums.</strong></p>
<p>That is not a null result about the datum. It is <code>trend</code> failing at those aerodromes for a different reason — a recall of 0.7% is not a method being mis-tuned, it is a method receiving almost nothing to work with. The likeliest cause is ADS-B coverage over the Anatolian plateau, where most of this band’s traffic sits; an aerodrome the feed barely sees cannot be named on any datum.</p>
<p>This matters for how the change should be argued elsewhere. The motivating example in the design was Erzurum at 5,763 ft, where a FL60 cut leaves about 240 ft in which to vote. That example is arithmetically correct and doubly unrepresentative: such fields are rare in the sample, <strong>and</strong> they sit in the one band where the method is independently broken. The population that actually benefits is the far less dramatic 1,500–3,000 ft — Madrid, Ankara, Sofia, Tbilisi — where a FL60 cut still leaves three to four thousand feet of usable climb and descent.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>