<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="EUROCONTROL Performance Review Unit">
<meta name="dcterms.date" content="2026-08-12">

<title>Reply to the review of version 6 – OPDI Papers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3fc44999f41da3927fa35e4e05887fd4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">OPDI Papers</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.eurocontrol.int/opdi"> 
<span class="menu-text">OPDI</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#general-remarks" id="toc-general-remarks" class="nav-link active" data-scroll-target="#general-remarks"><span class="header-section-number">1</span> General remarks</a>
  <ul class="collapse">
  <li><a href="#cut-the-wrong-turns-and-the-bugfixes" id="toc-cut-the-wrong-turns-and-the-bugfixes" class="nav-link" data-scroll-target="#cut-the-wrong-turns-and-the-bugfixes"><span class="header-section-number">1.1</span> 1. Cut the wrong turns and the bugfixes</a></li>
  <li><a href="#define-the-terms-and-gloss-the-table-headers" id="toc-define-the-terms-and-gloss-the-table-headers" class="nav-link" data-scroll-target="#define-the-terms-and-gloss-the-table-headers"><span class="header-section-number">1.2</span> 2. Define the terms, and gloss the table headers</a></li>
  <li><a href="#production-and-legacy-used-interchangeably" id="toc-production-and-legacy-used-interchangeably" class="nav-link" data-scroll-target="#production-and-legacy-used-interchangeably"><span class="header-section-number">1.3</span> 3. “Production” and “legacy” used interchangeably</a></li>
  </ul></li>
  <li><a href="#comments-on-the-summary" id="toc-comments-on-the-summary" class="nav-link" data-scroll-target="#comments-on-the-summary"><span class="header-section-number">2</span> Comments on the summary</a></li>
  <li><a href="#how-the-metrics-work" id="toc-how-the-metrics-work" class="nav-link" data-scroll-target="#how-the-metrics-work"><span class="header-section-number">3</span> 1. How the metrics work</a></li>
  <li><a href="#the-three-methods" id="toc-the-three-methods" class="nav-link" data-scroll-target="#the-three-methods"><span class="header-section-number">4</span> 3. The three methods</a></li>
  <li><a href="#trend-the-full-parameter-sweep" id="toc-trend-the-full-parameter-sweep" class="nav-link" data-scroll-target="#trend-the-full-parameter-sweep"><span class="header-section-number">5</span> 4. Trend: the full parameter sweep</a></li>
  <li><a href="#negative-results" id="toc-negative-results" class="nav-link" data-scroll-target="#negative-results"><span class="header-section-number">6</span> 8. Negative results</a>
  <ul class="collapse">
  <li><a href="#bearing-applied-to-trend" id="toc-bearing-applied-to-trend" class="nav-link" data-scroll-target="#bearing-applied-to-trend"><span class="header-section-number">6.1</span> 8.3 Bearing applied to <code>trend</code></a></li>
  <li><a href="#the-sampler" id="toc-the-sampler" class="nav-link" data-scroll-target="#the-sampler"><span class="header-section-number">6.2</span> 8.5 The sampler</a></li>
  </ul></li>
  <li><a href="#what-the-pipeline-actually-produces" id="toc-what-the-pipeline-actually-produces" class="nav-link" data-scroll-target="#what-the-pipeline-actually-produces"><span class="header-section-number">7</span> 9. What the pipeline actually produces</a>
  <ul class="collapse">
  <li><a href="#what-running-the-pipeline-caught" id="toc-what-running-the-pipeline-caught" class="nav-link" data-scroll-target="#what-running-the-pipeline-caught"><span class="header-section-number">7.1</span> 9.1 What running the pipeline caught</a></li>
  <li><a href="#the-trend-tuning-re-walked-inside-the-pipeline" id="toc-the-trend-tuning-re-walked-inside-the-pipeline" class="nav-link" data-scroll-target="#the-trend-tuning-re-walked-inside-the-pipeline"><span class="header-section-number">7.2</span> 9.2 The trend tuning re-walked inside the pipeline</a></li>
  <li><a href="#productions-own-optimum" id="toc-productions-own-optimum" class="nav-link" data-scroll-target="#productions-own-optimum"><span class="header-section-number">7.3</span> 9.3 Production’s own optimum</a></li>
  </ul></li>
  <li><a href="#and-11-the-tables-that-do-not-explain-themselves" id="toc-and-11-the-tables-that-do-not-explain-themselves" class="nav-link" data-scroll-target="#and-11-the-tables-that-do-not-explain-themselves"><span class="header-section-number">8</span> 10.1 and 11 — the tables that do not explain themselves</a></li>
  <li><a href="#what-is-being-recommended-and-why" id="toc-what-is-being-recommended-and-why" class="nav-link" data-scroll-target="#what-is-being-recommended-and-why"><span class="header-section-number">9</span> 11.1 What is being recommended, and why</a></li>
  <li><a href="#the-busiest-100-aerodromes" id="toc-the-busiest-100-aerodromes" class="nav-link" data-scroll-target="#the-busiest-100-aerodromes"><span class="header-section-number">10</span> 13. The busiest 100 aerodromes</a></li>
  <li><a href="#does-any-of-it-hold-on-a-second-period" id="toc-does-any-of-it-hold-on-a-second-period" class="nav-link" data-scroll-target="#does-any-of-it-hold-on-a-second-period"><span class="header-section-number">11</span> 14. Does any of it hold on a second period?</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">12</span> 17. Limitations</a></li>
  <li><a href="#what-happens-to-each-point" id="toc-what-happens-to-each-point" class="nav-link" data-scroll-target="#what-happens-to-each-point"><span class="header-section-number">13</span> What happens to each point</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="reply.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Reply to the review of version 6</h1>
<p class="subtitle lead">Every point answered, with the numbers behind the answer</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>EUROCONTROL Performance Review Unit </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>What this page is, and what it is not
</div>
</div>
<div class="callout-body-container callout-body">
<p>This answers the review of <strong>version 6</strong> point by point, in the review’s own order. Every number on it comes from the committed CSVs under <code>data/</code> — the same files version 6 was rendered from — so it answers the numbers that were actually reviewed.</p>
<p>Several points asked for measurements that did not exist. Those are being run now and land in <strong>version 7</strong>, the report written for the people who will use the flight list rather than for the people building it. Where that is the case this page says so explicitly rather than estimating.</p>
<p>Two decisions follow from the review and change everything downstream: step 02a (trajectory cleaning) is being wired into the flight-list path, and every parameter will be chosen on both periods jointly rather than on 2025 alone. Both mean version 7’s figures will differ from the ones quoted here. That is the point of the exercise, not a defect in it.</p>
</div>
</div>
<section id="general-remarks" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="general-remarks"><span class="header-section-number">1</span> General remarks</h2>
<section id="cut-the-wrong-turns-and-the-bugfixes" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="cut-the-wrong-turns-and-the-bugfixes"><span class="header-section-number">1.1</span> 1. Cut the wrong turns and the bugfixes</h3>
<p>Agreed, and version 7 has none of them. The whole apparatus — “what running the pipeline caught”, “two earlier accounts of this were wrong”, the ring-ranked path kept beside the exact-ranked one — exists because version 6 was written as a working record, for a reader who needed to know which of its own numbers to distrust. That is the wrong document for an external audience.</p>
<p>Version 7 shows the algorithm that ships, the evidence for each value in it, and the limits of that evidence. Where a rejected alternative is worth a reader’s time it appears as a result about the alternative, not as a story about how it was discovered.</p>
<p>I have removed the same material from version 6 in place, so the two do not contradict each other while both are reachable.</p>
</section>
<section id="define-the-terms-and-gloss-the-table-headers" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="define-the-terms-and-gloss-the-table-headers"><span class="header-section-number">1.2</span> 2. Define the terms, and gloss the table headers</h3>
<p>Agreed, and this is the single biggest change in version 7. Every measure gets a definition on first use — coverage, accuracy, score, <span class="math inline">\(k\)</span>, cell, recall, count ratio, out-of-area — and every table gets a line saying what its columns mean. The specific cases the review names (recall, cells, median score, the mode columns) are answered individually below and each becomes a definition rather than a reply.</p>
</section>
<section id="production-and-legacy-used-interchangeably" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="production-and-legacy-used-interchangeably"><span class="header-section-number">1.3</span> 3. “Production” and “legacy” used interchangeably</h3>
<p>Correct, and they are the same thing. Version 6 drifts between them; version 7 uses exactly three words:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>legacy</strong></td>
<td>The algorithm and constants that produced every OPDI flight list published before 2026 — <code>trend</code> for both roles, FL40, 30 NM, vote margin 4, no scheduled-service penalty, H3 ring ranking. Reachable in code as <code>DetectionConfig.legacy()</code>.</td>
</tr>
<tr class="even">
<td><strong>shipped</strong></td>
<td>What this study recommends and what <code>DetectionConfig()</code> now returns.</td>
</tr>
<tr class="odd">
<td><strong>production</strong></td>
<td>The system as it runs, at whatever version is deployed. Used only to talk about deployment, never as a name for an algorithm.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="comments-on-the-summary" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="comments-on-the-summary"><span class="header-section-number">2</span> Comments on the summary</h2>
<blockquote class="blockquote">
<p>You mention a mistake was made. It is however relevant that a more efficient algorithm was developed.</p>
</blockquote>
<p>Agreed on both halves. The summary’s job is to say what the algorithm does and how well, and the substantive finding is not that something was miscounted — it is that <strong>candidate aerodromes are now chosen by exact distance rather than by an H3 ring index</strong>, and that this is what makes tuning possible at all.</p>
<p>The size of that change, from the committed pipeline runs:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 31%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Step</th>
<th style="text-align: right;">Ring ranking, ADES score</th>
<th style="text-align: right;">Exact ranking, ADES score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">legacy constants</td>
<td style="text-align: right;">60,603</td>
<td style="text-align: right;">60,255</td>
</tr>
<tr class="even">
<td style="text-align: right;">+ scheduled-service penalty</td>
<td style="text-align: right;">60,855</td>
<td style="text-align: right;">61,113</td>
</tr>
<tr class="odd">
<td style="text-align: right;">+ flight-level cap FL60</td>
<td style="text-align: right;">59,136</td>
<td style="text-align: right;">61,773</td>
</tr>
<tr class="even">
<td style="text-align: right;">+ vote margin 2</td>
<td style="text-align: right;">59,295</td>
<td style="text-align: right;">61,941</td>
</tr>
<tr class="odd">
<td style="text-align: right;">+ radius 20 NM</td>
<td style="text-align: right;">59,454</td>
<td style="text-align: right;">62,004</td>
</tr>
</tbody>
</table>
<p>The same four parameter changes, applied to the same data in the same order, are worth −1,149 under ring ranking and +1,749 under exact ranking. Every tuned value is the same in both columns; only the rule for choosing among candidate aerodromes differs.</p>
<p>That is the summary version 7 opens with.</p>
</section>
<section id="how-the-metrics-work" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="how-the-metrics-work"><span class="header-section-number">3</span> 1. How the metrics work</h2>
<blockquote class="blockquote">
<p>It’s not clear that in table 1 you suddenly introduce recall for out-of-area only, and then later reuse the term without reintroducing it.</p>
</blockquote>
<p>Correct, and it is two different measures sharing one word.</p>
<ul>
<li><strong>Out-of-area recall</strong> (§1): of the flights whose true origin or destination lies outside the observed area, the share the method labels as such.</li>
<li><strong>Per-aerodrome recall</strong> (§13): of the flights that truly departed from or arrived at a given aerodrome, the share the method attributes to that aerodrome.</li>
</ul>
<p>Version 7 names them separately — <em>out-of-area recall</em> and <em>per-aerodrome recall</em> — and defines each where it first appears. Neither is ever called just “recall”.</p>
</section>
<section id="the-three-methods" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-three-methods"><span class="header-section-number">4</span> 3. The three methods</h2>
<blockquote class="blockquote">
<p>In 3.3 you apply a scheduled-service penalty tie-break. Does it not make sense to also apply this in <code>trend</code>? Later in the paper it does seem you do. Is this correct?</p>
</blockquote>
<p><strong>Yes — it is applied to <code>trend</code>, and it ships.</strong> <code>trend_sched_penalty_nm</code> is 10 NM by default and reaches <code>trend</code>’s ranking in <code>FlightListProcessor._compute_flight_table</code>. The review has found a real documentation defect: §3.3 introduces the penalty as though it belonged to <code>endpoint</code> alone, and §9.2 then uses it on <code>trend</code> without ever saying it was extended there.</p>
<p>What it does, in one sentence: an aerodrome without scheduled service has 10 NM added to its effective distance, so a military or general-aviation field must be <em>clearly</em> nearest rather than merely nearest. It re-ranks candidates without changing how many flights are answered, so coverage cannot move and only accuracy can.</p>
<p>Measured through the pipeline, as the first step of the path above:</p>
<p>Adding it to <code>trend</code> moves arrivals from 60,255 to 61,113 (+858), and departures from 62,539 to 63,391 (+852). Arrival coverage is 68.06% before and 68.06% after — unchanged, as the mechanism requires.</p>
<p>In version 7 the penalty is introduced once, as a property both methods share, before either is described.</p>
</section>
<section id="trend-the-full-parameter-sweep" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="trend-the-full-parameter-sweep"><span class="header-section-number">5</span> 4. Trend: the full parameter sweep</h2>
<blockquote class="blockquote">
<p>You should apply any parameter sweep, in the harness and in production, on <strong>both</strong> time periods, and select what works for both.</p>
</blockquote>
<p>Accepted in full, and it changes the recommendation procedure rather than just the presentation. Version 7 ranks every parameter cell by the two periods combined — scores normalised per period so the larger sample cannot dominate — and reports the single-period argmax only as a stability check.</p>
<p>The good news is that the existing data already supports this for <code>trend</code>, because both periods were swept on the identical grid. Ranking all 360 cells jointly:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Role</th>
<th style="text-align: right;">Rank</th>
<th style="text-align: right;">Cell</th>
<th style="text-align: right;">2025 score</th>
<th style="text-align: right;">2024 score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">ADEP</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">FL120 / margin 0 / 20 NM</td>
<td style="text-align: right;">70,527</td>
<td style="text-align: right;">59,589</td>
</tr>
<tr class="even">
<td style="text-align: right;">ADEP</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">FL120 / margin 2 / 20 NM</td>
<td style="text-align: right;">70,432</td>
<td style="text-align: right;">59,487</td>
</tr>
<tr class="odd">
<td style="text-align: right;">ADEP</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">FL100 / margin 0 / 20 NM</td>
<td style="text-align: right;">70,241</td>
<td style="text-align: right;">59,659</td>
</tr>
<tr class="even">
<td style="text-align: right;">ADES</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">FL60 / margin 2 / 30 NM</td>
<td style="text-align: right;">61,057</td>
<td style="text-align: right;">52,812</td>
</tr>
<tr class="odd">
<td style="text-align: right;">ADES</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">FL60 / margin 0 / 30 NM</td>
<td style="text-align: right;">60,952</td>
<td style="text-align: right;">52,825</td>
</tr>
<tr class="even">
<td style="text-align: right;">ADES</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">FL60 / margin 2 / 20 NM</td>
<td style="text-align: right;">61,069</td>
<td style="text-align: right;">52,668</td>
</tr>
</tbody>
</table>
<p>The arrival configuration version 6 ships — FL60, vote margin 2, 20 NM — ranks <strong>3 of 360</strong> on the joint objective. The joint winner differs from it in one parameter only, the radius (30 NM rather than 20 NM), and by 0.00143 of normalised score. So the arrival tuning does hold on both periods; version 6 simply never asked the question that way.</p>
<p>For <code>endpoint</code>, which is what departures actually ship, the two periods agree outright:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Role</th>
<th style="text-align: right;">2025 argmax</th>
<th style="text-align: right;">2024 argmax</th>
<th style="text-align: right;">Agrees</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">ADEP</td>
<td style="text-align: right;">30 NM / 15,000 ft</td>
<td style="text-align: right;">30 NM / 15,000 ft</td>
<td style="text-align: right;"><strong>yes</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">ADES</td>
<td style="text-align: right;">30 NM / 10,000 ft</td>
<td style="text-align: right;">30 NM / 10,000 ft</td>
<td style="text-align: right;"><strong>yes</strong></td>
</tr>
</tbody>
</table>
<p>The departure optimum — the one that ships — is the <em>same cell</em> on two independent periods, out of 126. That is the strongest stability evidence in the study and version 6 buries it in a subsection near the end.</p>
<blockquote class="blockquote">
<p>You should introduce that there is a harness sweep and later a production run. The transition is abrupt. Also say which data this is applied to.</p>
</blockquote>
<p>Agreed on all three. Version 7 introduces both stages before either is used:</p>
<p><strong>Stage 1 — the research sweep.</strong> Hundreds of parameter combinations applied to a cached intermediate table (vote counts per track-aerodrome pair, or endpoint candidates). Cheap enough to be exhaustive, but it is a re-implementation of the decision rule, not the pipeline itself, so it can only <em>propose</em> values.</p>
<p><strong>Stage 2 — the production run.</strong> The candidate values run through <code>FlightListProcessor.process_dai</code>, the same code path that writes the published flight list, and scored identically. Nothing becomes a default without passing this stage.</p>
<p>And the sample gets its own section up front rather than a passing mention: three days, <strong>5–7 June 2025</strong>, with <strong>5–7 June 2024</strong> as the independent second period; European bounding box; state vectors decimated to 5 s; ground truth from EUROCONTROL Network Manager movement data.</p>
</section>
<section id="negative-results" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="negative-results"><span class="header-section-number">6</span> 8. Negative results</h2>
<blockquote class="blockquote">
<p>To a random reader this section is not properly introduced.</p>
</blockquote>
<p>Agreed. In version 6 it is a list of things that did not work, which is a developer’s category. Version 7 reframes it as <strong>what else was tried, and what each attempt establishes about the problem</strong> — because the failures are informative in a way the review’s own comments show: bearing cannot <em>name</em> an aerodrome, which is precisely why it works as a tie-break and not as a ranking.</p>
<section id="bearing-applied-to-trend" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="bearing-applied-to-trend"><span class="header-section-number">6.1</span> 8.3 Bearing applied to <code>trend</code></h3>
<blockquote class="blockquote">
<p>What do you mean with “within 2 NM”? Also, if it is such a big improvement, why do we not apply this in production?</p>
</blockquote>
<p><strong>What it means.</strong> Every candidate aerodrome has an exact distance from the track’s closest approach. Sort them. If the runner-up is within 2 NM of the winner, the two are effectively equidistant and distance cannot separate them — so the tie is broken by <em>alignment</em>: which aerodrome the aircraft’s course actually points at. Outside that band, distance decides alone and bearing is never consulted.</p>
<p>The band is the whole mechanism, and the full sweep shows why:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Variant</th>
<th style="text-align: right;">Arrival coverage</th>
<th style="text-align: right;">Arrival accuracy</th>
<th style="text-align: right;">Correct</th>
<th style="text-align: right;">Wrong</th>
<th style="text-align: right;">Score</th>
<th style="text-align: right;">vs shipped</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">base: trend as shipped</td>
<td style="text-align: right;">69.76%</td>
<td style="text-align: right;">97.33%</td>
<td style="text-align: right;">64,583</td>
<td style="text-align: right;">1,769</td>
<td style="text-align: right;">61,045</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: right;">rerank by alignment</td>
<td style="text-align: right;">69.76%</td>
<td style="text-align: right;">69.07%</td>
<td style="text-align: right;">45,830</td>
<td style="text-align: right;">20,522</td>
<td style="text-align: right;">4,786</td>
<td style="text-align: right;">−56,259</td>
</tr>
<tr class="odd">
<td style="text-align: right;">tie-break by alignment within 0.5 NM</td>
<td style="text-align: right;">69.76%</td>
<td style="text-align: right;">97.57%</td>
<td style="text-align: right;">64,738</td>
<td style="text-align: right;">1,614</td>
<td style="text-align: right;">61,510</td>
<td style="text-align: right;">+465</td>
</tr>
<tr class="even">
<td style="text-align: right;">tie-break by alignment within 1 NM</td>
<td style="text-align: right;">69.76%</td>
<td style="text-align: right;">97.75%</td>
<td style="text-align: right;">64,857</td>
<td style="text-align: right;">1,495</td>
<td style="text-align: right;">61,867</td>
<td style="text-align: right;">+822</td>
</tr>
<tr class="odd">
<td style="text-align: right;">tie-break by alignment within 2 NM</td>
<td style="text-align: right;">69.76%</td>
<td style="text-align: right;">97.91%</td>
<td style="text-align: right;">64,963</td>
<td style="text-align: right;">1,389</td>
<td style="text-align: right;">62,185</td>
<td style="text-align: right;">+1,140</td>
</tr>
<tr class="even">
<td style="text-align: right;">tie-break by alignment within 5 NM</td>
<td style="text-align: right;">69.76%</td>
<td style="text-align: right;">95.77%</td>
<td style="text-align: right;">63,542</td>
<td style="text-align: right;">2,810</td>
<td style="text-align: right;">57,922</td>
<td style="text-align: right;">−3,123</td>
</tr>
</tbody>
</table>
<p>Column gloss: <em>coverage</em> is the share of reference flights given any answer; <em>accuracy</em> is the share of answers that are right; <em>score</em> is correct − 2 × wrong.</p>
<p>Widen the band to 5 NM and it turns negative (−3,123); drop the band entirely and rank by alignment alone and it collapses (−56,259). The reason is that every aerodrome on the same radial behind the right one is equally well aligned, so alignment carries no information about <em>which</em> — only about which of two nearly-equidistant candidates. The 2 NM band is an interior optimum, not a fitted edge.</p>
<p>At 2 NM: coverage is unchanged at 69.76% — the same flights are answered — while 380 answers move from wrong to right, accuracy rises +0.57 pp and score rises +1,140.</p>
<p><strong>Why it was not in production.</strong> Two reasons, one good and one no longer valid. The good one: unlike every other change in version 6 it is a new algorithmic component rather than a parameter — the flight-list path does not currently compute a track course — and it had been measured on one period, in the research harness, never through <code>process_dai</code>. Shipping it overnight on that basis would have broken the study’s own rule that nothing becomes a default until stage 2 confirms it.</p>
<p>The no-longer-valid reason is simply that version 6 was closing. <strong>It is now being implemented</strong> in <code>_compute_flight_table</code> behind a <code>trend_bearing_tiebreak_nm</code> threshold, and measured through the pipeline on both periods. Version 7 reports that result and adopts it if it survives.</p>
</section>
<section id="the-sampler" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="the-sampler"><span class="header-section-number">6.2</span> 8.5 The sampler</h3>
<blockquote class="blockquote">
<p>This should not be under negative results. It will improve things down the line — for example extracting on-ground events such as in-blocks and take-off, where we will have more state vectors.</p>
</blockquote>
<p>Agreed, and the reasoning is right. The sampler is neutral <em>for this problem</em> — ADEP/ADES detection depends on the altitude trend over tens of samples, so one extra fix per five-second bin changes nothing. It is not neutral for milestones defined by a single instant on the ground, where recovering a bin that the fixed-phase rule dropped is the difference between having a fix and not.</p>
<p>In version 7 it moves out of negative results and into the pipeline description, as a property of the data everything else is built on.</p>
<blockquote class="blockquote">
<p>In the table you mention “Cells” but this is never introduced. Also I would like to see improvement on the selected parameters, not just median score.</p>
</blockquote>
<p>Both fair, and both fixed.</p>
<p><strong>Cell</strong> = one parameter combination. The trend sweep has 371 (9 flight-level caps × 5 vote margins × 8 radii, plus reference rows); the endpoint grid has 126 (radius × height). Comparing two samplers across every cell rather than at one operating point is what makes the comparison hard to fool — a difference that appears at one setting and nowhere else is not a sampler effect.</p>
<p><strong>Median of what</strong>: for each cell, the score under the new sampler minus the score under the old one. The median is over cells.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Comparison</th>
<th style="text-align: right;">Role</th>
<th style="text-align: right;">Cells</th>
<th style="text-align: right;">Median Δ score</th>
<th style="text-align: right;">Cells improved</th>
<th style="text-align: right;">Cells worsened</th>
<th style="text-align: right;">Median Δ coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">trend sweep</td>
<td style="text-align: right;">ADEP</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">+6</td>
<td style="text-align: right;">231</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">+0.0021 pp</td>
</tr>
<tr class="even">
<td style="text-align: right;">trend sweep</td>
<td style="text-align: right;">ADES</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">+17</td>
<td style="text-align: right;">310</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">+0.0042 pp</td>
</tr>
<tr class="odd">
<td style="text-align: right;">endpoint grid</td>
<td style="text-align: right;">ADEP</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">−6</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">+0.0011 pp</td>
</tr>
<tr class="even">
<td style="text-align: right;">endpoint grid</td>
<td style="text-align: right;">ADES</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">−12</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">-0.0137 pp</td>
</tr>
<tr class="odd">
<td style="text-align: right;">pipeline modes</td>
<td style="text-align: right;">ADEP</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">−10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">+0.0000 pp</td>
</tr>
<tr class="even">
<td style="text-align: right;">pipeline modes</td>
<td style="text-align: right;">ADES</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">+16</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">+0.0026 pp</td>
</tr>
</tbody>
</table>
<p>Column gloss: a <strong>cell</strong> is one parameter combination; <strong>Δ</strong> is the bin-based sampler minus the fixed-phase one; <strong>pp</strong> is percentage points of the flights in the reference.</p>
<p>And the second view you asked for — not a median over cells, but the two samplers at the parameters that actually ship:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 23%">
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Configuration</th>
<th style="text-align: right;">Role</th>
<th style="text-align: right;">Fixed-phase score</th>
<th style="text-align: right;">Bin-based score</th>
<th style="text-align: right;">Δ score</th>
<th style="text-align: right;">Δ coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">legacy</td>
<td style="text-align: right;">Departures</td>
<td style="text-align: right;">63,049</td>
<td style="text-align: right;">63,064</td>
<td style="text-align: right;">+15</td>
<td style="text-align: right;">+0.00 pp</td>
</tr>
<tr class="even">
<td style="text-align: right;">legacy</td>
<td style="text-align: right;">Arrivals</td>
<td style="text-align: right;">60,610</td>
<td style="text-align: right;">60,600</td>
<td style="text-align: right;">−10</td>
<td style="text-align: right;">-0.00 pp</td>
</tr>
<tr class="odd">
<td style="text-align: right;">shipped</td>
<td style="text-align: right;">Departures</td>
<td style="text-align: right;">72,855</td>
<td style="text-align: right;">72,837</td>
<td style="text-align: right;">−18</td>
<td style="text-align: right;">+0.00 pp</td>
</tr>
<tr class="even">
<td style="text-align: right;">shipped</td>
<td style="text-align: right;">Arrivals</td>
<td style="text-align: right;">60,952</td>
<td style="text-align: right;">60,944</td>
<td style="text-align: right;">−8</td>
<td style="text-align: right;">+0.01 pp</td>
</tr>
</tbody>
</table>
<p>Both are complete pipeline runs over the same three days, differing only in the sampler.</p>
<p>The largest coverage difference anywhere — median over cells or at the shipped point — is a few thousandths of a percentage point, against a decision bar of 0.5 pp.&nbsp;The bin-based rule is adopted because it is the <strong>correct</strong> rule and does not depend on the OpenSky archive carrying positions forward between messages, not because it improves ADEP/ADES detection, which it does not measurably do. Where it should matter is on-ground milestones, exactly as you say, and that is a measurement neither version has made.</p>
</section>
</section>
<section id="what-the-pipeline-actually-produces" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="what-the-pipeline-actually-produces"><span class="header-section-number">7</span> 9. What the pipeline actually produces</h2>
<blockquote class="blockquote">
<p>This introduction is too late. And the three points are things that went wrong — we want our research implemented in production, not the legacy methods. We wanted haversine. We want to keep the smoothed barometric altitude across the flight-level boundary.</p>
</blockquote>
<p>Taken point by point, because the three items have three different statuses.</p>
<p><strong>Ranking by H3 ring count — already gone.</strong> This is the most important correction in the reply. The pipeline no longer keeps only the candidates at the minimum ring count. Under <code>trend_rank_by = "haversine"</code>, which is the shipped default, every aerodrome whose zone the aircraft passed through is carried forward and ranked on exact great-circle distance. Nothing is eliminated before it is measured. §9 describes the old behaviour in the present tense, which is a stale paragraph, not a description of what runs.</p>
<p><strong>Smoothing across the flight-level boundary — a real remaining gap, and being fixed.</strong> The pipeline applies the flight-level cut <em>before</em> the rolling mean, so the smoothing window is truncated at the boundary; the harness smooths first. You are right that the smoothed value should be kept across the boundary. The cut is being moved after the smoothing window and re-measured through <code>process_dai</code> for version 7.</p>
<p><strong>Radius as a ring band rather than exact distance — the same, and also being fixed.</strong> The pipeline selects zones whose band radius is within the detection radius; the harness cuts on exact distance. Consistent with the ranking change, version 7 cuts on exact distance.</p>
<blockquote class="blockquote">
<p>The OPDI pipeline has ingestion, state-vector processing, filters — which is never explained here. I do hope it is applied in your production pipeline test? Please confirm if not.</p>
</blockquote>
<p><strong>Partly, and the gap is worth stating plainly.</strong> The version 6 pipeline runs executed OPDI’s own step 01 (state-vector ingestion from the OpenSky archive: bounding box, column selection, 5 s decimation) and step 02 (track splitting, H3 indexing, altitude cleaning), and then step 03 for the flight list. Those are the real pipeline modules, not harness re-implementations.</p>
<p><strong>Step 02a — trajectory cleaning — was not applied, and could not have been: the flight list has never read its output.</strong> <code>cleaning/cleaner.py</code> writes a table called <code>osn_tracks_clean</code>, and <code>pipeline/flights.py</code> reads <code>osn_tracks</code>. The cleaning step exists, is tested, and feeds nothing. That is a genuine finding from your review and not something version 6 knew.</p>
<p>It is being wired in for version 7, with the expectation stated in advance that it may <em>cost</em> coverage: cleaning masks implausible values to NULL, and the flight-list path drops samples with no barometric altitude, so every masked altitude is a candidate sample removed. Whether the accuracy gained is worth the coverage lost is exactly the measurement that has been missing.</p>
<blockquote class="blockquote">
<p>We should include the steps that are done in the pipeline, maybe you can produce a flow chart with step by step descriptions.</p>
</blockquote>
<p>Agreed — version 7 has a dedicated section documenting the pipeline that produces the flight list: a flow chart of steps 00 through 05, each box naming its module and the table it writes, then each step in prose with what enters, what leaves, and which decisions are frozen against which are tuned. This is the section the report was missing for its actual audience.</p>
<blockquote class="blockquote">
<p>I hope this cached candidate table is now produced by the pipeline?</p>
</blockquote>
<p><strong>Yes.</strong> The endpoint candidate table is built by <code>FlightListProcessor.build_endpoint_candidates</code>, the pipeline’s own method, invoked from the regeneration chain as an explicit stage rather than assumed to exist. It is not a remnant. It caches the first and last fix of each track against every aerodrome within 110 NM — wider than any detection radius so the radius stays sweepable without a rebuild — and both the sweep and the pipeline filter that same table, which is why they agree to the flight.</p>
<blockquote class="blockquote">
<p>“The pipeline first keeps only the candidates at the minimum H3 ring count.” Why filter on minimum ring count? Just match the full H3 disk and then calculate haversine to tie-break. Isn’t that what the harness does?</p>
</blockquote>
<p>That is exactly right, it is exactly what the harness does, and <strong>it is what the pipeline now does</strong>. The sentence you quote describes the behaviour that was replaced. Concretely, the shipped path is:</p>
<ol type="1">
<li>join state-vector samples to the H3 airport detection zones — the full disk out to the detection radius;</li>
<li>compute exact great-circle distance from every sample to every candidate aerodrome;</li>
<li>take each candidate’s own closest approach — no candidate is dropped here;</li>
<li>rank on that distance, plus the scheduled-service penalty.</li>
</ol>
<p>Version 6’s own numbers for the difference are in the first table on this page: the same tuning is worth −1,149 under ring ranking and +1,749 under exact ranking.</p>
<section id="what-running-the-pipeline-caught" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="what-running-the-pipeline-caught"><span class="header-section-number">7.1</span> 9.1 What running the pipeline caught</h3>
<blockquote class="blockquote">
<p>Only show numbers where all bugs are fixed. No need to discuss the bugs.</p>
</blockquote>
<p>Agreed without reservation. All figures in version 6 are post-fix, but the section describing how the defect was found does not belong in a published paper, and it is gone. Version 7 has no equivalent.</p>
<p>While checking this I found a related defect the review implies but does not name: the verdict section calls the <code>recommended</code> row “a mislabelled control that kept ring ranking and scored below production”. That was true of an earlier build and is <strong>not true of the committed data</strong> — <code>recommended</code> and <code>combined</code> are field-for-field identical (72,837 and 60,944). The prose contradicted its own table. Removed.</p>
</section>
<section id="the-trend-tuning-re-walked-inside-the-pipeline" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="the-trend-tuning-re-walked-inside-the-pipeline"><span class="header-section-number">7.2</span> 9.2 The trend tuning re-walked inside the pipeline</h3>
<blockquote class="blockquote">
<p>Is exact-distance ranking still using a minimum H3 ring count, or the full disk?</p>
</blockquote>
<p>The full disk, then exact haversine. Answered above; the pipeline eliminates nothing on ring count.</p>
<blockquote class="blockquote">
<p>In the table you add coverage and accuracy, but for which mode?</p>
</blockquote>
<p>A fair catch — the table gives one coverage and one accuracy per row without saying which method produced them. Each row of that path is a full flight list with <strong>both</strong> roles produced by <code>trend</code>, varying one parameter per step; the departure columns and the arrival columns therefore both describe <code>trend</code>, at the <em>arrival</em> tuning. That is not what ships, which takes departures from <code>endpoint</code>, so the departure column of that table is a diagnostic and not a recommendation. Version 7 labels the method in every row and separates “tuning path” tables from “what ships” tables so the two cannot be confused.</p>
</section>
<section id="productions-own-optimum" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="productions-own-optimum"><span class="header-section-number">7.3</span> 9.3 Production’s own optimum</h3>
<blockquote class="blockquote">
<p>You do not discuss which modes you’re using or which parameters. And the vote margin is only for <code>trend</code>, right?</p>
</blockquote>
<p>Both correct. That grid is <code>trend</code> for both roles, sweeping the flight-level cap and the radius while holding the vote margin at 2, the scheduled-service penalty at 10 NM and the ranking rule at exact distance. And yes — <strong>the vote margin is a <code>trend</code> parameter only.</strong> It is the majority a direction must win by across the smoothed altitude samples before the track is called a departure or an arrival; <code>endpoint</code> has no votes, it looks at one fix.</p>
<p>Version 7 states the held-fixed values above every sweep table, which version 6 does for some and not others.</p>
</section>
</section>
<section id="and-11-the-tables-that-do-not-explain-themselves" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="and-11-the-tables-that-do-not-explain-themselves"><span class="header-section-number">8</span> 10.1 and 11 — the tables that do not explain themselves</h2>
<blockquote class="blockquote">
<p>The table is not clear, what are you showing in each row?</p>
</blockquote>
<p>Both tables show the same kind of thing and neither says so.</p>
<p><strong>§10.1 (the tuning path)</strong> — each row adds one parameter change to the row above it, cumulatively, and reports the whole flight list rebuilt with everything adopted so far. Row <em>n</em> differs from row <em>n−1</em> by exactly one parameter. It answers “which of these changes is doing the work”, and the answer is the flight-level cap.</p>
<p><strong>§11 (the verdict)</strong> — each row is a complete configuration, not a step: which method names departures, which names arrivals, and how that combination scores. Rows are alternatives, not increments.</p>
<p>Version 7 gives each an explicit lead-in and shapes them differently on the page, so a cumulative path and a menu of alternatives never look alike.</p>
</section>
<section id="what-is-being-recommended-and-why" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="what-is-being-recommended-and-why"><span class="header-section-number">9</span> 11.1 What is being recommended, and why</h2>
<blockquote class="blockquote">
<p>You mention that for departures the flight level cap should be 15,000 ft or FL150, but earlier you said 120 was optimal. Why did it change?</p>
</blockquote>
<p>It did not change — the sentence puts two different parameters side by side without distinguishing them, which is a writing defect:</p>
<ul>
<li><strong>15,000 ft</strong> is <code>endpoint_height_ft</code>: how far <em>above the aerodrome’s own field elevation</em> the track’s first or last fix may sit and still count. It is a height above ground, not a flight level, and it belongs to <code>endpoint</code>.</li>
<li><strong>FL120</strong> was the best flight-level cap for departures in the <code>trend</code> grid — a different method, and one departures do not use.</li>
</ul>
<p>Since departures ship <code>endpoint</code>, the trend cap does not affect the shipped departure result at all. Version 7 never states a height and a flight level in the same sentence without naming the parameter each belongs to.</p>
<blockquote class="blockquote">
<p>Should we do the sweep up to FL250 or FL300? It seems to be getting better the higher we go.</p>
</blockquote>
<p>It does in the table you were shown, and it does not in the data. The <strong>pipeline</strong> grid stopped at FL120, so departures were still rising when the table ran out. The <strong>research sweep</strong> already ran to FL200 on both periods, and it turns:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 20%">
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Flight-level cap</th>
<th style="text-align: right;">2025 departures</th>
<th style="text-align: right;">2025 arrivals</th>
<th style="text-align: right;">2024 departures</th>
<th style="text-align: right;">2024 arrivals</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">FL20</td>
<td style="text-align: right;">50,629</td>
<td style="text-align: right;">58,513</td>
<td style="text-align: right;">43,401</td>
<td style="text-align: right;">47,366</td>
</tr>
<tr class="even">
<td style="text-align: right;">FL30</td>
<td style="text-align: right;">60,364</td>
<td style="text-align: right;">59,970</td>
<td style="text-align: right;">51,392</td>
<td style="text-align: right;">49,998</td>
</tr>
<tr class="odd">
<td style="text-align: right;">FL40</td>
<td style="text-align: right;">64,695</td>
<td style="text-align: right;">60,736</td>
<td style="text-align: right;">54,798</td>
<td style="text-align: right;">51,795</td>
</tr>
<tr class="even">
<td style="text-align: right;">FL60</td>
<td style="text-align: right;">67,439</td>
<td style="text-align: right;">61,069</td>
<td style="text-align: right;">57,456</td>
<td style="text-align: right;">52,668</td>
</tr>
<tr class="odd">
<td style="text-align: right;">FL80</td>
<td style="text-align: right;">68,895</td>
<td style="text-align: right;">60,269</td>
<td style="text-align: right;">58,678</td>
<td style="text-align: right;">52,506</td>
</tr>
<tr class="even">
<td style="text-align: right;">FL100</td>
<td style="text-align: right;">69,992</td>
<td style="text-align: right;">58,122</td>
<td style="text-align: right;">59,509</td>
<td style="text-align: right;">50,266</td>
</tr>
<tr class="odd">
<td style="text-align: right;">FL120</td>
<td style="text-align: right;">70,432</td>
<td style="text-align: right;">56,083</td>
<td style="text-align: right;">59,487</td>
<td style="text-align: right;">48,278</td>
</tr>
<tr class="even">
<td style="text-align: right;">FL150</td>
<td style="text-align: right;">69,462</td>
<td style="text-align: right;">53,692</td>
<td style="text-align: right;">58,248</td>
<td style="text-align: right;">45,529</td>
</tr>
<tr class="odd">
<td style="text-align: right;">FL200</td>
<td style="text-align: right;">65,643</td>
<td style="text-align: right;">49,695</td>
<td style="text-align: right;">54,518</td>
<td style="text-align: right;">41,006</td>
</tr>
</tbody>
</table>
<p>Held at vote margin 2 and 20 NM. Departures peak at FL120 in 2025 and FL100 in 2024, then fall; arrivals peak at FL60 on <strong>both</strong> periods. Coverage does keep rising with the cap — that part of the intuition is right — but accuracy falls faster, because samples taken higher up are further from the aerodrome that will turn out to be the answer.</p>
<p>Your instruction stands regardless and is being followed: version 7 sweeps <strong>FL25 to FL300 in steps of 25</strong>, plus FL40 and FL60 so the legacy and current values stay on the grid, on both periods and in the pipeline as well as the harness. Closing the grid is worth doing even when the turn is already visible — it is the difference between “it peaks here” and “it peaks here as far as we looked”.</p>
</section>
<section id="the-busiest-100-aerodromes" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="the-busiest-100-aerodromes"><span class="header-section-number">10</span> 13. The busiest 100 aerodromes</h2>
<blockquote class="blockquote">
<p>Does recall mean you match flight by flight on icao24, or do you compare movement numbers? Also, what is “recall” versus “recall, production”?</p>
</blockquote>
<p><strong>Flight by flight.</strong> Each reference flight from the Network Manager data is paired with an OPDI track on aircraft address (<code>icao24</code>) plus callsign plus date, and where several tracks match, the one starting closest to the reference off-block time. Per-aerodrome recall is then, of the flights whose <em>true</em> departure (or arrival) aerodrome is X, the share OPDI attributes to X. Movement counts are not compared directly — that is the other column:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Movements (truth)</strong></td>
<td>Reference flights whose true aerodrome is this one.</td>
</tr>
<tr class="even">
<td><strong>Found</strong></td>
<td>Of those, how many OPDI gave any answer for.</td>
</tr>
<tr class="odd">
<td><strong>Correct</strong></td>
<td>Of those, how many OPDI attributed to this aerodrome.</td>
</tr>
<tr class="even">
<td><strong>Recall</strong></td>
<td>Correct ÷ Movements (truth). Flight-level.</td>
</tr>
<tr class="odd">
<td><strong>Count ratio</strong></td>
<td>Movements OPDI <em>assigns to</em> this aerodrome ÷ Movements (truth). Includes flights that truly belong elsewhere, so it is the number an operational count would show, and it can exceed 1.</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Why is production always lower? Is this the original recall? What’s the new method and the legacy?</p>
</blockquote>
<p>“Recall, production” is the <strong>legacy</strong> run — the pre-2026 algorithm with its original constants and ring ranking. “Recall” without a qualifier is the shipped configuration. It is lower for legacy because that is the result: the shipped configuration answers more flights and answers them at least as accurately.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Role</th>
<th style="text-align: right;">Movements in truth</th>
<th style="text-align: right;">Recall, shipped</th>
<th style="text-align: right;">Recall, legacy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Departures</td>
<td style="text-align: right;">65,382</td>
<td style="text-align: right;">92.37%</td>
<td style="text-align: right;">83.41%</td>
</tr>
<tr class="even">
<td style="text-align: right;">Arrivals</td>
<td style="text-align: right;">65,360</td>
<td style="text-align: right;">79.59%</td>
<td style="text-align: right;">79.74%</td>
</tr>
</tbody>
</table>
<p>Version 7 renames the column to <strong>“Recall, legacy”</strong>, defines both measures above the table, and drops the word “production” from measurement contexts entirely.</p>
</section>
<section id="does-any-of-it-hold-on-a-second-period" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="does-any-of-it-hold-on-a-second-period"><span class="header-section-number">11</span> 14. Does any of it hold on a second period?</h2>
<blockquote class="blockquote">
<p>For <code>trend</code> it’s clear it’s not. We should train and fine-tune on both periods, then select the optimal parameters for both. We can validate on a third period in between.</p>
</blockquote>
<p>The first half is accepted and is being done — see §4 above, where the joint ranking already shows the shipped arrival cell placing 3rd of 360 across both periods, which is a much better result than version 6’s presentation implies. Version 6 compared two argmaxes and reported that they differed; that is nearly the weakest possible test, because an argmax over hundreds of cells moves under noise even when the surface is stable.</p>
<p>On the third period: worth doing, and it is a different kind of check — validation on data no parameter was chosen against. The constraint is that it needs committed Network Manager reference data for that month, so I would like to know which month you want before building anything. It is listed as an explicit open item rather than quietly dropped.</p>
</section>
<section id="limitations" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="limitations"><span class="header-section-number">12</span> 17. Limitations</h2>
<blockquote class="blockquote">
<p>You mention <code>trend</code> emits no out-of-area label at all. Why not? Should we implement it? I think we should.</p>
</blockquote>
<p>Agreed, and this is the sharpest gap the review found. <code>trend</code> names an aerodrome or says nothing; it has no way to say <em>“this flight came from outside the observed area”</em>. <code>endpoint</code> does — it labels out-of-area when the track’s endpoint sits at the edge of the ingestion region rather than near any aerodrome.</p>
<p>That matters more than it looks, because of which method ships for which role:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Role</th>
<th style="text-align: right;">Method shipped</th>
<th style="text-align: right;">Truly out-of-area</th>
<th style="text-align: right;">Labelled out-of-area</th>
<th style="text-align: right;">Out-of-area recall</th>
<th style="text-align: right;">Out-of-area precision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Departures</td>
<td style="text-align: right;">endpoint</td>
<td style="text-align: right;">8.30%</td>
<td style="text-align: right;">0.74%</td>
<td style="text-align: right;">7.98%</td>
<td style="text-align: right;">89.49%</td>
</tr>
<tr class="even">
<td style="text-align: right;">Arrivals</td>
<td style="text-align: right;">trend</td>
<td style="text-align: right;">8.37%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
</tr>
</tbody>
</table>
<p>Arrivals ship <code>trend</code>, so the arrival row is all zeros: 8.37% of reference arrivals genuinely originate outside the observed area and <strong>none of them can ever be labelled as such</strong>. Departures ship <code>endpoint</code> and do get labels — accurately, at 89.49% precision — but only 7.98% of the ones that qualify.</p>
<p>So there are two things to fix, not one: <code>trend</code> has no out-of-area concept at all, and <code>endpoint</code>’s recall is low even where it does. Version 7 gives <code>trend</code> the same border test <code>endpoint</code> uses, keeping <code>endpoint</code>’s precedence rule — aerodrome first, border second, because the other order labels departures from aerodromes near the edge as out-of-area while the aircraft is still on the runway. Both roles are then re-measured with out-of-area reported separately from naming skill, so a method cannot buy headline accuracy by labelling liberally.</p>
</section>
<section id="what-happens-to-each-point" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="what-happens-to-each-point"><span class="header-section-number">13</span> What happens to each point</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Point</th>
<th style="text-align: left;">Disposition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">General 1 — drop the wrong turns</td>
<td style="text-align: left;">Fixed in v6; absent from v7</td>
</tr>
<tr class="even">
<td style="text-align: left;">General 2 — define terms and gloss headers</td>
<td style="text-align: left;">v7 rewritten throughout</td>
</tr>
<tr class="odd">
<td style="text-align: left;">General 3 — production vs legacy</td>
<td style="text-align: left;">Fixed in v6; v7 uses one vocabulary</td>
</tr>
<tr class="even">
<td style="text-align: left;">Summary — lead with the better algorithm</td>
<td style="text-align: left;">Fixed in v6; v7 opens with it</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1 — recall introduced twice</td>
<td style="text-align: left;">Two measures renamed and defined separately</td>
</tr>
<tr class="even">
<td style="text-align: left;">3.3 — penalty on trend?</td>
<td style="text-align: left;">Yes, and it ships. Documentation fixed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4 — sweep both periods</td>
<td style="text-align: left;">Adopted as the selection rule for v7</td>
</tr>
<tr class="even">
<td style="text-align: left;">4 — introduce harness vs production</td>
<td style="text-align: left;">v7 introduces both stages up front</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4 — say which data</td>
<td style="text-align: left;">v7 has a sample section</td>
</tr>
<tr class="even">
<td style="text-align: left;">8 — negative results introduced badly</td>
<td style="text-align: left;">Reframed in v7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8.3 — what is within 2 NM</td>
<td style="text-align: left;">Defined here; being implemented for v7</td>
</tr>
<tr class="even">
<td style="text-align: left;">8.3 — why not in production</td>
<td style="text-align: left;">Was one period, harness only. Now being shipped if it survives stage 2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8.5 — sampler is not a negative result</td>
<td style="text-align: left;">Moved into the pipeline description in v7</td>
</tr>
<tr class="even">
<td style="text-align: left;">8.5 — what is a cell, median of what</td>
<td style="text-align: left;">Defined here and in v7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9 — pipeline introduced too late</td>
<td style="text-align: left;">v7 documents the pipeline before any result</td>
</tr>
<tr class="even">
<td style="text-align: left;">9 — ring count is not what we wanted</td>
<td style="text-align: left;">Already replaced by exact distance; stale text fixed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9 — keep smoothing across the FL boundary</td>
<td style="text-align: left;">Real gap; being fixed and measured</td>
</tr>
<tr class="even">
<td style="text-align: left;">9 — is ingestion/processing applied</td>
<td style="text-align: left;">01 and 02 yes; 02a never fed the flight list. Being wired in</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9 — flow chart</td>
<td style="text-align: left;">In v7</td>
</tr>
<tr class="even">
<td style="text-align: left;">9 — is the candidate cache pipeline-built</td>
<td style="text-align: left;">Yes, by build_endpoint_candidates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9.1 — do not discuss bugs</td>
<td style="text-align: left;">Removed from v6; absent from v7</td>
</tr>
<tr class="even">
<td style="text-align: left;">9.2 — coverage/accuracy for which mode</td>
<td style="text-align: left;">Every row labelled in v7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9.3 — which modes and parameters</td>
<td style="text-align: left;">Held-fixed values stated above every sweep in v7</td>
</tr>
<tr class="even">
<td style="text-align: left;">10.1 / 11 — unclear tables</td>
<td style="text-align: left;">Lead-ins added; cumulative vs alternative made visually distinct</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11.1 — FL150 vs FL120</td>
<td style="text-align: left;">Two different parameters; wording fixed</td>
</tr>
<tr class="even">
<td style="text-align: left;">11.1 — sweep higher</td>
<td style="text-align: left;">Harness already turns at FL150/200; v7 sweeps FL25-300 by 25 anyway</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13 — what is recall</td>
<td style="text-align: left;">Defined here and in v7; column renamed</td>
</tr>
<tr class="even">
<td style="text-align: left;">14 — tune on both periods</td>
<td style="text-align: left;">Adopted; third period awaiting your choice of month</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17 — out-of-area for trend</td>
<td style="text-align: left;">Being implemented for v7</td>
</tr>
</tbody>
</table>
<p><strong>Two things I need from you.</strong> Which month to use as the third, held-out validation period — it needs committed Network Manager reference data. And a decision on storage: wiring cleaning in materialises a second track table, and the bucket has room for one period but not two, so the 2024 period will have cleaning applied at read time unless you would rather free space.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>