<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="EUROCONTROL Performance Review Unit">
<meta name="dcterms.date" content="2026-08-10">

<title>Detecting departure and destination aerodromes from ADS-B – OPDI Papers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3fc44999f41da3927fa35e4e05887fd4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">OPDI Papers</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.eurocontrol.int/opdi"> 
<span class="menu-text">OPDI</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#sec-deficit" id="toc-sec-deficit" class="nav-link" data-scroll-target="#sec-deficit"><span class="header-section-number">1</span> Where the arrival deficit sits</a></li>
  <li><a href="#sec-silence" id="toc-sec-silence" class="nav-link" data-scroll-target="#sec-silence"><span class="header-section-number">2</span> Silence, not error</a></li>
  <li><a href="#sec-hard" id="toc-sec-hard" class="nav-link" data-scroll-target="#sec-hard"><span class="header-section-number">3</span> The abstained block is hard, not neglected</a></li>
  <li><a href="#sec-bearing" id="toc-sec-bearing" class="nav-link" data-scroll-target="#sec-bearing"><span class="header-section-number">4</span> Bearing alignment</a></li>
  <li><a href="#sec-compare" id="toc-sec-compare" class="nav-link" data-scroll-target="#sec-compare"><span class="header-section-number">5</span> The comparison that matters</a></li>
  <li><a href="#sec-vertical" id="toc-sec-vertical" class="nav-link" data-scroll-target="#sec-vertical"><span class="header-section-number">6</span> Why the vertical channel is dead</a></li>
  <li><a href="#sec-recommendation" id="toc-sec-recommendation" class="nav-link" data-scroll-target="#sec-recommendation"><span class="header-section-number">7</span> Recommendation</a>
  <ul class="collapse">
  <li><a href="#sec-next" id="toc-sec-next" class="nav-link" data-scroll-target="#sec-next"><span class="header-section-number">7.1</span> What the bearing test still needs</a></li>
  </ul></li>
  <li><a href="#sec-whole" id="toc-sec-whole" class="nav-link" data-scroll-target="#sec-whole"><span class="header-section-number">8</span> Bearing on the whole sample</a>
  <ul class="collapse">
  <li><a href="#sec-domain" id="toc-sec-domain" class="nav-link" data-scroll-target="#sec-domain"><span class="header-section-number">8.1</span> Why: the measure is out of domain on flights that landed</a></li>
  <li><a href="#sec-naming" id="toc-sec-naming" class="nav-link" data-scroll-target="#sec-naming"><span class="header-section-number">8.2</span> Rerank refutes the naming-rule argument</a></li>
  </ul></li>
  <li><a href="#sec-ruled-out" id="toc-sec-ruled-out" class="nav-link" data-scroll-target="#sec-ruled-out"><span class="header-section-number">9</span> What is now ruled out</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations"><span class="header-section-number">10</span> Limitations</a></li>
  <li><a href="#sec-reproducing" id="toc-sec-reproducing" class="nav-link" data-scroll-target="#sec-reproducing"><span class="header-section-number">11</span> Reproducing</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Detecting departure and destination aerodromes from ADS-B</h1>
<p class="subtitle lead">Version 5.1 — why arrivals are hard, and what recovers part of them</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>EUROCONTROL Performance Review Unit </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>Version 4 established that arrivals are harder than departures on every measure and recommended not changing the arrivals algorithm. It did not say <em>why</em>, and “we do not know why” is a poor basis for leaving a quarter of the data unlabelled. This version takes the arrival deficit apart.</p>
<p><strong>Three findings.</strong></p>
<p><strong>The arrival deficit is silence, not error.</strong> Of 87,152 in-area arrivals, 3,011 are answered wrongly and <strong>21,009 are not answered at all</strong>. Version 4’s emphasis on misnaming — built on a vivid case, Bilbao — described 12.54% of the problem.</p>
<p><strong>Most of that silence is ours, but it is not cheap to break.</strong> 13,300 flights had a usable candidate that the abstention refused; only 7,709 had nothing at all. So the recoverable share is nearly twice the permanently lost one. But guessing on the refused flights scores 28.27% — four right for eleven wrong. The abstention is doing its job.</p>
<p><strong>One new signal beats that, and it is horizontal.</strong> Whether the aircraft’s course <em>points at</em> the candidate aerodrome, measured tightly enough, recovers 425 correct arrivals for only 97 new errors — <strong>4.38:1</strong>, past the 2:1 exchange rate version 4.5 argued for, and the first thing tested to clear it. Vertical rate recovers nothing, and adding it destroys most of the gain.</p>
<p><strong>It is still not adoptable, for a reason outside its own comparison.</strong> The bearing test improves <code>endpoint</code>; production runs <code>trend</code> on arrivals, and <code>trend</code> beats the improved <code>endpoint</code> on <em>both</em> axes. The signal is real and the rule it improves is the wrong one (<a href="#sec-recommendation" class="quarto-xref">Section&nbsp;7</a>).</p>
<p>There is a single reason for that asymmetry, and it is the most useful thing in this paper:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Positions survive staleness; rates do not
</div>
</div>
<div class="callout-body-container callout-body">
<p>The OpenSky archive fills every second by carrying the last known position forward, and in this population roughly half the rows are repeats. A <strong>bearing between two genuinely measured fixes is correct regardless of when they were measured</strong>. A <strong>rate divides by an elapsed time the timestamps get wrong</strong> — the clock says ten minutes, the two real measurements may be ninety seconds apart.</p>
<p>That one sentence explains why bearing alignment works, and why vertical rate, closing rate and the approach cone of version 4.5 all failed.</p>
</div>
</div>
</section>
<section id="sec-deficit" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="sec-deficit"><span class="header-section-number">1</span> Where the arrival deficit sits</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals not correctly labelled, by class of the true aerodrome. 31,829 of 95,116 flights over 2025-06-05 to 07.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Flights</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Correct</th>
<th style="text-align: right;">Missing</th>
<th style="text-align: right;">Share of deficit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">large airport</td>
<td style="text-align: right;">80,683</td>
<td style="text-align: right;">76.11%</td>
<td style="text-align: right;">96.27%</td>
<td style="text-align: right;">59,120</td>
<td style="text-align: right;">21,563</td>
<td style="text-align: right;">67.75%</td>
</tr>
<tr class="even">
<td style="text-align: left;">out of area</td>
<td style="text-align: right;">7,964</td>
<td style="text-align: right;">5.12%</td>
<td style="text-align: right;">37.99%</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">7,809</td>
<td style="text-align: right;">24.53%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">medium airport</td>
<td style="text-align: right;">5,983</td>
<td style="text-align: right;">74.88%</td>
<td style="text-align: right;">89.55%</td>
<td style="text-align: right;">4,012</td>
<td style="text-align: right;">1,971</td>
<td style="text-align: right;">6.19%</td>
</tr>
<tr class="even">
<td style="text-align: left;">small airport</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">57.67%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">1.11%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">heliport</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">36.57%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">0.42%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Two thirds of the deficit is at large airports and a quarter is out-of-area. This paper addresses the first; the second remains the largest untouched block and is left for a successor.</p>
</section>
<section id="sec-silence" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-silence"><span class="header-section-number">2</span> Silence, not error</h2>
<p>“Not labelled” hides two situations that need opposite responses: <strong>no candidate existed</strong>, which is a receiver-coverage fact, and <strong>a candidate existed and the rule refused it</strong>, which is a choice. <code>nearest</code> never abstains, so its coverage is exactly the rate at which a candidate existed — no new computation is needed to separate them.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The 87,152 in-area arrivals, decomposed. In-area means the true destination is a real aerodrome, so out-of-area flights are excluded.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Outcome</th>
<th style="text-align: right;">Flights</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">correctly labelled</td>
<td style="text-align: right;">63,132</td>
<td style="text-align: right;">72.44%</td>
</tr>
<tr class="even">
<td style="text-align: left;">answered, wrong</td>
<td style="text-align: right;">3,011</td>
<td style="text-align: right;">3.45%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">candidate existed, abstained</td>
<td style="text-align: right;">13,300</td>
<td style="text-align: right;">15.26%</td>
</tr>
<tr class="even">
<td style="text-align: left;">no candidate anywhere</td>
<td style="text-align: right;">7,709</td>
<td style="text-align: right;">8.85%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>8.85% of in-area arrivals have no candidate at all.</strong> That is the hard ceiling: no endpoint-based method can exceed 91.15% coverage on this data, whatever rule it uses.</p>
</section>
<section id="sec-hard" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-hard"><span class="header-section-number">3</span> The abstained block is hard, not neglected</h2>
<p>The 13,300 refused flights look like free coverage. They are not.</p>
<p><code>endpoint</code> answers a subset of what <code>nearest</code> answers, and on shared flights both rank candidates by the same effective distance, so they return identical answers there. <code>nearest</code>’s <em>extra</em> correct answers are therefore exactly its score on the refused block: <strong>3,760 of 13,300, or 28.27%.</strong></p>
<p>Answering them all would add 3,760 correct labels and 9,540 wrong ones — 0.39:1. Against the exchange rate version 4.5 argued for, that is not close. <strong>“Relax the thresholds for arrivals” is now priced, and the price is bad.</strong></p>
<p>Why are they hard? Because of what an arrival endpoint is. The state-vector decimation study measured that an arrival’s last fix carries a position <strong>measured a median of 190 s earlier</strong> — at approach speed, roughly eight nautical miles back up the approach. The endpoint is not where the flight ended. Position alone cannot identify an aerodrome from eight miles out on a busy terminal area, and the abstention correctly declines to try.</p>
</section>
<section id="sec-bearing" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-bearing"><span class="header-section-number">4</span> Bearing alignment</h2>
<p>If position is exhausted, motion might not be. The measure is the angle between <strong>the direction the aircraft actually travelled</strong> over a window and <strong>the direction of the candidate aerodrome</strong>, seen from the far end of that window. Zero degrees means the track runs straight at it.</p>
<p>This involves no extrapolated position — it is an angle between two observed bearings — so the documented failures of trajectory extrapolation in version 2 and the 2025 PRC report do not bind it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why departures need no 180-degree correction
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A departing aircraft flies <em>away</em> from its aerodrome, so it looks as though the measure must be inverted for departures. It must not, because the origin of the angle already flips with the role.</p>
<p>The window is measured from the arrival’s <strong>last</strong> fix and the departure’s <strong>first</strong>, so its far end is earlier in time for an arrival and later for a departure. The bearing from that far end toward the near end is therefore the course in one case and the reverse course in the other. The question becomes <em>“is the aerodrome in the direction I am heading”</em> for an arrival and <em>“is the aerodrome in the direction I came from”</em> for a departure, and both read zero for a correct match.</p>
<p>The distinction matters because the two vertical and horizontal <em>rates</em> in the same analysis do carry an explicit per-role sign — they are signed along the time axis, and an angle between two bearings from a common origin is not. Confirmed empirically: correctly identified departures sit at a median of 2–9 degrees, not 171–178.</p>
<p>It also explains part of why the measure is weak for departures. By 30 minutes down-track the separation is 6 degrees against 2 — from far enough away, the true origin aerodrome and its neighbours all lie in much the same direction, so the angle stops discriminating. An arrival endpoint sits a median of eight nautical miles short of the runway, where the direction along the track is still informative.</p>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correct labels per error on the abstained arrival block, by window and angle gate. The block’s own baseline is 0.37. Note that these are computed on in-area truth only, and so overstate the population-level trade – see the next section.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Window</th>
<th style="text-align: right;">1°</th>
<th style="text-align: right;">2°</th>
<th style="text-align: right;">3°</th>
<th style="text-align: right;">5°</th>
<th style="text-align: right;">10°</th>
<th style="text-align: right;">20°</th>
<th style="text-align: right;">30°</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2 min</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">3 min</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5 min</td>
<td style="text-align: right;">2.81</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">1.33</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">0.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min</td>
<td style="text-align: right;">3.14</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: right;">2.52</td>
<td style="text-align: right;">2.38</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10 min</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: right;">2.45</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;">1.92</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">15 min</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">1.79</td>
<td style="text-align: right;">1.52</td>
<td style="text-align: right;">1.07</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">0.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 min</td>
<td style="text-align: right;">2.47</td>
<td style="text-align: right;">1.85</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 min</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.43</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Three things are visible and all three make physical sense.</p>
<p><strong>Short windows carry no information.</strong> At 2–3 minutes every cell sits near the 0.37 baseline. Over two minutes the aircraft’s displacement is small against its position error, so the bearing is noise.</p>
<p><strong>It switches on at 5 minutes and peaks at 7.</strong> A metric that were an artefact would not have an interior optimum with noise on both sides.</p>
<p><strong>The gate should tighten as the window lengthens.</strong> At loose gates short windows win, because over half an hour everything points roughly everywhere. At 1° that reverses — a long baseline gives a more precise bearing, so a tight gate becomes meaningful rather than noise.</p>
<p><strong>Accuracy plateaus at 70–76%</strong> however tight the gate. Roughly one arrival in four that points straight at an aerodrome lands somewhere else. Bearing alone has a ceiling, and tuning it further is close to exhausted.</p>
</section>
<section id="sec-compare" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sec-compare"><span class="header-section-number">5</span> The comparison that matters</h2>
<p>The sweep above scores the abstained block with out-of-area truth excluded. That flatters it: rescuing a flight whose true destination is outside the observed area produces a wrong answer the block analysis never counted. The honest test is the whole population.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals, all 95,116 ground-truth flights. <em>Net <span class="citation" data-cites="2:1">@2:1</span></em> prices each new error at two correct labels, the exchange rate of version 4.5; positive means the gate is worth adopting on that reasoning.</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
<th style="text-align: right;">d correct</th>
<th style="text-align: right;">d wrong</th>
<th style="text-align: right;">Ratio</th>
<th style="text-align: right;">Net <span class="citation" data-cites="2:1">@2:1</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">base (30 NM / 15,000 ft)</td>
<td style="text-align: right;">69.10%</td>
<td style="text-align: right;">95.63%</td>
<td style="text-align: right;">66.08%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 0.10 deg</td>
<td style="text-align: right;">69.65%</td>
<td style="text-align: right;">95.52%</td>
<td style="text-align: right;">66.53%</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">4.38:1</td>
<td style="text-align: right;">231</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 0.25 deg</td>
<td style="text-align: right;">69.83%</td>
<td style="text-align: right;">95.44%</td>
<td style="text-align: right;">66.65%</td>
<td style="text-align: right;">536</td>
<td style="text-align: right;">161</td>
<td style="text-align: right;">3.33:1</td>
<td style="text-align: right;">214</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 0.50 deg</td>
<td style="text-align: right;">69.96%</td>
<td style="text-align: right;">95.33%</td>
<td style="text-align: right;">66.70%</td>
<td style="text-align: right;">584</td>
<td style="text-align: right;">237</td>
<td style="text-align: right;">2.46:1</td>
<td style="text-align: right;">110</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 0.75 deg</td>
<td style="text-align: right;">70.05%</td>
<td style="text-align: right;">95.27%</td>
<td style="text-align: right;">66.74%</td>
<td style="text-align: right;">623</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">2.20:1</td>
<td style="text-align: right;">57</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 1 deg</td>
<td style="text-align: right;">70.14%</td>
<td style="text-align: right;">95.22%</td>
<td style="text-align: right;">66.79%</td>
<td style="text-align: right;">676</td>
<td style="text-align: right;">316</td>
<td style="text-align: right;">2.14:1</td>
<td style="text-align: right;">44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 2 deg</td>
<td style="text-align: right;">70.42%</td>
<td style="text-align: right;">95.07%</td>
<td style="text-align: right;">66.94%</td>
<td style="text-align: right;">817</td>
<td style="text-align: right;">434</td>
<td style="text-align: right;">1.88:1</td>
<td style="text-align: right;">-51</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 3 deg</td>
<td style="text-align: right;">70.68%</td>
<td style="text-align: right;">94.92%</td>
<td style="text-align: right;">67.09%</td>
<td style="text-align: right;">957</td>
<td style="text-align: right;">546</td>
<td style="text-align: right;">1.75:1</td>
<td style="text-align: right;">-135</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 min / 1 deg</td>
<td style="text-align: right;">71.59%</td>
<td style="text-align: right;">94.52%</td>
<td style="text-align: right;">67.67%</td>
<td style="text-align: right;">1,510</td>
<td style="text-align: right;">862</td>
<td style="text-align: right;">1.75:1</td>
<td style="text-align: right;">-214</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 min / 1 deg</td>
<td style="text-align: right;">73.13%</td>
<td style="text-align: right;">93.66%</td>
<td style="text-align: right;">68.50%</td>
<td style="text-align: right;">2,295</td>
<td style="text-align: right;">1,537</td>
<td style="text-align: right;">1.49:1</td>
<td style="text-align: right;">-779</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 1 deg +rate</td>
<td style="text-align: right;">69.39%</td>
<td style="text-align: right;">95.39%</td>
<td style="text-align: right;">66.19%</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">171</td>
<td style="text-align: right;">0.60:1</td>
<td style="text-align: right;">-240</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 3 deg +rate</td>
<td style="text-align: right;">69.60%</td>
<td style="text-align: right;">95.22%</td>
<td style="text-align: right;">66.27%</td>
<td style="text-align: right;">182</td>
<td style="text-align: right;">293</td>
<td style="text-align: right;">0.62:1</td>
<td style="text-align: right;">-404</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Departures, the same models. Every gate is a loss.</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
<th style="text-align: right;">d correct</th>
<th style="text-align: right;">d wrong</th>
<th style="text-align: right;">Ratio</th>
<th style="text-align: right;">Net <span class="citation" data-cites="2:1">@2:1</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">base (30 NM / 15,000 ft)</td>
<td style="text-align: right;">80.96%</td>
<td style="text-align: right;">98.16%</td>
<td style="text-align: right;">79.47%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 0.10 deg</td>
<td style="text-align: right;">81.06%</td>
<td style="text-align: right;">98.05%</td>
<td style="text-align: right;">79.48%</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">0.09:1</td>
<td style="text-align: right;">-170</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 0.25 deg</td>
<td style="text-align: right;">81.12%</td>
<td style="text-align: right;">98.00%</td>
<td style="text-align: right;">79.50%</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">0.22:1</td>
<td style="text-align: right;">-231</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 0.50 deg</td>
<td style="text-align: right;">81.23%</td>
<td style="text-align: right;">97.93%</td>
<td style="text-align: right;">79.55%</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">0.44:1</td>
<td style="text-align: right;">-281</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 0.75 deg</td>
<td style="text-align: right;">81.34%</td>
<td style="text-align: right;">97.86%</td>
<td style="text-align: right;">79.60%</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">242</td>
<td style="text-align: right;">0.52:1</td>
<td style="text-align: right;">-357</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 1 deg</td>
<td style="text-align: right;">81.47%</td>
<td style="text-align: right;">97.77%</td>
<td style="text-align: right;">79.65%</td>
<td style="text-align: right;">173</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">0.55:1</td>
<td style="text-align: right;">-451</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 2 deg</td>
<td style="text-align: right;">82.06%</td>
<td style="text-align: right;">97.25%</td>
<td style="text-align: right;">79.80%</td>
<td style="text-align: right;">313</td>
<td style="text-align: right;">733</td>
<td style="text-align: right;">0.43:1</td>
<td style="text-align: right;">-1,153</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 3 deg</td>
<td style="text-align: right;">82.44%</td>
<td style="text-align: right;">97.01%</td>
<td style="text-align: right;">79.97%</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">931</td>
<td style="text-align: right;">0.52:1</td>
<td style="text-align: right;">-1,381</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 min / 1 deg</td>
<td style="text-align: right;">82.28%</td>
<td style="text-align: right;">97.03%</td>
<td style="text-align: right;">79.83%</td>
<td style="text-align: right;">347</td>
<td style="text-align: right;">912</td>
<td style="text-align: right;">0.38:1</td>
<td style="text-align: right;">-1,477</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 min / 1 deg</td>
<td style="text-align: right;">82.58%</td>
<td style="text-align: right;">96.80%</td>
<td style="text-align: right;">79.94%</td>
<td style="text-align: right;">450</td>
<td style="text-align: right;">1,094</td>
<td style="text-align: right;">0.41:1</td>
<td style="text-align: right;">-1,738</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 min / 1 deg +rate</td>
<td style="text-align: right;">81.29%</td>
<td style="text-align: right;">97.95%</td>
<td style="text-align: right;">79.63%</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">171</td>
<td style="text-align: right;">0.88:1</td>
<td style="text-align: right;">-192</td>
</tr>
<tr class="even">
<td style="text-align: left;">7 min / 3 deg +rate</td>
<td style="text-align: right;">81.94%</td>
<td style="text-align: right;">97.54%</td>
<td style="text-align: right;">79.92%</td>
<td style="text-align: right;">432</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;">0.86:1</td>
<td style="text-align: right;">-578</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Because the bearing test only ever <em>adds</em> answers — a flight that already passed the abstention is untouched, and the aerodrome named is the same candidate either way — every newly answered flight falls in exactly one of the two delta columns. Their sum is the number of flights the gate rescued, and</p>
<p><span class="math display">\[\text{accuracy on the rescued} = \frac{\Delta\text{correct}}{\Delta\text{correct} + \Delta\text{wrong}}\]</span></p>
<p>is how often the gate is right <em>when it overrides the abstention</em>. It is not the model’s accuracy, which is swamped by the flights the change never touched: at 3° the gate is right 63.67% of the time on the 1,503 flights it rescues, while the model’s accuracy reads 94.92%. The benchmark to hold it against is 28.27% — what guessing blind on that population scores (<a href="#sec-hard" class="quarto-xref">Section&nbsp;3</a>).</p>
<p><strong>The gate must be tight, and tighter than seems physical.</strong> The ratio climbs monotonically as the gate narrows — 1.75:1 at 3°, 2.14:1 at 1°, 4.38:1 at 0.1° — and accuracy on the rescued flights rises with it, from 63.67% to 81.42%. Under 2:1 pricing the best gate is the tightest tested.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A prediction this refuted
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before running the sub-degree gates we argued they could not help. A runway complex spans 2–4 km, which from 40 NM subtends 2–3°, so a gate below a degree is tighter than the target: it should stop selecting for “heading to this airport” and start selecting for “aimed at the arbitrary reference coordinate OurAirports publishes”. Accuracy was predicted to plateau and counts to collapse into noise.</p>
<p>Accuracy did not plateau. It rose from 63.67% at 3° to 81.42% at 0.1°, monotonically, on 522 flights — not a handful.</p>
<p>The reasoning was wrong about what the gate selects. It is not resolving which runway an aircraft is aimed at; it is separating tracks <em>deliberately</em> pointed at a field, over a long straight leg, from tracks that happen to line up by coincidence. Coincidental alignment is common at 3° and rare at 0.1°, and that is the whole of the discrimination.</p>
</div>
</div>
<p><strong>Volume and rate trade against each other, and the rate wins.</strong> The widest gate tested, +bearing 30 min / 1 deg, recovers 2,295 correct labels — five times the tightest — but at 1.49:1 it costs 779 on the 2:1 reckoning. Chasing volume here is what the exchange rate exists to prevent.</p>
<p><strong>Departures lose.</strong> The same test adds 8 correct departures for 89 errors, 0.09:1. Consistent with everything this study has found: departures are not short of evidence, and adding evidence to a rule that is not short of it costs accuracy. <strong>Bearing should not be applied to departures.</strong></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The block-level ratios were optimistic, and this is why
</div>
</div>
<div class="callout-body-container callout-body">
<p>The abstained-block sweep reports 2.52:1 at 7 min / 3°. The same rule on the full population gives 1.75:1 — the same gate, the same rule, a third less. The difference is entirely the out-of-area flights the block analysis filtered out and the population cannot.</p>
<p>The lesson generalises: a rule evaluated on the subset it was designed for will beat its own field performance, and by a wide margin. Every ratio quoted in <a href="#sec-bearing" class="quarto-xref">Section&nbsp;4</a> should be read as an upper bound.</p>
</div>
</div>
</section>
<section id="sec-vertical" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-vertical"><span class="header-section-number">6</span> Why the vertical channel is dead</h2>
<p>Vertical rate is the obvious second signal, and it does not work. Two independent measures of the same quantity — the broadcast <code>vert_rate</code>, and an ordinary least squares fit of altitude on time across the window — agree in sign at close to chance.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Sign agreement between vertical measures on the abstained arrival block. 50% is chance.</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 17%">
<col style="width: 28%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Window</th>
<th style="text-align: right;">vert_rate vs OLS</th>
<th style="text-align: right;">2-point vs OLS</th>
<th style="text-align: right;">rows with vert_rate = 0</th>
<th style="text-align: right;">rows fresher than 5 s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">5 min</td>
<td style="text-align: right;">43.04%</td>
<td style="text-align: right;">47.13%</td>
<td style="text-align: right;">44.85%</td>
<td style="text-align: right;">10.58%</td>
</tr>
<tr class="even">
<td style="text-align: left;">10 min</td>
<td style="text-align: right;">51.88%</td>
<td style="text-align: right;">59.80%</td>
<td style="text-align: right;">45.29%</td>
<td style="text-align: right;">28.87%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 min</td>
<td style="text-align: right;">57.56%</td>
<td style="text-align: right;">64.28%</td>
<td style="text-align: right;">46.70%</td>
<td style="text-align: right;">43.92%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The same agreement at 20 minutes, banded by the share of rows carrying a position fresher than 5 s. Agreement tracks freshness, which identifies the cause rather than inferring it.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Window freshness</th>
<th style="text-align: right;">Flights</th>
<th style="text-align: right;">vert_rate vs OLS</th>
<th style="text-align: right;">2-point vs OLS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">&lt;30% fresh</td>
<td style="text-align: right;">11,960</td>
<td style="text-align: right;">49.76%</td>
<td style="text-align: right;">55.39%</td>
</tr>
<tr class="even">
<td style="text-align: left;">30-60%</td>
<td style="text-align: right;">10,451</td>
<td style="text-align: right;">59.71%</td>
<td style="text-align: right;">60.43%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">60-90%</td>
<td style="text-align: right;">11,309</td>
<td style="text-align: right;">62.50%</td>
<td style="text-align: right;">77.51%</td>
</tr>
<tr class="even">
<td style="text-align: left;">&gt;=90% fresh</td>
<td style="text-align: right;">1,067</td>
<td style="text-align: right;">71.79%</td>
<td style="text-align: right;">61.39%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Agreement rises with freshness, and 44.85% of rows carry a vertical rate of exactly zero — the signature of a value held over rather than measured. <strong>There is no vertical signal to extract here in either form.</strong></p>
<p>The measured consequence is in the comparison table: adding the vertical test to the bearing test cuts the arrival gain from 425 correct to 102, and the ratio from 4.38:1 to 0.60:1. It does not merely fail to help — <strong>it discards flights the bearing test correctly rescued.</strong></p>
</section>
<section id="sec-recommendation" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="sec-recommendation"><span class="header-section-number">7</span> Recommendation</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The bearing test improves <code>endpoint</code>, and <code>endpoint</code> is still the wrong rule for arrivals
</div>
</div>
<div class="callout-body-container callout-body">
<p>The comparison above scores every variant against the <code>endpoint</code> base. Scored against <strong>production</strong> instead, the picture changes completely.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals against production. The best bearing variant still loses on both axes.</caption>
<colgroup>
<col style="width: 41%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
<th style="text-align: right;">Correct</th>
<th style="text-align: right;">Wrong</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">trend (production)</td>
<td style="text-align: right;">68.06%</td>
<td style="text-align: right;">97.87%</td>
<td style="text-align: right;">66.61%</td>
<td style="text-align: right;">63,361</td>
<td style="text-align: right;">1,377</td>
</tr>
<tr class="even">
<td style="text-align: left;">endpoint 30 NM / 15,000 ft</td>
<td style="text-align: right;">69.10%</td>
<td style="text-align: right;">95.63%</td>
<td style="text-align: right;">66.08%</td>
<td style="text-align: right;">62,856</td>
<td style="text-align: right;">2,870</td>
</tr>
<tr class="odd">
<td style="text-align: left;">endpoint + bearing 0.10 deg</td>
<td style="text-align: right;">69.66%</td>
<td style="text-align: right;">95.52%</td>
<td style="text-align: right;">66.54%</td>
<td style="text-align: right;">63,292</td>
<td style="text-align: right;">2,967</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>trend</code> returns 69 more correct arrivals <strong>and</strong> 1,590 fewer wrong ones. It dominates: there is no exchange rate at which the bearing model wins.</p>
<p>The bearing test is a real signal and it genuinely improves <code>endpoint</code>. But <code>endpoint</code> was never the right rule for arrivals — version 4.5 concluded that already — so improving it does not produce a rule worth adopting. Earlier drafts of this section recommended the bearing test for arrivals without checking it against production. That was an error of comparison, not of measurement.</p>
</div>
</div>
<p><strong>Departures: <code>endpoint</code> at 30 NM, 15,000 ft, 10 NM scheduled-service penalty.</strong> Against production this is +10,993 correct labels for +645 wrong, about 17:1. Unchanged from version 4.5 and still the one clear win in this study.</p>
<p><strong>Arrivals: keep <code>trend</code>.</strong> Nothing in versions 4, 5 or 5.1 beats it.</p>
<p><strong>Do not apply the bearing test to departures</strong> — every gate is a loss, the best at 0.55:1. <strong>Do not pursue vertical rate</strong> (<a href="#sec-vertical" class="quarto-xref">Section&nbsp;6</a>). <strong>Do not use bearing as a veto, a replacement or a naming rule</strong> (<a href="#sec-whole" class="quarto-xref">Section&nbsp;8</a>).</p>
<p><strong>Publish the provenance columns.</strong> <code>adep_source</code> / <code>ades_source</code> distinguish “named an aerodrome”, “outside the observed area” and “could not determine”, which are one indistinguishable null in the published flight list today. Still the highest value per line of code in the study.</p>
<section id="sec-next" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="sec-next"><span class="header-section-number">7.1</span> What the bearing test still needs</h3>
<p>It has only ever been tested as a rescue for <strong><code>endpoint</code>’s</strong> abstention. <code>trend</code> — the rule actually recommended for arrivals — abstains on about a third of them, and <strong>whether bearing can rescue those flights is untested.</strong> That is the experiment that would give this finding somewhere to land, and the machinery now exists to run it.</p>
<p><strong>And out-of-area remains the larger prize</strong>: 24.53% of the arrival deficit, 7,809 flights, current recall 1.95%. Unlike the abstained block, nobody has shown it is hard.</p>
</section>
</section>
<section id="sec-whole" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="sec-whole"><span class="header-section-number">8</span> Bearing on the whole sample</h2>
<p>Used as a rescue, the bearing test can only <em>add</em> answers. That is a structural limit rather than a property of the data: a flight the abstention already accepts is untouched, so the 2,870 arrivals the base rule gets <strong>wrong</strong> were unreachable by every variant in <a href="#sec-compare" class="quarto-xref">Section&nbsp;5</a>. No rescue can raise accuracy.</p>
<p>Applying the test to every flight opens three questions the rescue framing cannot ask.</p>
<ul>
<li><strong>Veto</strong> — require alignment on flights the gate accepts, so bearing can remove answers. The only variant that can raise accuracy.</li>
<li><strong>Replace</strong> — alignment instead of the distance and height gate, testing whether that box carries anything the course does not.</li>
<li><strong>Rerank</strong> — choose <em>which</em> aerodrome by alignment rather than by effective distance. Version 4.5 argued the abstention is a gate and never a naming rule, and that arrivals fail by misnaming; this is the naming rule that argument implies.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals: the bearing test used four ways. Only the rescue helps; the other three are catastrophic.</caption>
<colgroup>
<col style="width: 41%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
<th style="text-align: right;">d correct</th>
<th style="text-align: right;">d wrong</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">base</td>
<td style="text-align: right;">69.10%</td>
<td style="text-align: right;">95.63%</td>
<td style="text-align: right;">66.08%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">rescue: gate OR align&lt;=0.1</td>
<td style="text-align: right;">69.66%</td>
<td style="text-align: right;">95.52%</td>
<td style="text-align: right;">66.54%</td>
<td style="text-align: right;">436</td>
<td style="text-align: right;">97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rescue: gate OR align&lt;=3.0</td>
<td style="text-align: right;">70.75%</td>
<td style="text-align: right;">94.93%</td>
<td style="text-align: right;">67.16%</td>
<td style="text-align: right;">1,020</td>
<td style="text-align: right;">544</td>
</tr>
<tr class="even">
<td style="text-align: left;">veto: gate AND align&lt;=3.0</td>
<td style="text-align: right;">22.78%</td>
<td style="text-align: right;">98.17%</td>
<td style="text-align: right;">22.36%</td>
<td style="text-align: right;">-41,585</td>
<td style="text-align: right;">-2,473</td>
</tr>
<tr class="odd">
<td style="text-align: left;">veto: gate AND align&lt;=0.1</td>
<td style="text-align: right;">11.67%</td>
<td style="text-align: right;">97.30%</td>
<td style="text-align: right;">11.36%</td>
<td style="text-align: right;">-52,052</td>
<td style="text-align: right;">-2,570</td>
</tr>
<tr class="even">
<td style="text-align: left;">replace: align&lt;=3.0 only</td>
<td style="text-align: right;">24.42%</td>
<td style="text-align: right;">95.95%</td>
<td style="text-align: right;">23.44%</td>
<td style="text-align: right;">-40,565</td>
<td style="text-align: right;">-1,929</td>
</tr>
<tr class="odd">
<td style="text-align: left;">replace: align&lt;=0.1 only</td>
<td style="text-align: right;">12.23%</td>
<td style="text-align: right;">96.59%</td>
<td style="text-align: right;">11.82%</td>
<td style="text-align: right;">-51,616</td>
<td style="text-align: right;">-2,473</td>
</tr>
<tr class="even">
<td style="text-align: left;">rerank by alignment, then gate</td>
<td style="text-align: right;">35.81%</td>
<td style="text-align: right;">86.50%</td>
<td style="text-align: right;">30.97%</td>
<td style="text-align: right;">-33,396</td>
<td style="text-align: right;">1,729</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rerank, gate OR align&lt;=0.1</td>
<td style="text-align: right;">37.42%</td>
<td style="text-align: right;">84.44%</td>
<td style="text-align: right;">31.60%</td>
<td style="text-align: right;">-32,800</td>
<td style="text-align: right;">2,667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>All three fail, and not marginally.</strong> The veto costs 41,585 correct arrivals at 3°. Replace costs 40,565. Rerank costs 33,396 correct labels <em>and</em> adds 1,729 wrong ones, dropping accuracy from 95.63% to 86.50%.</p>
<section id="sec-domain" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="sec-domain"><span class="header-section-number">8.1</span> Why: the measure is out of domain on flights that landed</h3>
<p>The diagnosis is not that alignment is a weak signal. It is that the flights the gate already accepts are the wrong population to ask.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>no course computable</th>
<th>median alignment</th>
<th>within 3°</th>
<th>on ground at the endpoint</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gate accepts</td>
<td>23.8%</td>
<td><strong>21°</strong></td>
<td>18.4%</td>
<td><strong>43.1%</strong></td>
</tr>
<tr class="even">
<td>gate refuses</td>
<td>24.3%</td>
<td>53°</td>
<td>5.2%</td>
<td>0.6%</td>
</tr>
</tbody>
</table>
<p><strong>43% of accepted arrivals are on the ground at their endpoint.</strong> For those, the last seven minutes are the approach, the landing roll and the taxi to stand — and the “course” over that window is dominated by ground manoeuvring, which points wherever the taxiways happen to run. A further quarter have no computable course at all. A veto at 3° therefore rejects roughly four in five flights it should keep.</p>
<p>The bearing test was developed on the abstained block, where every endpoint is airborne and en route by construction. <strong>Its domain is airborne endpoints, and the flights the gate accepts are mostly not that.</strong> Used as a rescue it never leaves its domain, which is why it works there and nowhere else.</p>
</section>
<section id="sec-naming" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="sec-naming"><span class="header-section-number">8.2</span> Rerank refutes the naming-rule argument</h3>
<p>The reranking result deserves its own note, because version 4.5 predicted the opposite. Its argument was that the abstention decides only <em>whether</em> to answer and never <em>what</em> to answer, that arrivals fail predominantly by misnaming, and that a trajectory-based naming rule was therefore the most promising fix available.</p>
<p>Ranking candidates by alignment instead of distance is that rule, and it is far worse than ranking by distance. The reason is geometric: <strong>an aerodrome 200 NM directly ahead is perfectly aligned.</strong> Alignment has no sense of scale, so as a ranking criterion it systematically prefers distant aerodromes that happen to lie on the track. Distance was doing enormous work that the argument did not credit.</p>
<p>Alignment is a <strong>filter over distance-ranked candidates</strong>, not a ranking criterion. That is what the rescue variant does, and it is the only form in which the signal is worth anything.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A small correction to <a href="#sec-compare" class="quarto-xref">Section&nbsp;5</a>
</div>
</div>
<div class="callout-body-container callout-body">
<p>The whole-sample run computes alignment without requiring an altitude, because alignment is purely horizontal; <a href="#sec-compare" class="quarto-xref">Section&nbsp;5</a>’s figures came from a routine that also fitted the vertical slope and so discarded samples with no altitude. The rescue numbers here are consequently a little higher — 436 correct against 425 at the same gate. The direction and the recommendation are unchanged; the earlier figures were conservative.</p>
</div>
</div>
</section>
</section>
<section id="sec-ruled-out" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="sec-ruled-out"><span class="header-section-number">9</span> What is now ruled out</h2>
<p>Recorded so it is not re-attempted:</p>
<ul>
<li><strong>Relaxing the abstention thresholds</strong> — priced at 0.39:1 (<a href="#sec-hard" class="quarto-xref">Section&nbsp;3</a>).</li>
<li><strong>The approach cone</strong> — version 4.5 measured it against the rectangle at matched coverage; departures lost up to 2.55 pp of accuracy, arrivals were a wash.</li>
<li><strong>Bucket decimation</strong> — the state-vector study measured +55 correct arrivals per day for a change that rewrites <code>track_id</code> for every published row.</li>
<li><strong>Vertical rate, in any form</strong> (<a href="#sec-vertical" class="quarto-xref">Section&nbsp;6</a>).</li>
<li><strong>Trajectory extrapolation</strong> — version 2 and the 2025 PRC report, independently.</li>
<li><strong>Bearing as a veto, a replacement, or a naming rule</strong> (<a href="#sec-whole" class="quarto-xref">Section&nbsp;8</a>). Only the rescue form works, and only because it stays inside the measure’s domain.</li>
</ul>
</section>
<section id="sec-limitations" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="sec-limitations"><span class="header-section-number">10</span> Limitations</h2>
<ul>
<li><strong>One sample.</strong> Three days, 2025-06-05 to 07. The operating points were chosen as the argmax over 120 grid cells of that same sample, so the ratios are optimistic. The 2° and 3° columns peak cleanly at 7 minutes, which is why the <em>region</em> is credible; the specific numbers are not validated.</li>
<li><strong>Two measurement bugs were found in this work</strong>, both by sanity checks rather than by anything failing: <code>angle_between</code> used <code>%</code>, and Spark’s remainder keeps the sign of the dividend, so bearings 20° apart measured 340° whenever the pair straddled north — the tell was a median alignment of 186° on a 0–180° scale. And the altitude slope divided an altitude change by an elapsed time drawn from different rows, because <code>min_by</code> skips nulls where <code>min</code> does not. Both are fixed; both had already produced numbers that were reported before being caught.</li>
<li><strong>The <code>&gt;=90% fresh</code> band reverses the freshness trend</strong> for the 2-point measure, on about a thousand flights. Either small-sample noise or something real about very short tracks. Not resolved.</li>
<li><strong><code>nearest</code> and <code>endpoint</code> are assumed to answer identically where both answer</strong>, which underpins <a href="#sec-hard" class="quarto-xref">Section&nbsp;3</a>. It follows from both ranking on the same effective distance, but it is an argument, not a measurement.</li>
</ul>
</section>
<section id="sec-reproducing" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="sec-reproducing"><span class="header-section-number">11</span> Reproducing</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the abstained block, its motion profile, and the angle x window sweep</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/abstained_vertical.py <span class="at">--results-dir</span> <span class="op">&lt;</span>dir<span class="op">&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># which vertical measure to trust, banded by freshness</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/vertical_measure.py <span class="at">--results-dir</span> <span class="op">&lt;</span>dir<span class="op">&gt;</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># base against the motion variants, whole population</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/motion_model_compare.py <span class="at">--results-dir</span> <span class="op">&lt;</span>dir<span class="op">&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Rendering this page needs no credentials, no database and no cluster.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>