<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="EUROCONTROL Performance Review Unit">
<meta name="dcterms.date" content="2026-08-09">

<title>Detecting departure and destination aerodromes from ADS-B – OPDI Papers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3fc44999f41da3927fa35e4e05887fd4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">OPDI Papers</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.eurocontrol.int/opdi"> 
<span class="menu-text">OPDI</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#sec-preprocessing" id="toc-sec-preprocessing" class="nav-link" data-scroll-target="#sec-preprocessing"><span class="header-section-number">1</span> What the pipeline does before any method runs</a></li>
  <li><a href="#sec-metrics" id="toc-sec-metrics" class="nav-link" data-scroll-target="#sec-metrics"><span class="header-section-number">2</span> How the metrics work</a>
  <ul class="collapse">
  <li><a href="#precision-and-recall-for-out-of-area" id="toc-precision-and-recall-for-out-of-area" class="nav-link" data-scroll-target="#precision-and-recall-for-out-of-area"><span class="header-section-number">2.1</span> Precision and recall, for out-of-area</a></li>
  <li><a href="#in-area-coverage-and-accuracy" id="toc-in-area-coverage-and-accuracy" class="nav-link" data-scroll-target="#in-area-coverage-and-accuracy"><span class="header-section-number">2.2</span> In-area coverage and accuracy</a></li>
  </ul></li>
  <li><a href="#sec-modes" id="toc-sec-modes" class="nav-link" data-scroll-target="#sec-modes"><span class="header-section-number">3</span> The three modes</a>
  <ul class="collapse">
  <li><a href="#trend-the-current-production-algorithm" id="toc-trend-the-current-production-algorithm" class="nav-link" data-scroll-target="#trend-the-current-production-algorithm"><span class="header-section-number">3.1</span> <code>trend</code> — the current production algorithm</a></li>
  <li><a href="#nearest-the-traffic-librarys-rule" id="toc-nearest-the-traffic-librarys-rule" class="nav-link" data-scroll-target="#nearest-the-traffic-librarys-rule"><span class="header-section-number">3.2</span> <code>nearest</code> — the <em>traffic</em> library’s rule</a></li>
  <li><a href="#endpoint-nearest-with-abstention" id="toc-endpoint-nearest-with-abstention" class="nav-link" data-scroll-target="#endpoint-nearest-with-abstention"><span class="header-section-number">3.3</span> <code>endpoint</code> — nearest, with abstention</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a></li>
  <li><a href="#sec-radius" id="toc-sec-radius" class="nav-link" data-scroll-target="#sec-radius"><span class="header-section-number">5</span> What a distance cap costs</a>
  <ul class="collapse">
  <li><a href="#sec-accuracy-sweep" id="toc-sec-accuracy-sweep" class="nav-link" data-scroll-target="#sec-accuracy-sweep"><span class="header-section-number">5.1</span> What the coverage view hides</a></li>
  </ul></li>
  <li><a href="#sec-penalty" id="toc-sec-penalty" class="nav-link" data-scroll-target="#sec-penalty"><span class="header-section-number">6</span> Preferring aerodromes with scheduled service</a></li>
  <li><a href="#sec-ooa" id="toc-sec-ooa" class="nav-link" data-scroll-target="#sec-ooa"><span class="header-section-number">7</span> Out-of-area</a>
  <ul class="collapse">
  <li><a href="#how-it-is-derived" id="toc-how-it-is-derived" class="nav-link" data-scroll-target="#how-it-is-derived"><span class="header-section-number">7.1</span> How it is derived</a></li>
  <li><a href="#what-it-does-to-the-numbers" id="toc-what-it-does-to-the-numbers" class="nav-link" data-scroll-target="#what-it-does-to-the-numbers"><span class="header-section-number">7.2</span> What it does to the numbers</a></li>
  </ul></li>
  <li><a href="#sec-crosscheck" id="toc-sec-crosscheck" class="nav-link" data-scroll-target="#sec-crosscheck"><span class="header-section-number">8</span> Cross-check against the reference</a>
  <ul class="collapse">
  <li><a href="#sec-per-type" id="toc-sec-per-type" class="nav-link" data-scroll-target="#sec-per-type"><span class="header-section-number">8.1</span> By class of aerodrome</a></li>
  <li><a href="#sec-outliers" id="toc-sec-outliers" class="nav-link" data-scroll-target="#sec-outliers"><span class="header-section-number">8.2</span> Busy aerodromes that fail outright</a></li>
  </ul></li>
  <li><a href="#sec-operating-point" id="toc-sec-operating-point" class="nav-link" data-scroll-target="#sec-operating-point"><span class="header-section-number">9</span> Choosing the operating point</a>
  <ul class="collapse">
  <li><a href="#sec-op-dep" id="toc-sec-op-dep" class="nav-link" data-scroll-target="#sec-op-dep"><span class="header-section-number">9.1</span> Departures: every cell wins, but the marginal return collapses</a></li>
  <li><a href="#sec-op-arr" id="toc-sec-op-arr" class="nav-link" data-scroll-target="#sec-op-arr"><span class="header-section-number">9.2</span> Arrivals: nothing in the grid earns its place</a></li>
  <li><a href="#sec-op-metrics" id="toc-sec-op-metrics" class="nav-link" data-scroll-target="#sec-op-metrics"><span class="header-section-number">9.3</span> Why no single metric can make this choice</a></li>
  <li><a href="#sec-op-choice" id="toc-sec-op-choice" class="nav-link" data-scroll-target="#sec-op-choice"><span class="header-section-number">9.4</span> The exchange rate, and the choice</a></li>
  </ul></li>
  <li><a href="#sec-hybrid" id="toc-sec-hybrid" class="nav-link" data-scroll-target="#sec-hybrid"><span class="header-section-number">10</span> What <code>endpoint</code> could borrow from <code>trend</code></a>
  <ul class="collapse">
  <li><a href="#sec-why-trend" id="toc-sec-why-trend" class="nav-link" data-scroll-target="#sec-why-trend"><span class="header-section-number">10.1</span> Why <code>trend</code> wins arrivals</a></li>
  <li><a href="#sec-cone" id="toc-sec-cone" class="nav-link" data-scroll-target="#sec-cone"><span class="header-section-number">10.2</span> Tested: an approach cone instead of a rectangle</a></li>
  <li><a href="#sec-untested" id="toc-sec-untested" class="nav-link" data-scroll-target="#sec-untested"><span class="header-section-number">10.3</span> Untested, in order of expected value</a></li>
  <li><a href="#sec-hybrid-dep" id="toc-sec-hybrid-dep" class="nav-link" data-scroll-target="#sec-hybrid-dep"><span class="header-section-number">10.4</span> Should any of this apply to departures too?</a></li>
  </ul></li>
  <li><a href="#recommendation" id="toc-recommendation" class="nav-link" data-scroll-target="#recommendation"><span class="header-section-number">11</span> Recommendation</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations"><span class="header-section-number">12</span> Limitations</a></li>
  <li><a href="#reproducing" id="toc-reproducing" class="nav-link" data-scroll-target="#reproducing"><span class="header-section-number">13</span> Reproducing</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Detecting departure and destination aerodromes from ADS-B</h1>
<p class="subtitle lead">Version 4.5 — detection inside the pipeline</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>EUROCONTROL Performance Review Unit </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>Versions 1–3 of this study ran outside the OPDI pipeline. They reimplemented aerodrome proximity with their own coordinate grid, which made every recommendation awkward to adopt: the findings were expressed in nautical miles while production ranks by H3 cell membership, so acting on them meant re-deriving rather than transcribing.</p>
<p>Version 4 moves detection <strong>into the pipeline</strong>. Three modes now share one candidate-detection stage — H3 as the index, exact great-circle distance as the comparison — and are selected by a <code>mode</code> parameter on the production function. The pipeline ran end to end on three days of 2025-06, producing a real flight list scored against Network Manager ground truth.</p>
<p>Three results:</p>
<p><strong>Endpoint abstention buys +12.47 pp of departure coverage for -0.84 pp of accuracy.</strong> A real trade, not a free win — and a different conclusion from version 3, for a reason worth stating up front.</p>
<p><strong>The detection radius barely matters; the height threshold is everything.</strong> Extending the radius from 40 NM to 110 NM changes departure coverage by +0.20 pp.&nbsp;Raising the height cut-off from on-ground-only to unrestricted changes it by more than fifty points. A distance cap costs almost nothing, which is worth knowing because it is the parameter most likely to be tuned.</p>
<p><strong>Preferring aerodromes with scheduled service is close to free.</strong> Ranking candidates on a distance penalised for aerodromes without scheduled service gains <strong>+0.67 pp of departure accuracy</strong> and <strong>+1.24 pp of arrival accuracy</strong>, at no measurable cost in coverage.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The production baseline improved too
</div>
</div>
<div class="callout-body-container callout-body">
<p>Version 3 concluded that endpoint abstention beat production on <em>both</em> coverage and accuracy. That no longer holds, and the reason is not that abstention got worse — it is that <strong>the baseline got better</strong>. Running the altitude-trend algorithm on H3 candidates with exact distances lifts its departure accuracy from 97.45% in version 3 to 98.82% here.</p>
<p>The comparison in this version is therefore harder and fairer than the one before it. Version 3’s numbers are not comparable to these and remain published unchanged.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What changed since version 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Every headline number is unchanged throughout. The point releases report more of what version 4 already computed, plus three new computations.</p>
<p><strong>4.5</strong></p>
<ul>
<li>A <strong>result analysis</strong> that picks an operating point and argues for it (<a href="#sec-operating-point" class="quarto-xref">Section&nbsp;9</a>), in flights rather than percentages, separately for departures and arrivals. It finds the currently published parameters are past break-even, and that no arrival setting beats production.</li>
<li><strong>Why no single metric can choose</strong> the parameters — each of coverage, accuracy and overall correctness is maximised at a degenerate corner (<a href="#sec-op-metrics" class="quarto-xref">Section&nbsp;9.3</a>).</li>
<li><strong>An approach cone tested against the rectangle</strong> (<a href="#sec-cone" class="quarto-xref">Section&nbsp;10.2</a>), and what <code>endpoint</code> could borrow from <code>trend</code> for arrivals (<a href="#sec-hybrid" class="quarto-xref">Section&nbsp;10</a>).</li>
</ul>
<p><strong>4.3</strong></p>
<ul>
<li>The height sweep runs to <strong>40,000 ft</strong> rather than stopping at 20,000. At 20,000 ft six points of departure coverage still separated the curve from the unrestricted case, so the old grid cut it off mid-rise and left the reader to guess where it flattened.</li>
</ul>
<p><strong>4.2</strong></p>
<ul>
<li>A breakdown <strong>by class of ground-truth aerodrome</strong> (<a href="#sec-per-type" class="quarto-xref">Section&nbsp;8.1</a>) — the one new computation. It surfaces the sharpest finding in the study: on small aerodromes and heliports the method is wrong <strong>every single time it answers</strong>, because the detection reference contains large and medium aerodromes only.</li>
<li>Overall correctness is reported in the <strong>radius and penalty sweeps</strong>, not only in the results table.</li>
<li>The per-aerodrome cross-check extends to the <strong>100 busiest</strong>, and now covers <strong>arrivals as well as departures</strong>.</li>
</ul>
<p><strong>4.1</strong></p>
<ul>
<li>Results given for <strong>both roles on all four measures</strong>: arrival overall correctness and both in-area figures were computed but not printed.</li>
<li>The sweep plotted <strong>on accuracy as well as coverage</strong>, for both roles. Accuracy peaks near the ground and falls as height is admitted, so the coverage view alone overstates the case for a high threshold (<a href="#sec-accuracy-sweep" class="quarto-xref">Section&nbsp;5.1</a>).</li>
<li>The cross-check names the <strong>mode and parameters</strong> it was produced at, and separates the out-of-area bucket from the movement-count ratio it was distorting.</li>
<li>Figure captions generated from the data rather than written by hand.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="sec-preprocessing" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="sec-preprocessing"><span class="header-section-number">1</span> What the pipeline does before any method runs</h2>
<p>The population a method is judged on is fixed long before the method executes. Each stage below discards something, and what survives is what detection sees.</p>
<p><strong>1. Ingest</strong> (<code>ingestion/osn_statevectors.py</code>). Hourly partitions are read from the OpenSky archive and immediately filtered to the European bounding box <code>(-25.87, 26.75, 49.66, 70.26)</code> and decimated to one sample every 5 s. Both filters are applied <em>before</em> anything is written. For the three days here that turned roughly 60 GB of raw feed into <strong>142,630,930 state vectors</strong>.</p>
<p><em>What is discarded:</em> everything outside Europe, and four samples in five. The 5 s decimation is the reason a track’s “first sample” can be several seconds into the take-off roll rather than at the stand.</p>
<p><strong>2. Track construction</strong> (<code>pipeline/tracks.py</code>). State vectors are grouped into tracks by <code>SHA2(icao24 ‖ callsign)</code> and split on a gap of over 30 minutes, or over 15 minutes below 5,000 ft. Each sample is also indexed into H3 cells at resolutions 7 and 12.</p>
<p><em>What is discarded:</em> nothing, but the grouping decides what counts as one flight. Version 2 measured the consequences — roughly one matched flight in ten is split across more than one track, and a few percent of tracks cover more than one flight.</p>
<p><strong>3. Aerodrome zones</strong> (<code>reference/h3_airport_zones.py</code>). Each aerodrome is surrounded by concentric rings of H3 res-7 cells: 5 NM steps out to 40 NM, then 10 NM steps to 110 NM. Every cell carries the ring band it belongs to, so a consumer chooses its own radius at read time. <strong>33,751,619 (aerodrome, cell) rows</strong> for the 1,353 large and medium aerodromes in the area.</p>
<p><em>Why it reaches 110 NM:</em> the same table serves ASMA ring crossings at 40 and 100 NM. Detection uses a fraction of it.</p>
<p><strong>4. Endpoint candidates</strong> (<code>pipeline/flights.py</code>). For each track, the first and last sample are matched against the zone table on <code>h3_res_7</code>, and the exact great-circle distance to each candidate aerodrome is computed. The result is cached as <code>opdi_endpoint_candidates</code> — <strong>7,491,655 rows</strong>.</p>
<p>This is the step that makes the sweeps in this paper affordable. Deriving candidates from state vectors is expensive; once cached, changing a threshold is a filter and a re-rank over a few million rows rather than a pass over 142 million. Reducing to the two endpoint samples <em>before</em> the join is also what makes the full 110 NM reach cheap — about a million rows to match, not the whole month.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>H3 as an index, distance as the comparison
</div>
</div>
<div class="callout-body-container callout-body">
<p>The H3 join answers “which aerodromes are plausibly near this sample” in one equi-join, without a spatial cross product. It does not answer “how near”, because a cell inside a 40 NM ring can still be more than 40 NM from the aerodrome. So every candidate is then measured exactly, and the distance — not the cell — decides.</p>
</div>
</div>
</section>
<section id="sec-metrics" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-metrics"><span class="header-section-number">2</span> How the metrics work</h2>
<p>This study turns on the difference between measures that are easy to conflate, so each is defined before any number appears.</p>
<p>Let <span class="math inline">\(G\)</span> be the ground-truth flights and <span class="math inline">\(A \subseteq G\)</span> those the method answered.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Definition</th>
<th>The question it answers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Coverage</strong></td>
<td><span class="math inline">\(\lvert A \rvert / \lvert G \rvert\)</span></td>
<td>How often does it say <em>something</em>?</td>
</tr>
<tr class="even">
<td><strong>Accuracy</strong></td>
<td><span class="math inline">\(\lvert \text{correct} \rvert / \lvert A \rvert\)</span></td>
<td>When it speaks, how often is it right?</td>
</tr>
<tr class="odd">
<td><strong>Overall correctness</strong></td>
<td><span class="math inline">\(\lvert \text{correct} \rvert / \lvert G \rvert\)</span></td>
<td>Of everything, how much did it get right?</td>
</tr>
</tbody>
</table>
<p>A flight whose trajectory was never seen counts against coverage. That is deliberate: ground truth is the denominator throughout, so “we had no data” is a miss rather than an excluded row.</p>
<p><strong>Accuracy alone is close to meaningless here.</strong> It says nothing about how often a method speaks, so a method that answers rarely and cautiously can post a better accuracy than one doing far more useful work. Consider two methods on the same flights:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Accuracy favours the cautious method; overall correctness shows the eager one labels more than twice as many flights correctly.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall correctness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cautious</td>
<td style="text-align: right;">40.00%</td>
<td style="text-align: right;">99.00%</td>
<td style="text-align: right;">39.60%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eager</td>
<td style="text-align: right;">95.00%</td>
<td style="text-align: right;">88.00%</td>
<td style="text-align: right;">83.60%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Neither is simply better — they suit different uses. A flight list that downstream users treat as authoritative may well prefer the cautious one. The point is that <strong>no single number decides it</strong>, which is why all three are reported throughout.</p>
<section id="precision-and-recall-for-out-of-area" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="precision-and-recall-for-out-of-area"><span class="header-section-number">2.1</span> Precision and recall, for out-of-area</h3>
<p>Some flights have an origin or destination outside the observed area entirely. “Out of area” is therefore a legitimate <em>answer</em>, not a failure — and how well a method identifies those cases is measured with the standard pair:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Definition</th>
<th>The question it answers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Precision</strong></td>
<td>of flights <em>labelled</em> out-of-area, the fraction that were</td>
<td>When it says out-of-area, is it right?</td>
</tr>
<tr class="even">
<td><strong>Recall</strong></td>
<td>of flights that <em>were</em> out-of-area, the fraction it labelled</td>
<td>Of the cases out there, how many did it catch?</td>
</tr>
</tbody>
</table>
<p>Precision is accuracy computed on one label instead of all of them. Recall has no counterpart in the table above, and it is the one that matters here: <strong>high precision with low recall means a method is right when it fires but rarely fires</strong>.</p>
<p>In the standard confusion-matrix vocabulary, with “out-of-area” as the positive class: precision is <span class="math inline">\(TP/(TP+FP)\)</span> and recall is <span class="math inline">\(TP/(TP+FN)\)</span>. Coverage has no confusion-matrix equivalent, because it measures whether the method produced <em>any</em> label rather than which one.</p>
</section>
<section id="in-area-coverage-and-accuracy" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="in-area-coverage-and-accuracy"><span class="header-section-number">2.2</span> In-area coverage and accuracy</h3>
<p>Because roughly one flight in twelve is genuinely out of area, a method could raise its apparent accuracy simply by labelling out-of-area liberally. So the same two measures are also reported <strong>restricted to flights whose truth is a real aerodrome</strong> — detection skill with the free wins removed. When headline and in-area figures diverge, the gap is exactly the contribution of out-of-area labelling.</p>
</section>
</section>
<section id="sec-modes" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-modes"><span class="header-section-number">3</span> The three modes</h2>
<p>All three read the same cached candidates. They differ in what evidence they consult and, more importantly, in when they are willing to stay silent.</p>
<section id="trend-the-current-production-algorithm" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="trend-the-current-production-algorithm"><span class="header-section-number">3.1</span> <code>trend</code> — the current production algorithm</h3>
<p><em>Evidence:</em> every state vector below <strong>FL40</strong> that falls inside an aerodrome’s detection zone, currently 30 NM.</p>
<p><em>Rule:</em> for each (track, aerodrome) pair, smooth altitude over a 5-sample window, count how often the smoothed value rises versus falls, and require a margin of 4 either way. A positive margin is a take-off, negative a landing.</p>
<p><em>Abstains when:</em> the margin is within ±4 — classified <code>ambiguous</code> and <strong>the flight is dropped entirely</strong>.</p>
<p><em>Failure mode:</em> a flight seen only above FL40 near its origin, or with a noisy altitude trace, silently loses its aerodrome. The FL40 gate is the binding constraint, not the 30 NM radius.</p>
</section>
<section id="nearest-the-traffic-librarys-rule" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="nearest-the-traffic-librarys-rule"><span class="header-section-number">3.2</span> <code>nearest</code> — the <em>traffic</em> library’s rule</h3>
<p><em>Evidence:</em> the track’s first and last sample. Nothing else — no altitude, no ground state, no trend.</p>
<p><em>Rule:</em> name the nearest aerodrome by effective distance.</p>
<p><em>Abstains when:</em> never, except when no candidate exists at all.</p>
<p><em>Failure mode:</em> it answers just as confidently for a track that begins in the cruise as for one that begins at a stand. Its coverage is the highest of any method and its accuracy the lowest, and both facts have the same cause.</p>
</section>
<section id="endpoint-nearest-with-abstention" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="endpoint-nearest-with-abstention"><span class="header-section-number">3.3</span> <code>endpoint</code> — nearest, with abstention</h3>
<p><em>Evidence:</em> the same two samples, plus their height above <strong>field elevation</strong> and their <code>on_ground</code> flag.</p>
<p><em>Rule:</em> name the nearest aerodrome, but only if the endpoint is within <code>radius_nm</code> <strong>and</strong> either below <code>height_ft</code> above that aerodrome’s elevation or flagged on the ground. Otherwise, if the endpoint lies near the boundary of the observed area, answer out-of-area. Otherwise answer nothing.</p>
<p><em>Why height above field elevation:</em> a fixed altitude cut-off means nothing at an aerodrome sitting at 5,000 ft. Elevation comes from OurAirports and is missing for about 3% of large and medium aerodromes; where it is missing the height test is skipped and only the ground flag can satisfy the rule, rather than silently comparing against sea level.</p>
<p><em>Failure mode:</em> it inherits <code>nearest</code>’s naming and therefore its confusions between neighbouring aerodromes; the abstention only decides <em>whether</em> to answer, never <em>what</em> to answer.</p>
</section>
</section>
<section id="results" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="results"><span class="header-section-number">4</span> Results</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The three modes on 95,116 ground-truth flights, 2025-06-05 to 07. Overall correctness is coverage x accuracy. Produced at 40 NM detection radius, 15,000 ft abstention height, 10 NM scheduled-service penalty.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Movements</th>
<th style="text-align: left;">Mode</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
<th style="text-align: right;">In-area cov</th>
<th style="text-align: right;">In-area acc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">trend</td>
<td style="text-align: right;">68.72%</td>
<td style="text-align: right;">98.82%</td>
<td style="text-align: right;">67.91%</td>
<td style="text-align: right;">74.84%</td>
<td style="text-align: right;">98.95%</td>
</tr>
<tr class="even">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">nearest</td>
<td style="text-align: right;">91.68%</td>
<td style="text-align: right;">87.78%</td>
<td style="text-align: right;">80.48%</td>
<td style="text-align: right;">96.26%</td>
<td style="text-align: right;">91.17%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">endpoint</td>
<td style="text-align: right;">81.20%</td>
<td style="text-align: right;">97.98%</td>
<td style="text-align: right;">79.55%</td>
<td style="text-align: right;">87.43%</td>
<td style="text-align: right;">98.41%</td>
</tr>
<tr class="even">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">trend</td>
<td style="text-align: right;">68.06%</td>
<td style="text-align: right;">97.87%</td>
<td style="text-align: right;">66.61%</td>
<td style="text-align: right;">74.23%</td>
<td style="text-align: right;">97.94%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">nearest</td>
<td style="text-align: right;">88.56%</td>
<td style="text-align: right;">79.41%</td>
<td style="text-align: right;">70.33%</td>
<td style="text-align: right;">91.15%</td>
<td style="text-align: right;">84.20%</td>
</tr>
<tr class="even">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">endpoint</td>
<td style="text-align: right;">69.97%</td>
<td style="text-align: right;">95.10%</td>
<td style="text-align: right;">66.54%</td>
<td style="text-align: right;">75.89%</td>
<td style="text-align: right;">95.45%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>endpoint</code> sits between the two by construction, and that is the whole design: it keeps <code>nearest</code>’s naming rule and adds <code>trend</code>’s willingness to stay silent. It answers +12.47 pp more departures than production for -0.84 pp of accuracy.</p>
<p>Whether that trade is worth taking is a policy question rather than a technical one. A flight list treated as authoritative may prefer production’s caution; an analysis needing volume may not.</p>
<p>Arrivals remain weaker than departures on every measure, as in all previous versions. A departure’s first sample is at or near a stand, with the aircraft stationary shortly before. An arrival’s last sample is more often a loss of reception during descent than a landing, and can be anywhere on the approach.</p>
</section>
<section id="sec-radius" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sec-radius"><span class="header-section-number">5</span> What a distance cap costs</h2>
<p>The sweep varies the detection radius and the abstention height independently, 126 combinations in all, over the cached candidates. Height runs from on-ground-only to 40,000 ft above field elevation — past typical cruise, so the curve is followed to where it flattens — plus an unrestricted case as the limit.</p>
<p>Both measures are plotted for both roles, because the two axes do not merely differ in strength — they pull in opposite directions, and a coverage-only view hides that entirely.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/sweep-plot-cov-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Coverage against abstention height, one line per detection radius. The shape of the curve belongs to the height axis in both panels; the radius only sets how much of it is reachable, and arrivals need more of it than departures. At 15,000 ft a 20 NM radius still leaves +1.32 pp of departure coverage and +3.61 pp of arrival coverage on the table against the full 110 NM reach, while at 40 NM both are within half a point of it.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/sweep-plot-acc-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Accuracy against abstention height, same axes. This is the figure the coverage plot hides. Accuracy peaks close to the ground – at 40 NM, departures at 2,000 ft and arrivals at 500 ft – and every foot admitted above that is bought with correctness: -1.00 pp for departures by 15,000 ft, -3.47 pp for arrivals. The radius, which barely touches coverage above 40 NM, spreads accuracy at 15,000 ft by +1.32 pp for departures and +3.97 pp for arrivals.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Detection radius at a fixed 15,000 ft abstention height. <em>ovr</em> is overall correctness, coverage x accuracy. Coverage saturates by about 30 NM for departures and 40 NM for arrivals; beyond that a wider radius trades accuracy for almost no coverage, and overall correctness flattens rather than turning – the radius has no interior optimum on this axis, unlike the height (<a href="#sec-accuracy-sweep" class="quarto-xref">Section&nbsp;5.1</a>).</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Max radius</th>
<th style="text-align: right;">ADEP cov</th>
<th style="text-align: right;">ADEP acc</th>
<th style="text-align: right;">ADEP ovr</th>
<th style="text-align: right;">ADES cov</th>
<th style="text-align: right;">ADES acc</th>
<th style="text-align: right;">ADES ovr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">5 NM</td>
<td style="text-align: right;">71.62%</td>
<td style="text-align: right;">99.07%</td>
<td style="text-align: right;">70.95%</td>
<td style="text-align: right;">58.79%</td>
<td style="text-align: right;">98.64%</td>
<td style="text-align: right;">57.99%</td>
</tr>
<tr class="even">
<td style="text-align: left;">10 NM</td>
<td style="text-align: right;">76.74%</td>
<td style="text-align: right;">98.77%</td>
<td style="text-align: right;">75.79%</td>
<td style="text-align: right;">62.36%</td>
<td style="text-align: right;">97.87%</td>
<td style="text-align: right;">61.03%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM</td>
<td style="text-align: right;">80.07%</td>
<td style="text-align: right;">98.44%</td>
<td style="text-align: right;">78.82%</td>
<td style="text-align: right;">66.78%</td>
<td style="text-align: right;">96.65%</td>
<td style="text-align: right;">64.54%</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 NM</td>
<td style="text-align: right;">80.96%</td>
<td style="text-align: right;">98.16%</td>
<td style="text-align: right;">79.47%</td>
<td style="text-align: right;">69.10%</td>
<td style="text-align: right;">95.63%</td>
<td style="text-align: right;">66.08%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM</td>
<td style="text-align: right;">81.20%</td>
<td style="text-align: right;">97.98%</td>
<td style="text-align: right;">79.55%</td>
<td style="text-align: right;">69.97%</td>
<td style="text-align: right;">95.10%</td>
<td style="text-align: right;">66.54%</td>
</tr>
<tr class="even">
<td style="text-align: left;">60 NM</td>
<td style="text-align: right;">81.36%</td>
<td style="text-align: right;">97.79%</td>
<td style="text-align: right;">79.56%</td>
<td style="text-align: right;">70.29%</td>
<td style="text-align: right;">94.80%</td>
<td style="text-align: right;">66.63%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80 NM</td>
<td style="text-align: right;">81.39%</td>
<td style="text-align: right;">97.75%</td>
<td style="text-align: right;">79.57%</td>
<td style="text-align: right;">70.38%</td>
<td style="text-align: right;">94.69%</td>
<td style="text-align: right;">66.64%</td>
</tr>
<tr class="even">
<td style="text-align: left;">100 NM</td>
<td style="text-align: right;">81.40%</td>
<td style="text-align: right;">97.75%</td>
<td style="text-align: right;">79.57%</td>
<td style="text-align: right;">70.38%</td>
<td style="text-align: right;">94.67%</td>
<td style="text-align: right;">66.64%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">110 NM</td>
<td style="text-align: right;">81.40%</td>
<td style="text-align: right;">97.75%</td>
<td style="text-align: right;">79.57%</td>
<td style="text-align: right;">70.38%</td>
<td style="text-align: right;">94.67%</td>
<td style="text-align: right;">66.64%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>A cap costs almost nothing.</strong> Going from 40 NM to the full 110 NM reach changes departure coverage by +0.20 pp and accuracy by -0.23 pp.&nbsp;The useful range is 20–40 NM; below that coverage falls away quickly, above it nothing happens.</p>
<p>Every radius at or above 20 NM traces effectively the same coverage curve: at 5,000 ft they span 74.39% to 74.58%, about a point across a five-fold change. Only the 5 NM and 10 NM lines fall away, and they fall further as the height threshold rises, because a tight radius costs more once more of the sky is admitted.</p>
<p><strong>Height is the parameter that matters.</strong> At 40 NM, departure coverage runs from 31.21% with the on-ground-only rule, through 67.05% at 2,000 ft, to 81.20% at 15,000 ft. That is over fifty points from one axis against a fraction of a point from the other.</p>
<p>Arrivals behave the same way with less room: from 36.01% to 69.97% over the same range. They also saturate later in radius — at 15,000 ft a 20 NM cap costs departures +1.32 pp of coverage but arrivals +3.61 pp, because an arrival’s last recorded sample is further from the aerodrome than a departure’s first.</p>
<p>Two endpoints of the sweep serve as sanity checks, and both behave as they should: at height 0 the rule reduces to “endpoint on the ground” and gives 31.21%, close to what a surface-samples-only method achieved in earlier versions; with height unrestricted and a wide radius it reaches 91.41%, close to <code>nearest</code>’s 91.68%, which is what it should converge to.</p>
<p><strong>The curve does flatten, and the grid now reaches the flat part.</strong> At 40 NM the last measured height is within +0.06 pp of the unrestricted case for departures and +0.36 pp for arrivals, so a threshold at cruise level is indistinguishable from no threshold at all. The steepest remaining step is between 30,000 and 35,000 ft — +4.08 pp of arrival coverage in one 5,000 ft band, which is where first and last contact at cruise gets admitted.</p>
<section id="sec-accuracy-sweep" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="sec-accuracy-sweep"><span class="header-section-number">5.1</span> What the coverage view hides</h3>
<p>Read on accuracy, the same grid tells a different story, and the two together are what actually determines an operating point.</p>
<p><strong>Accuracy peaks near the ground, then declines.</strong> At 40 NM, departure accuracy is highest at 2,000 ft (98.98%) and arrival accuracy at 500 ft (98.57%). By 15,000 ft they have given up -1.00 pp and -3.47 pp respectively. Every foot of extra height admits endpoints that are further into the climb or descent, and those are exactly the endpoints most likely to sit nearer a neighbouring aerodrome than the real one.</p>
<p><strong>Arrivals pay roughly three times as much for the same height.</strong> That ratio is the single clearest statement of why this study has never recommended changing the arrivals algorithm: the same parameter that is nearly free for departures is expensive for arrivals, so one operating point cannot serve both well.</p>
<p><strong>The radius matters for accuracy even where it does not for coverage.</strong> Above 40 NM a wider radius buys essentially no coverage, but it keeps costing accuracy: at 15,000 ft, going from 5 NM to 110 NM costs -1.32 pp of departure accuracy and -3.97 pp of arrival accuracy. This is the real argument for a cap. Version 4 justified one on the grounds that it costs almost no coverage; the accuracy view shows it is mildly <em>positive</em> rather than merely harmless.</p>
<p><strong>Overall correctness is what reconciles them, and it has a maximum.</strong> Coverage rises steeply with height while accuracy falls gently, so their product rises for a long way: at 40 NM departure overall correctness runs from 66.36% at 2,000 ft to 79.55% at 15,000 ft. But it does not rise forever. It peaks at <strong>25,000 ft</strong> (80.41%) and declines above that, as the accuracy loss finally outruns the coverage gain.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Version 4.2 got this wrong, and the extended grid is why
</div>
</div>
<div class="callout-body-container callout-body">
<p>Version 4.2 stated that the product “keeps rising for departures across the whole range”. That was true of the range it measured — the sweep stopped at 20,000 ft, below the turning point — and false of the parameter. Extending the grid to 40,000 ft was what exposed it. The claim is withdrawn.</p>
</div>
</div>
<p>The maximum is shallow, which is the practical point: 80.41% at its peak against 79.55% at the recommended 15,000 ft, a difference of +0.86 pp.&nbsp;Buying it costs -1.67 pp of accuracy, so the recommendation does not move.</p>
<p>Arrivals never turn over inside the grid: overall correctness is still climbing at 40,000 ft (69.26% against 66.54% at 15,000 ft). Arrival coverage is so far from its ceiling that admitting more of it still pays, which is the same asymmetry once more.</p>
<p>A user who cares about a trustworthy label rather than a complete one should ignore all of this and read the accuracy panel, where the optimum sits near the ground.</p>
</section>
</section>
<section id="sec-penalty" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-penalty"><span class="header-section-number">6</span> Preferring aerodromes with scheduled service</h2>
<p>Version 3 found that the most frequent departure errors formed one pattern: a scheduled civil airport losing to an adjacent military airfield — Izmir to Çiğli Airbase, Naples to Grazzanise, Cagliari to Decimomannu, Catania to Sigonella, Gdańsk to Cewice, all between 7 and 25 NM apart.</p>
<p>The mechanism is straightforward. With 5 s sampling a departing aircraft’s first recorded fix is already into the climb and displaced along the departure track. Where a military field lies between the airport and that track, it is genuinely the nearest aerodrome — the rule is not malfunctioning, it is answering the question it was asked.</p>
<p>Aviation knowledge resolves it without new data: a commercial flight almost certainly used the aerodrome with scheduled service. Candidates are therefore ranked on <strong>effective distance</strong> — true distance plus a fixed penalty for aerodromes without scheduled service — so a military field must be <em>clearly</em> nearest rather than merely nearest.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Scheduled-service penalty at 40 NM and 15,000 ft. <em>ovr</em> is overall correctness. A penalty of 0 reproduces the unbiased ranking exactly and is the control.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Penalty</th>
<th style="text-align: right;">ADEP cov</th>
<th style="text-align: right;">ADEP acc</th>
<th style="text-align: right;">ADEP ovr</th>
<th style="text-align: right;">ADES cov</th>
<th style="text-align: right;">ADES acc</th>
<th style="text-align: right;">ADES ovr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0 NM</td>
<td style="text-align: right;">81.20%</td>
<td style="text-align: right;">97.31%</td>
<td style="text-align: right;">79.02%</td>
<td style="text-align: right;">70.00%</td>
<td style="text-align: right;">93.85%</td>
<td style="text-align: right;">65.70%</td>
</tr>
<tr class="even">
<td style="text-align: left;">5 NM</td>
<td style="text-align: right;">81.20%</td>
<td style="text-align: right;">97.72%</td>
<td style="text-align: right;">79.35%</td>
<td style="text-align: right;">69.99%</td>
<td style="text-align: right;">94.31%</td>
<td style="text-align: right;">66.01%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10 NM</td>
<td style="text-align: right;">81.20%</td>
<td style="text-align: right;">97.98%</td>
<td style="text-align: right;">79.55%</td>
<td style="text-align: right;">69.97%</td>
<td style="text-align: right;">95.10%</td>
<td style="text-align: right;">66.54%</td>
</tr>
<tr class="even">
<td style="text-align: left;">15 NM</td>
<td style="text-align: right;">81.19%</td>
<td style="text-align: right;">97.90%</td>
<td style="text-align: right;">79.49%</td>
<td style="text-align: right;">69.92%</td>
<td style="text-align: right;">94.88%</td>
<td style="text-align: right;">66.35%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM</td>
<td style="text-align: right;">81.20%</td>
<td style="text-align: right;">97.68%</td>
<td style="text-align: right;">79.32%</td>
<td style="text-align: right;">69.91%</td>
<td style="text-align: right;">94.80%</td>
<td style="text-align: right;">66.27%</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 NM</td>
<td style="text-align: right;">81.19%</td>
<td style="text-align: right;">97.59%</td>
<td style="text-align: right;">79.23%</td>
<td style="text-align: right;">69.82%</td>
<td style="text-align: right;">94.84%</td>
<td style="text-align: right;">66.22%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The gain is <strong>+0.67 pp of departure accuracy</strong> and <strong>+1.24 pp of arrival accuracy</strong>, for a coverage change of -0.01 pp. Overall correctness moves with it — +0.54 pp and +0.84 pp — which is what makes this the one parameter in the study with no trade attached.</p>
<p>Two features make this trustworthy rather than a lucky constant. The control at penalty 0 reproduces the unbiased ranking, so the effect is attributable. And the curve <strong>peaks and turns</strong> — accuracy is best around 10 NM and declines above it. A penalty that merely favoured larger aerodromes would improve monotonically; one that corrects a specific bias should overshoot, and this does.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>It is not free — the cost is a mirror error
</div>
</div>
<div class="callout-body-container callout-body">
<p>Version 3 measured what this preference breaks: genuine movements at non-scheduled aerodromes get pulled to the nearby hub — Biggin Hill to London City, Northolt to Heathrow. In that analysis the mirror error became the <strong>largest single class of remaining departure error</strong>, at roughly 59% of them.</p>
<p>The net is favourable, and the accuracy figures above include the cost. But a flight list built this way will systematically under-report movements at non-scheduled aerodromes, and anyone analysing general aviation or military traffic should know that before using it.</p>
</div>
</div>
</section>
<section id="sec-ooa" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="sec-ooa"><span class="header-section-number">7</span> Out-of-area</h2>
<p>A flight from Dubai to Amsterdam has a departure aerodrome that no European ADS-B feed can name: the aircraft entered the observed area already airborne. Scoring that as a detection failure understates every method. Treating “out of area” as an answer is an accounting correction, not a detection improvement.</p>
<section id="how-it-is-derived" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="how-it-is-derived"><span class="header-section-number">7.1</span> How it is derived</h3>
<p><strong>On the ground-truth side</strong>, an aerodrome is relabelled <code>OOA</code> when its coordinates fall outside the ingestion bounding box, <strong>or</strong> when its ICAO code does not resolve in OurAirports. The unresolvable codes are overwhelmingly non-European, and a code that cannot be located is one no trajectory endpoint could have been matched to. This is what puts prediction and truth in the same alphabet.</p>
<p><strong>On the prediction side</strong>, an endpoint within 30 NM of the bounding box edge is labelled out-of-area. The longitude margin is scaled by <span class="math inline">\(1/\cos(\text{lat})\)</span>: a degree of longitude shrinks toward the pole, so an unscaled margin would be roughly twice as strict in northern Norway as in the Canaries.</p>
<p><strong>Precedence is aerodrome first, border second.</strong> The opposite order looks equivalent and is not — version 3 found Ponta Delgada, which sits about 8 NM inside the western edge, having its departures labelled out-of-area with the aircraft still on the runway. Being near the boundary means “out of area” only when there is nothing better to say.</p>
<p><strong>The border test carries no height condition.</strong> A flight leaving the observed area is at cruise level by definition, so any height cut-off would reject exactly the endpoints the branch exists to catch.</p>
</section>
<section id="what-it-does-to-the-numbers" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="what-it-does-to-the-numbers"><span class="header-section-number">7.2</span> What it does to the numbers</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Out-of-area for departures. Only <code>endpoint</code> emits the label; the others never do, so their recall is zero by construction.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mode</th>
<th style="text-align: right;">truly OOA</th>
<th style="text-align: right;">labelled OOA</th>
<th style="text-align: right;">OOA recall</th>
<th style="text-align: right;">OOA precision</th>
<th style="text-align: right;">headline acc</th>
<th style="text-align: right;">in-area acc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">trend</td>
<td style="text-align: right;">8.30%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">98.82%</td>
<td style="text-align: right;">98.95%</td>
</tr>
<tr class="even">
<td style="text-align: left;">nearest</td>
<td style="text-align: right;">8.30%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">87.78%</td>
<td style="text-align: right;">91.17%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">endpoint</td>
<td style="text-align: right;">8.30%</td>
<td style="text-align: right;">0.74%</td>
<td style="text-align: right;">7.94%</td>
<td style="text-align: right;">89.44%</td>
<td style="text-align: right;">97.98%</td>
<td style="text-align: right;">98.41%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>truly OOA</code> is a property of the sample, not of the method, so it must be identical across all three rows — that it is confirms the decomposition is being computed correctly rather than being a per-method artefact.</p>
<p>The gap between headline and in-area accuracy shows how much out-of-area labelling contributes. It is small here, which is the honest reading: the mechanism is right but the geometric test catches only part of what is there. Version 3 measured this directly at <strong>92–94% precision against 10–15% recall</strong> — when the rule fires it is almost always correct, but it rarely fires. An inbound flight’s first recorded sample appears wherever a receiver happens to catch it, which is usually well inside the boundary rather than at it.</p>
<p><strong>The concept is right and the instrument is wrong.</strong> A phase-based test would fit the physics better: a track whose first sample is already in the cruise, neither near an aerodrome nor descending toward one, has an origin outside the observed area regardless of where it sits. That is the clearest single improvement available and is not implemented here.</p>
</section>
</section>
<section id="sec-crosscheck" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="sec-crosscheck"><span class="header-section-number">8</span> Cross-check against the reference</h2>
<p>Flight-level accuracy can hide errors that cancel: a departure misattributed from A to B leaves both counts wrong and the total right. Movement counts per aerodrome are what an operational user reads, so they are checked separately.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Movement counts against Network Manager, from the <code>endpoint</code> flight list at 40 NM detection radius, 15,000 ft abstention height, 10 NM scheduled-service penalty. A count ratio below 1 is an undercount. The second ratio drops the out-of-area bucket, whose own recall is poor (<a href="#sec-ooa" class="quarto-xref">Section&nbsp;7</a>) and which otherwise carries the shortfall of every unlabelled flight.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Movements</th>
<th style="text-align: right;">Aerodromes</th>
<th style="text-align: right;">Count ratio</th>
<th style="text-align: right;">Excl. OOA</th>
<th style="text-align: right;">Median recall</th>
<th style="text-align: right;">Median recall, 50+ movements</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">departures</td>
<td style="text-align: right;">824</td>
<td style="text-align: right;">0.810</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">80.00%</td>
<td style="text-align: right;">97.35%</td>
</tr>
<tr class="even">
<td style="text-align: left;">arrivals</td>
<td style="text-align: right;">805</td>
<td style="text-align: right;">0.695</td>
<td style="text-align: right;">0.756</td>
<td style="text-align: right;">60.00%</td>
<td style="text-align: right;">84.08%</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="sec-per-type" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="sec-per-type"><span class="header-section-number">8.1</span> By class of aerodrome</h3>
<p>Every headline figure averages over populations that behave nothing like each other. The detection reference holds <strong>large and medium aerodromes only</strong>, so flights whose true aerodrome is a small field or a heliport cannot be named correctly at any radius or height. Grouping ground truth by its OurAirports class separates that from detection skill.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Coverage and accuracy by the class of the <em>ground-truth</em> aerodrome, from the <code>endpoint</code> flight list at 40 NM detection radius, 15,000 ft abstention height, 10 NM scheduled-service penalty. Classes are OurAirports types. The detection reference contains large and medium aerodromes only.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Movements</th>
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Aerodromes</th>
<th style="text-align: right;">Flights</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">large airport</td>
<td style="text-align: right;">331</td>
<td style="text-align: right;">80,683</td>
<td style="text-align: right;">76.11%</td>
<td style="text-align: right;">96.27%</td>
<td style="text-align: right;">73.27%</td>
</tr>
<tr class="even">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">out of area</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7,964</td>
<td style="text-align: right;">5.12%</td>
<td style="text-align: right;">37.99%</td>
<td style="text-align: right;">1.95%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">medium airport</td>
<td style="text-align: right;">346</td>
<td style="text-align: right;">5,983</td>
<td style="text-align: right;">74.88%</td>
<td style="text-align: right;">89.55%</td>
<td style="text-align: right;">67.06%</td>
</tr>
<tr class="even">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">small airport</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">57.67%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">arrivals</td>
<td style="text-align: left;">heliport</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">36.57%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">large airport</td>
<td style="text-align: right;">331</td>
<td style="text-align: right;">80,661</td>
<td style="text-align: right;">88.37%</td>
<td style="text-align: right;">99.14%</td>
<td style="text-align: right;">87.60%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">out of area</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7,892</td>
<td style="text-align: right;">12.34%</td>
<td style="text-align: right;">64.37%</td>
<td style="text-align: right;">7.94%</td>
</tr>
<tr class="even">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">medium airport</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">6,069</td>
<td style="text-align: right;">78.22%</td>
<td style="text-align: right;">92.21%</td>
<td style="text-align: right;">72.12%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">small airport</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">361</td>
<td style="text-align: right;">49.58%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">departures</td>
<td style="text-align: left;">heliport</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">39.10%</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">0.00%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Small aerodromes and heliports are answered confidently and wrongly, every time.</strong> Accuracy on both classes is exactly zero, on 49.58% coverage for small airports and 39.10% for heliports. That is not a near-miss rate: the reference cannot name these aerodromes, so when the endpoint happens to fall within 40 NM of some large or medium field below 15,000 ft, the rule names that one instead. Across both roles, 483 of 980 such flights get an answer and none of them are right.</p>
<p>The absolute cost is small — under half a point of the sample — but the shape of the error matters more than its size. <strong>These are not abstentions; they are false statements</strong>, and nothing in the output distinguishes them from the 99.14% of correct large-airport departures. Two fixes are available and neither is implemented here: extend the reference to small aerodromes so they can be named, or make abstention aware of what the reference contains, so an endpoint nearest to an aerodrome the reference omits produces silence rather than its neighbour.</p>
<p><strong>Between the classes the reference does hold, the difference is real but ordinary.</strong> Departures at large airports run 88.37% coverage at 99.14% accuracy, against 78.22% and 92.21% at medium ones. Since large airports are 84.80% of the sample, the headline figures are very close to the large-airport figures and should not be read as applying uniformly.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The 100 busiest aerodromes by Network Manager departures, against the <code>endpoint</code> flight list at 40 NM detection radius, 15,000 ft abstention height, 10 NM scheduled-service penalty. Out-of-area is excluded – it is not an aerodrome and is reported separately in <a href="#sec-ooa" class="quarto-xref">Section&nbsp;7</a>. <em>Count ratio</em> is OPDI movements divided by Network Manager movements, so it can sit near 1 even when the individual flights are wrong; <em>recall</em> is the share of Network Manager departures OPDI put at this aerodrome, and is the stricter measure.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Aerodrome</th>
<th style="text-align: right;">NM movements</th>
<th style="text-align: right;">OPDI assigned</th>
<th style="text-align: right;">Count ratio</th>
<th style="text-align: right;">Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LTFM</td>
<td style="text-align: right;">2,282</td>
<td style="text-align: right;">2,211</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">96.49%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EHAM</td>
<td style="text-align: right;">2,148</td>
<td style="text-align: right;">2,165</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">99.77%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDF</td>
<td style="text-align: right;">2,094</td>
<td style="text-align: right;">2,087</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.43%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFPG</td>
<td style="text-align: right;">2,084</td>
<td style="text-align: right;">2,071</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.85%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGLL</td>
<td style="text-align: right;">2,001</td>
<td style="text-align: right;">2,024</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">99.35%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEMD</td>
<td style="text-align: right;">1,773</td>
<td style="text-align: right;">1,761</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.21%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEBL</td>
<td style="text-align: right;">1,591</td>
<td style="text-align: right;">1,582</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.25%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDDM</td>
<td style="text-align: right;">1,573</td>
<td style="text-align: right;">1,567</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.43%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIRF</td>
<td style="text-align: right;">1,449</td>
<td style="text-align: right;">1,445</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.65%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTAI</td>
<td style="text-align: right;">1,435</td>
<td style="text-align: right;">1,387</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">96.17%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEPA</td>
<td style="text-align: right;">1,417</td>
<td style="text-align: right;">1,401</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.80%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LGAV</td>
<td style="text-align: right;">1,306</td>
<td style="text-align: right;">1,280</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">95.94%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGKK</td>
<td style="text-align: right;">1,223</td>
<td style="text-align: right;">1,218</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.43%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EIDW</td>
<td style="text-align: right;">1,185</td>
<td style="text-align: right;">1,166</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">98.14%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LSZH</td>
<td style="text-align: right;">1,178</td>
<td style="text-align: right;">1,168</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.81%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LOWW</td>
<td style="text-align: right;">1,156</td>
<td style="text-align: right;">1,142</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.10%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EKCH</td>
<td style="text-align: right;">1,140</td>
<td style="text-align: right;">1,133</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.30%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTFJ</td>
<td style="text-align: right;">1,137</td>
<td style="text-align: right;">1,115</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">96.83%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LPPT</td>
<td style="text-align: right;">1,010</td>
<td style="text-align: right;">1,001</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.11%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFPO</td>
<td style="text-align: right;">992</td>
<td style="text-align: right;">990</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">98.99%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIMC</td>
<td style="text-align: right;">973</td>
<td style="text-align: right;">964</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.56%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ENGM</td>
<td style="text-align: right;">932</td>
<td style="text-align: right;">927</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.93%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGCC</td>
<td style="text-align: right;">926</td>
<td style="text-align: right;">902</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">97.41%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGSS</td>
<td style="text-align: right;">885</td>
<td style="text-align: right;">883</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.66%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPWA</td>
<td style="text-align: right;">875</td>
<td style="text-align: right;">874</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.43%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EBBR</td>
<td style="text-align: right;">872</td>
<td style="text-align: right;">886</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">99.66%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDB</td>
<td style="text-align: right;">870</td>
<td style="text-align: right;">864</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">97.70%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEMG</td>
<td style="text-align: right;">850</td>
<td style="text-align: right;">849</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.65%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ESSA</td>
<td style="text-align: right;">820</td>
<td style="text-align: right;">791</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">95.98%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDDL</td>
<td style="text-align: right;">758</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.15%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LFMN</td>
<td style="text-align: right;">707</td>
<td style="text-align: right;">695</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">98.02%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LSGG</td>
<td style="text-align: right;">680</td>
<td style="text-align: right;">688</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">99.41%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LKPR</td>
<td style="text-align: right;">667</td>
<td style="text-align: right;">659</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.20%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EFHK</td>
<td style="text-align: right;">659</td>
<td style="text-align: right;">660</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.09%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEAL</td>
<td style="text-align: right;">599</td>
<td style="text-align: right;">598</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.83%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LHBP</td>
<td style="text-align: right;">578</td>
<td style="text-align: right;">554</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">95.67%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGPH</td>
<td style="text-align: right;">577</td>
<td style="text-align: right;">569</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.61%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGGW</td>
<td style="text-align: right;">550</td>
<td style="text-align: right;">551</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.82%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDH</td>
<td style="text-align: right;">538</td>
<td style="text-align: right;">537</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">98.14%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCLP</td>
<td style="text-align: right;">520</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDK</td>
<td style="text-align: right;">515</td>
<td style="text-align: right;">502</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">97.28%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LLBG</td>
<td style="text-align: right;">513</td>
<td style="text-align: right;">509</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">97.66%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LPPR</td>
<td style="text-align: right;">513</td>
<td style="text-align: right;">508</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.83%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LROP</td>
<td style="text-align: right;">504</td>
<td style="text-align: right;">493</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">97.82%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEIB</td>
<td style="text-align: right;">495</td>
<td style="text-align: right;">490</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.99%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGBB</td>
<td style="text-align: right;">474</td>
<td style="text-align: right;">468</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.73%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIML</td>
<td style="text-align: right;">458</td>
<td style="text-align: right;">452</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.47%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LIME</td>
<td style="text-align: right;">453</td>
<td style="text-align: right;">450</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.34%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIRN</td>
<td style="text-align: right;">449</td>
<td style="text-align: right;">337</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">74.61%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFML</td>
<td style="text-align: right;">444</td>
<td style="text-align: right;">440</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.87%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDS</td>
<td style="text-align: right;">440</td>
<td style="text-align: right;">418</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">94.32%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LGIR</td>
<td style="text-align: right;">424</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.24%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIPZ</td>
<td style="text-align: right;">412</td>
<td style="text-align: right;">409</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.03%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFLL</td>
<td style="text-align: right;">411</td>
<td style="text-align: right;">417</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">97.81%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LPFR</td>
<td style="text-align: right;">405</td>
<td style="text-align: right;">399</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.52%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LYBE</td>
<td style="text-align: right;">394</td>
<td style="text-align: right;">391</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.73%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LICC</td>
<td style="text-align: right;">390</td>
<td style="text-align: right;">382</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">97.69%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTAC</td>
<td style="text-align: right;">381</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIPE</td>
<td style="text-align: right;">380</td>
<td style="text-align: right;">375</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.68%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LCLK</td>
<td style="text-align: right;">368</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">95.38%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPKK</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">348</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">96.39%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GMMN</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">387</td>
<td style="text-align: right;">1.07</td>
<td style="text-align: right;">87.78%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGGD</td>
<td style="text-align: right;">359</td>
<td style="text-align: right;">356</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.89%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEVC</td>
<td style="text-align: right;">355</td>
<td style="text-align: right;">341</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">96.06%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LFSB</td>
<td style="text-align: right;">354</td>
<td style="text-align: right;">354</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">98.59%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ENBR</td>
<td style="text-align: right;">349</td>
<td style="text-align: right;">366</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">98.28%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LTBJ</td>
<td style="text-align: right;">346</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">79.48%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGPF</td>
<td style="text-align: right;">344</td>
<td style="text-align: right;">328</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">93.60%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LGRP</td>
<td style="text-align: right;">340</td>
<td style="text-align: right;">334</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">95.88%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LMML</td>
<td style="text-align: right;">326</td>
<td style="text-align: right;">325</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.39%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GCTS</td>
<td style="text-align: right;">321</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCXO</td>
<td style="text-align: right;">319</td>
<td style="text-align: right;">367</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">96.24%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LATI</td>
<td style="text-align: right;">316</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LICJ</td>
<td style="text-align: right;">310</td>
<td style="text-align: right;">288</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">92.58%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EBCI</td>
<td style="text-align: right;">304</td>
<td style="text-align: right;">304</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">100.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIKF</td>
<td style="text-align: right;">297</td>
<td style="text-align: right;">331</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">98.99%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ELLX</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.32%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFBO</td>
<td style="text-align: right;">293</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.63%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LGTS</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">271</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">96.77%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GMMX</td>
<td style="text-align: right;">278</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">30.94%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEZL</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">99.27%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EVRA</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">271</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.90%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LTBS</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">219</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">80.22%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LBSF</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">62.13%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GCRR</td>
<td style="text-align: right;">269</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGNX</td>
<td style="text-align: right;">267</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.50%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPKT</td>
<td style="text-align: right;">259</td>
<td style="text-align: right;">249</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">96.14%</td>
</tr>
<tr class="even">
<td style="text-align: left;">HEGN</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGTB</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">199</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">61.87%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFRS</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">254</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">98.83%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDP</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">99.61%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EPGD</td>
<td style="text-align: right;">248</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">15.73%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LGKR</td>
<td style="text-align: right;">244</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">84.84%</td>
</tr>
<tr class="even">
<td style="text-align: left;">HECA</td>
<td style="text-align: right;">244</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">17.21%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGAA</td>
<td style="text-align: right;">239</td>
<td style="text-align: right;">240</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">100.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ENZV</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">174</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">67.80%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEBB</td>
<td style="text-align: right;">234</td>
<td style="text-align: right;">174</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">73.50%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFPB</td>
<td style="text-align: right;">230</td>
<td style="text-align: right;">230</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">98.70%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIEO</td>
<td style="text-align: right;">228</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">85.53%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LIBD</td>
<td style="text-align: right;">228</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The 100 busiest aerodromes by Network Manager arrivals, against the <code>endpoint</code> flight list at 40 NM detection radius, 15,000 ft abstention height, 10 NM scheduled-service penalty. Out-of-area is excluded – it is not an aerodrome and is reported separately in <a href="#sec-ooa" class="quarto-xref">Section&nbsp;7</a>. <em>Count ratio</em> is OPDI movements divided by Network Manager movements, so it can sit near 1 even when the individual flights are wrong; <em>recall</em> is the share of Network Manager arrivals OPDI put at this aerodrome, and is the stricter measure.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Aerodrome</th>
<th style="text-align: right;">NM movements</th>
<th style="text-align: right;">OPDI assigned</th>
<th style="text-align: right;">Count ratio</th>
<th style="text-align: right;">Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LTFM</td>
<td style="text-align: right;">2,258</td>
<td style="text-align: right;">1,647</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">72.85%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EHAM</td>
<td style="text-align: right;">2,136</td>
<td style="text-align: right;">1,766</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">82.49%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDF</td>
<td style="text-align: right;">2,091</td>
<td style="text-align: right;">1,609</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">76.66%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFPG</td>
<td style="text-align: right;">2,066</td>
<td style="text-align: right;">1,546</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">74.54%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGLL</td>
<td style="text-align: right;">1,986</td>
<td style="text-align: right;">1,183</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">57.85%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEMD</td>
<td style="text-align: right;">1,786</td>
<td style="text-align: right;">1,357</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">74.92%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEBL</td>
<td style="text-align: right;">1,597</td>
<td style="text-align: right;">1,411</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">88.17%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDDM</td>
<td style="text-align: right;">1,571</td>
<td style="text-align: right;">1,313</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">83.45%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LTAI</td>
<td style="text-align: right;">1,437</td>
<td style="text-align: right;">994</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">68.89%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEPA</td>
<td style="text-align: right;">1,436</td>
<td style="text-align: right;">1,386</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">96.24%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIRF</td>
<td style="text-align: right;">1,433</td>
<td style="text-align: right;">1,189</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">82.76%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LGAV</td>
<td style="text-align: right;">1,317</td>
<td style="text-align: right;">1,128</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">83.45%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGKK</td>
<td style="text-align: right;">1,220</td>
<td style="text-align: right;">994</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">81.39%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EIDW</td>
<td style="text-align: right;">1,188</td>
<td style="text-align: right;">965</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">81.14%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LSZH</td>
<td style="text-align: right;">1,160</td>
<td style="text-align: right;">978</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">83.97%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EKCH</td>
<td style="text-align: right;">1,152</td>
<td style="text-align: right;">1,007</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">87.41%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LOWW</td>
<td style="text-align: right;">1,145</td>
<td style="text-align: right;">896</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">78.17%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTFJ</td>
<td style="text-align: right;">1,138</td>
<td style="text-align: right;">925</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">80.67%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LPPT</td>
<td style="text-align: right;">1,001</td>
<td style="text-align: right;">764</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">76.32%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFPO</td>
<td style="text-align: right;">991</td>
<td style="text-align: right;">888</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">89.51%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIMC</td>
<td style="text-align: right;">967</td>
<td style="text-align: right;">757</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">77.56%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ENGM</td>
<td style="text-align: right;">940</td>
<td style="text-align: right;">877</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">92.66%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGCC</td>
<td style="text-align: right;">924</td>
<td style="text-align: right;">619</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">66.99%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGSS</td>
<td style="text-align: right;">888</td>
<td style="text-align: right;">773</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">86.49%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPWA</td>
<td style="text-align: right;">880</td>
<td style="text-align: right;">705</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">79.77%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EBBR</td>
<td style="text-align: right;">871</td>
<td style="text-align: right;">733</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">83.47%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEMG</td>
<td style="text-align: right;">861</td>
<td style="text-align: right;">789</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">91.64%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ESSA</td>
<td style="text-align: right;">841</td>
<td style="text-align: right;">709</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">83.83%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDB</td>
<td style="text-align: right;">840</td>
<td style="text-align: right;">763</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">89.88%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDDL</td>
<td style="text-align: right;">751</td>
<td style="text-align: right;">666</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">88.15%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LFMN</td>
<td style="text-align: right;">710</td>
<td style="text-align: right;">657</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">91.97%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LSGG</td>
<td style="text-align: right;">670</td>
<td style="text-align: right;">625</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">91.64%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EFHK</td>
<td style="text-align: right;">666</td>
<td style="text-align: right;">577</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">85.59%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LKPR</td>
<td style="text-align: right;">657</td>
<td style="text-align: right;">571</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">86.45%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEAL</td>
<td style="text-align: right;">599</td>
<td style="text-align: right;">572</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">95.49%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGPH</td>
<td style="text-align: right;">584</td>
<td style="text-align: right;">506</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">85.96%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LHBP</td>
<td style="text-align: right;">577</td>
<td style="text-align: right;">238</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">41.07%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGGW</td>
<td style="text-align: right;">552</td>
<td style="text-align: right;">479</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">86.41%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDH</td>
<td style="text-align: right;">532</td>
<td style="text-align: right;">488</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">90.04%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCLP</td>
<td style="text-align: right;">521</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LLBG</td>
<td style="text-align: right;">516</td>
<td style="text-align: right;">409</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">74.03%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LPPR</td>
<td style="text-align: right;">512</td>
<td style="text-align: right;">435</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">84.77%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDK</td>
<td style="text-align: right;">509</td>
<td style="text-align: right;">443</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">85.66%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEIB</td>
<td style="text-align: right;">509</td>
<td style="text-align: right;">493</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">96.66%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LROP</td>
<td style="text-align: right;">509</td>
<td style="text-align: right;">463</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">90.77%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGBB</td>
<td style="text-align: right;">466</td>
<td style="text-align: right;">388</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">83.26%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIML</td>
<td style="text-align: right;">465</td>
<td style="text-align: right;">445</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">94.62%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LIME</td>
<td style="text-align: right;">460</td>
<td style="text-align: right;">419</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">91.09%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LIRN</td>
<td style="text-align: right;">447</td>
<td style="text-align: right;">335</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">73.60%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFML</td>
<td style="text-align: right;">445</td>
<td style="text-align: right;">391</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">87.64%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EDDS</td>
<td style="text-align: right;">433</td>
<td style="text-align: right;">377</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">86.84%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LGIR</td>
<td style="text-align: right;">430</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LFLL</td>
<td style="text-align: right;">412</td>
<td style="text-align: right;">386</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">90.53%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LIPZ</td>
<td style="text-align: right;">409</td>
<td style="text-align: right;">370</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">89.98%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LPFR</td>
<td style="text-align: right;">407</td>
<td style="text-align: right;">392</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">96.31%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LYBE</td>
<td style="text-align: right;">395</td>
<td style="text-align: right;">342</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">86.33%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LICC</td>
<td style="text-align: right;">391</td>
<td style="text-align: right;">356</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">91.05%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LIPE</td>
<td style="text-align: right;">376</td>
<td style="text-align: right;">359</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">95.21%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LTAC</td>
<td style="text-align: right;">374</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LCLK</td>
<td style="text-align: right;">367</td>
<td style="text-align: right;">338</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">91.55%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGGD</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">303</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">84.17%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ENBR</td>
<td style="text-align: right;">357</td>
<td style="text-align: right;">356</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">93.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GMMN</td>
<td style="text-align: right;">357</td>
<td style="text-align: right;">336</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">71.99%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEVC</td>
<td style="text-align: right;">357</td>
<td style="text-align: right;">333</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">93.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPKK</td>
<td style="text-align: right;">356</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">70.22%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFSB</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">322</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">91.48%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LGRP</td>
<td style="text-align: right;">346</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">87.57%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGPF</td>
<td style="text-align: right;">346</td>
<td style="text-align: right;">299</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">85.55%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LTBJ</td>
<td style="text-align: right;">341</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">80.65%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LMML</td>
<td style="text-align: right;">326</td>
<td style="text-align: right;">310</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">94.79%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GCTS</td>
<td style="text-align: right;">323</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">21.98%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LATI</td>
<td style="text-align: right;">323</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GCXO</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">316</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">23.75%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LICJ</td>
<td style="text-align: right;">314</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">92.04%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EBCI</td>
<td style="text-align: right;">303</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">94.06%</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIKF</td>
<td style="text-align: right;">296</td>
<td style="text-align: right;">165</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">29.39%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ELLX</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">226</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">76.53%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFBO</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">278</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">95.17%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LGTS</td>
<td style="text-align: right;">281</td>
<td style="text-align: right;">264</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">93.95%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTBS</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">228</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">81.07%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GMMX</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">19.35%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EVRA</td>
<td style="text-align: right;">278</td>
<td style="text-align: right;">221</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">78.78%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEZL</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">255</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">92.39%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCRR</td>
<td style="text-align: right;">269</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LBSF</td>
<td style="text-align: right;">267</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">32.58%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDDP</td>
<td style="text-align: right;">261</td>
<td style="text-align: right;">224</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">84.67%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HEGN</td>
<td style="text-align: right;">258</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LFRS</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">237</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">92.22%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPKT</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">82.10%</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGTB</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">21.79%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EGNX</td>
<td style="text-align: right;">255</td>
<td style="text-align: right;">206</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">79.61%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LIEO</td>
<td style="text-align: right;">252</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">83.33%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LGKR</td>
<td style="text-align: right;">247</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">68.02%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EGAA</td>
<td style="text-align: right;">246</td>
<td style="text-align: right;">223</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">90.65%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EPGD</td>
<td style="text-align: right;">244</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">1.64%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ENZV</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">46.61%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEBB</td>
<td style="text-align: right;">235</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">16.17%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTFE</td>
<td style="text-align: right;">232</td>
<td style="text-align: right;">187</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">80.17%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HECA</td>
<td style="text-align: right;">231</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">34.20%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LIBD</td>
<td style="text-align: right;">229</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The error is an <strong>undercount</strong> rather than an overcount, which is the correctable direction: a systematic shortfall can be adjusted for, an inflated count cannot. Roughly six points of it are the out-of-area bucket rather than per-aerodrome detection failure — flights the method never labelled land nowhere, so they show up as missing movements at whichever aerodrome the truth names.</p>
<p>Recall also scales sharply with aerodrome size. Across the hundred busiest — 74.96% of all departures in the sample — the median is 98.24% and the quartiles are 95.60% and 99.04%, against a median of 80.00% over all 824 aerodromes with departures. The flight list is therefore substantially more complete at large aerodromes than small ones, which matters before comparing across aerodrome classes — and <a href="#sec-per-type" class="quarto-xref">Section&nbsp;8.1</a> says why.</p>
</section>
<section id="sec-outliers" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="sec-outliers"><span class="header-section-number">8.2</span> Busy aerodromes that fail outright</h3>
<p>Extending the listing from thirty rows to a hundred exposes something the shorter view could not: a handful of genuinely busy aerodromes where the method does not merely lose a few movements but fails almost completely.</p>
<p>29 of the two hundred rows above sit below 50% recall — 11 departure aerodromes and 18 arrival ones. They split cleanly into two kinds of failure:</p>
<ul>
<li><strong>Never seen</strong> (19 rows). Under a quarter of their flights get an answer at all: Gran Canaria departures return 24 answers against 520 movements, and Hurghada none at all. These cluster where ADS-B receiver coverage is thin — the Canaries, North Africa, the Caucasus, Anatolia. No detection rule can recover a flight with no low-altitude trajectory.</li>
<li><strong>Seen and misnamed</strong> (10 rows). The trajectory is there and the answer is wrong. Bilbao arrivals are answered 90.64% of the time and only 38 of 235 land on Bilbao.</li>
</ul>
<p>Tenerife North is the cleanest warning about reading count ratios. It is assigned 316 arrivals against 320 true ones — a count ratio of 0.99, which looks like a well-measured aerodrome — while its recall is 23.75%. Almost every movement it is credited with belongs somewhere else, and the totals cancel the error exactly as <a href="#sec-crosscheck" class="quarto-xref">Section&nbsp;8</a> warned they could.</p>
<p>Every aerodrome in both groups is a <code>large_airport</code> with scheduled service and is present in the detection reference, so neither failure is the reference gap of <a href="#sec-per-type" class="quarto-xref">Section&nbsp;8.1</a>. The first group is a data limitation and is not fixable here. The second is a detection failure at aerodromes large enough to matter, it is concentrated rather than scattered, and <strong>this study has not diagnosed it</strong> — it is the most promising lead the cross-check produces.</p>
</section>
</section>
<section id="sec-operating-point" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="sec-operating-point"><span class="header-section-number">9</span> Choosing the operating point</h2>
<p>The sections above establish how each parameter behaves. This one picks values, and argues for them in flights rather than in percentages — because a rate conceals the size of what is being traded. “−0.84 pp of accuracy” and “792 more wrong aerodromes in three days” are the same fact, and only one of them can be weighed against anything.</p>
<p>All counts are out of 95,116 ground-truth flights per role, over 2025-06-05 to 07. <em>Answered</em> is what the method labelled, <em>correct</em> is what it labelled right, <em>wrong</em> is what it labelled wrong, <em>silent</em> is what it declined. The last three columns compare against production (<code>trend</code>).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Departures: the parameter grid in rates and in flights, against production. Penalty fixed at 10 NM. <em>Gain:err</em> is extra correct labels per extra wrong label, against production.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameters</th>
<th style="text-align: right;">Cov</th>
<th style="text-align: right;">Acc</th>
<th style="text-align: right;">Ovr</th>
<th style="text-align: right;">Answered</th>
<th style="text-align: right;">Correct</th>
<th style="text-align: right;">Wrong</th>
<th style="text-align: right;">Silent</th>
<th style="text-align: right;">d correct</th>
<th style="text-align: right;">d wrong</th>
<th style="text-align: right;">Gain:err</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">trend (production)</td>
<td style="text-align: right;">68.72%</td>
<td style="text-align: right;">98.82%</td>
<td style="text-align: right;">67.91%</td>
<td style="text-align: right;">65,365</td>
<td style="text-align: right;">64,594</td>
<td style="text-align: right;">771</td>
<td style="text-align: right;">29,751</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">20 NM / 15,000 ft</td>
<td style="text-align: right;">80.07%</td>
<td style="text-align: right;">98.44%</td>
<td style="text-align: right;">78.82%</td>
<td style="text-align: right;">76,164</td>
<td style="text-align: right;">74,973</td>
<td style="text-align: right;">1,191</td>
<td style="text-align: right;">18,952</td>
<td style="text-align: right;">10,379</td>
<td style="text-align: right;">420</td>
<td style="text-align: right;">24.7:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30 NM / 15,000 ft</td>
<td style="text-align: right;">80.96%</td>
<td style="text-align: right;">98.16%</td>
<td style="text-align: right;">79.47%</td>
<td style="text-align: right;">77,003</td>
<td style="text-align: right;">75,587</td>
<td style="text-align: right;">1,416</td>
<td style="text-align: right;">18,113</td>
<td style="text-align: right;">10,993</td>
<td style="text-align: right;">645</td>
<td style="text-align: right;">17.0:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">40 NM / 15,000 ft</td>
<td style="text-align: right;">81.20%</td>
<td style="text-align: right;">97.98%</td>
<td style="text-align: right;">79.55%</td>
<td style="text-align: right;">77,230</td>
<td style="text-align: right;">75,667</td>
<td style="text-align: right;">1,563</td>
<td style="text-align: right;">17,886</td>
<td style="text-align: right;">11,073</td>
<td style="text-align: right;">792</td>
<td style="text-align: right;">14.0:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM / 20,000 ft</td>
<td style="text-align: right;">80.53%</td>
<td style="text-align: right;">98.11%</td>
<td style="text-align: right;">79.01%</td>
<td style="text-align: right;">76,593</td>
<td style="text-align: right;">75,148</td>
<td style="text-align: right;">1,445</td>
<td style="text-align: right;">18,523</td>
<td style="text-align: right;">10,554</td>
<td style="text-align: right;">674</td>
<td style="text-align: right;">15.7:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 NM / 20,000 ft</td>
<td style="text-align: right;">81.86%</td>
<td style="text-align: right;">97.65%</td>
<td style="text-align: right;">79.94%</td>
<td style="text-align: right;">77,863</td>
<td style="text-align: right;">76,032</td>
<td style="text-align: right;">1,831</td>
<td style="text-align: right;">17,253</td>
<td style="text-align: right;">11,438</td>
<td style="text-align: right;">1,060</td>
<td style="text-align: right;">10.8:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 20,000 ft</td>
<td style="text-align: right;">82.44%</td>
<td style="text-align: right;">97.34%</td>
<td style="text-align: right;">80.24%</td>
<td style="text-align: right;">78,411</td>
<td style="text-align: right;">76,322</td>
<td style="text-align: right;">2,089</td>
<td style="text-align: right;">16,705</td>
<td style="text-align: right;">11,728</td>
<td style="text-align: right;">1,318</td>
<td style="text-align: right;">8.9:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">20 NM / 25,000 ft</td>
<td style="text-align: right;">80.80%</td>
<td style="text-align: right;">97.80%</td>
<td style="text-align: right;">79.02%</td>
<td style="text-align: right;">76,852</td>
<td style="text-align: right;">75,162</td>
<td style="text-align: right;">1,690</td>
<td style="text-align: right;">18,264</td>
<td style="text-align: right;">10,568</td>
<td style="text-align: right;">919</td>
<td style="text-align: right;">11.5:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30 NM / 25,000 ft</td>
<td style="text-align: right;">82.41%</td>
<td style="text-align: right;">97.06%</td>
<td style="text-align: right;">79.98%</td>
<td style="text-align: right;">78,382</td>
<td style="text-align: right;">76,078</td>
<td style="text-align: right;">2,304</td>
<td style="text-align: right;">16,734</td>
<td style="text-align: right;">11,484</td>
<td style="text-align: right;">1,533</td>
<td style="text-align: right;">7.5:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">40 NM / 25,000 ft</td>
<td style="text-align: right;">83.50%</td>
<td style="text-align: right;">96.31%</td>
<td style="text-align: right;">80.41%</td>
<td style="text-align: right;">79,419</td>
<td style="text-align: right;">76,487</td>
<td style="text-align: right;">2,932</td>
<td style="text-align: right;">15,697</td>
<td style="text-align: right;">11,893</td>
<td style="text-align: right;">2,161</td>
<td style="text-align: right;">5.5:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM / 30,000 ft</td>
<td style="text-align: right;">81.13%</td>
<td style="text-align: right;">97.40%</td>
<td style="text-align: right;">79.02%</td>
<td style="text-align: right;">77,168</td>
<td style="text-align: right;">75,165</td>
<td style="text-align: right;">2,003</td>
<td style="text-align: right;">17,948</td>
<td style="text-align: right;">10,571</td>
<td style="text-align: right;">1,232</td>
<td style="text-align: right;">8.6:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 NM / 30,000 ft</td>
<td style="text-align: right;">83.09%</td>
<td style="text-align: right;">96.26%</td>
<td style="text-align: right;">79.99%</td>
<td style="text-align: right;">79,035</td>
<td style="text-align: right;">76,083</td>
<td style="text-align: right;">2,952</td>
<td style="text-align: right;">16,081</td>
<td style="text-align: right;">11,489</td>
<td style="text-align: right;">2,181</td>
<td style="text-align: right;">5.3:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 30,000 ft</td>
<td style="text-align: right;">84.44%</td>
<td style="text-align: right;">95.21%</td>
<td style="text-align: right;">80.39%</td>
<td style="text-align: right;">80,317</td>
<td style="text-align: right;">76,467</td>
<td style="text-align: right;">3,850</td>
<td style="text-align: right;">14,799</td>
<td style="text-align: right;">11,873</td>
<td style="text-align: right;">3,079</td>
<td style="text-align: right;">3.9:1</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals: the same grid. Note that most cells produce <em>fewer</em> correct labels than production while adding wrong ones. Penalty fixed at 10 NM.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameters</th>
<th style="text-align: right;">Cov</th>
<th style="text-align: right;">Acc</th>
<th style="text-align: right;">Ovr</th>
<th style="text-align: right;">Answered</th>
<th style="text-align: right;">Correct</th>
<th style="text-align: right;">Wrong</th>
<th style="text-align: right;">Silent</th>
<th style="text-align: right;">d correct</th>
<th style="text-align: right;">d wrong</th>
<th style="text-align: right;">Gain:err</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">trend (production)</td>
<td style="text-align: right;">68.06%</td>
<td style="text-align: right;">97.87%</td>
<td style="text-align: right;">66.61%</td>
<td style="text-align: right;">64,738</td>
<td style="text-align: right;">63,361</td>
<td style="text-align: right;">1,377</td>
<td style="text-align: right;">30,378</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">20 NM / 15,000 ft</td>
<td style="text-align: right;">66.78%</td>
<td style="text-align: right;">96.65%</td>
<td style="text-align: right;">64.54%</td>
<td style="text-align: right;">63,514</td>
<td style="text-align: right;">61,387</td>
<td style="text-align: right;">2,127</td>
<td style="text-align: right;">31,602</td>
<td style="text-align: right;">-1,974</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30 NM / 15,000 ft</td>
<td style="text-align: right;">69.10%</td>
<td style="text-align: right;">95.63%</td>
<td style="text-align: right;">66.08%</td>
<td style="text-align: right;">65,726</td>
<td style="text-align: right;">62,856</td>
<td style="text-align: right;">2,870</td>
<td style="text-align: right;">29,390</td>
<td style="text-align: right;">-505</td>
<td style="text-align: right;">1,493</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">40 NM / 15,000 ft</td>
<td style="text-align: right;">69.97%</td>
<td style="text-align: right;">95.10%</td>
<td style="text-align: right;">66.54%</td>
<td style="text-align: right;">66,551</td>
<td style="text-align: right;">63,287</td>
<td style="text-align: right;">3,264</td>
<td style="text-align: right;">28,565</td>
<td style="text-align: right;">-74</td>
<td style="text-align: right;">1,887</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM / 20,000 ft</td>
<td style="text-align: right;">67.42%</td>
<td style="text-align: right;">95.97%</td>
<td style="text-align: right;">64.70%</td>
<td style="text-align: right;">64,124</td>
<td style="text-align: right;">61,543</td>
<td style="text-align: right;">2,581</td>
<td style="text-align: right;">30,992</td>
<td style="text-align: right;">-1,818</td>
<td style="text-align: right;">1,204</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 NM / 20,000 ft</td>
<td style="text-align: right;">70.32%</td>
<td style="text-align: right;">94.24%</td>
<td style="text-align: right;">66.27%</td>
<td style="text-align: right;">66,883</td>
<td style="text-align: right;">63,032</td>
<td style="text-align: right;">3,851</td>
<td style="text-align: right;">28,233</td>
<td style="text-align: right;">-329</td>
<td style="text-align: right;">2,474</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 20,000 ft</td>
<td style="text-align: right;">71.47%</td>
<td style="text-align: right;">93.47%</td>
<td style="text-align: right;">66.81%</td>
<td style="text-align: right;">67,983</td>
<td style="text-align: right;">63,544</td>
<td style="text-align: right;">4,439</td>
<td style="text-align: right;">27,133</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">3,062</td>
<td style="text-align: right;">0.1:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">20 NM / 25,000 ft</td>
<td style="text-align: right;">67.91%</td>
<td style="text-align: right;">95.54%</td>
<td style="text-align: right;">64.88%</td>
<td style="text-align: right;">64,592</td>
<td style="text-align: right;">61,710</td>
<td style="text-align: right;">2,882</td>
<td style="text-align: right;">30,524</td>
<td style="text-align: right;">-1,651</td>
<td style="text-align: right;">1,505</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30 NM / 25,000 ft</td>
<td style="text-align: right;">71.09%</td>
<td style="text-align: right;">93.46%</td>
<td style="text-align: right;">66.45%</td>
<td style="text-align: right;">67,622</td>
<td style="text-align: right;">63,202</td>
<td style="text-align: right;">4,420</td>
<td style="text-align: right;">27,494</td>
<td style="text-align: right;">-159</td>
<td style="text-align: right;">3,043</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">40 NM / 25,000 ft</td>
<td style="text-align: right;">72.43%</td>
<td style="text-align: right;">92.51%</td>
<td style="text-align: right;">67.00%</td>
<td style="text-align: right;">68,889</td>
<td style="text-align: right;">63,728</td>
<td style="text-align: right;">5,161</td>
<td style="text-align: right;">26,227</td>
<td style="text-align: right;">367</td>
<td style="text-align: right;">3,784</td>
<td style="text-align: right;">0.1:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM / 30,000 ft</td>
<td style="text-align: right;">68.50%</td>
<td style="text-align: right;">95.04%</td>
<td style="text-align: right;">65.10%</td>
<td style="text-align: right;">65,156</td>
<td style="text-align: right;">61,923</td>
<td style="text-align: right;">3,233</td>
<td style="text-align: right;">29,960</td>
<td style="text-align: right;">-1,438</td>
<td style="text-align: right;">1,856</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 NM / 30,000 ft</td>
<td style="text-align: right;">71.96%</td>
<td style="text-align: right;">92.65%</td>
<td style="text-align: right;">66.67%</td>
<td style="text-align: right;">68,445</td>
<td style="text-align: right;">63,417</td>
<td style="text-align: right;">5,028</td>
<td style="text-align: right;">26,671</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">3,651</td>
<td style="text-align: right;">0.0:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 30,000 ft</td>
<td style="text-align: right;">73.55%</td>
<td style="text-align: right;">91.40%</td>
<td style="text-align: right;">67.23%</td>
<td style="text-align: right;">69,962</td>
<td style="text-align: right;">63,946</td>
<td style="text-align: right;">6,016</td>
<td style="text-align: right;">25,154</td>
<td style="text-align: right;">585</td>
<td style="text-align: right;">4,639</td>
<td style="text-align: right;">0.1:1</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="sec-op-dep" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="sec-op-dep"><span class="header-section-number">9.1</span> Departures: every cell wins, but the marginal return collapses</h3>
<p>Every cell in the table beats production. That is not the question. The question is what each successive loosening <em>buys</em>, and the answer is that it collapses.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Departures: each step of loosening, and its marginal return. <em>Marginal</em> is extra correct labels per extra wrong label for that step alone, not against production.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: right;">d correct</th>
<th style="text-align: right;">d wrong</th>
<th style="text-align: right;">Marginal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">production to 20 NM / 5,000 ft</td>
<td style="text-align: right;">5,366</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">206.38:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">20 NM / 5,000 ft to 20 NM / 8,000 ft</td>
<td style="text-align: right;">2,426</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">39.13:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM / 8,000 ft to 20 NM / 10,000 ft</td>
<td style="text-align: right;">1,295</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">13.78:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">20 NM / 10,000 ft to 20 NM / 15,000 ft</td>
<td style="text-align: right;">1,292</td>
<td style="text-align: right;">238</td>
<td style="text-align: right;">5.43:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 NM / 15,000 ft to 30 NM / 15,000 ft</td>
<td style="text-align: right;">614</td>
<td style="text-align: right;">225</td>
<td style="text-align: right;">2.73:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">30 NM / 15,000 ft to 40 NM / 15,000 ft</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">147</td>
<td style="text-align: right;">0.54:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 15,000 ft to 40 NM / 20,000 ft</td>
<td style="text-align: right;">655</td>
<td style="text-align: right;">526</td>
<td style="text-align: right;">1.25:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">40 NM / 20,000 ft to 40 NM / 25,000 ft</td>
<td style="text-align: right;">165</td>
<td style="text-align: right;">843</td>
<td style="text-align: right;">0.20:1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 25,000 ft to 40 NM / 30,000 ft</td>
<td style="text-align: right;">-20</td>
<td style="text-align: right;">918</td>
<td style="text-align: right;">loss</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Two readings of the same table. Against production, every cell looks excellent — the worst ratio in the grid is still better than three correct labels per error. Step by step, the picture inverts: the first move off production is nearly free, and by the wide-and-high end each additional correct label costs more than one additional error.</p>
<p>Note where the currently published operating point sits. Going from 30 NM to 40 NM at 15,000 ft adds 80 correct labels and 147 wrong ones. <strong>The published parameters are already past break-even</strong>, which the percentage view never showed because it is a 0.18 pp change in accuracy.</p>
</section>
<section id="sec-op-arr" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="sec-op-arr"><span class="header-section-number">9.2</span> Arrivals: nothing in the grid earns its place</h3>
<p>Arrivals invert the departure result completely. <strong>8 of the 12 cells produce fewer correct arrival labels than production</strong>, while every one of them produces more wrong ones. The cells that do gain correct labels buy them at a ruinous rate:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals: what each cell costs against production. Cells omitted from the ratio column produce fewer correct labels than production and so gain nothing to price.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Cell</th>
<th style="text-align: right;">d correct</th>
<th style="text-align: right;">d wrong</th>
<th style="text-align: right;">Errors per correct gained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">30 NM / 15,000 ft</td>
<td style="text-align: right;">-505</td>
<td style="text-align: right;">1,493</td>
<td style="text-align: right;">gains none</td>
</tr>
<tr class="even">
<td style="text-align: left;">40 NM / 15,000 ft</td>
<td style="text-align: right;">-74</td>
<td style="text-align: right;">1,887</td>
<td style="text-align: right;">gains none</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 20,000 ft</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">3,062</td>
<td style="text-align: right;">16.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">40 NM / 25,000 ft</td>
<td style="text-align: right;">367</td>
<td style="text-align: right;">3,784</td>
<td style="text-align: right;">10.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40 NM / 30,000 ft</td>
<td style="text-align: right;">585</td>
<td style="text-align: right;">4,639</td>
<td style="text-align: right;">7.9</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The best arrival cell in the entire grid, 40 NM / 30,000 ft, gains 585 correct labels and adds 4,639 wrong ones. There is no exchange rate under which that is a good trade. <strong><code>endpoint</code> should not replace <code>trend</code> for arrivals at any setting measured here</strong> — and <a href="#sec-hybrid" class="quarto-xref">Section&nbsp;10</a> asks why, and what could be done about it.</p>
</section>
<section id="sec-op-metrics" class="level3" data-number="9.3">
<h3 data-number="9.3" class="anchored" data-anchor-id="sec-op-metrics"><span class="header-section-number">9.3</span> Why no single metric can make this choice</h3>
<p>A natural instinct is to let one number decide. It cannot, and it is worth seeing why before trusting any headline figure.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Departures: the best cell in the whole grid under each metric taken alone.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Optimising</th>
<th style="text-align: left;">Parameters</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">coverage</td>
<td style="text-align: left;">110 NM / unrestricted</td>
<td style="text-align: right;">91.41%</td>
<td style="text-align: right;">87.91%</td>
<td style="text-align: right;">80.36%</td>
</tr>
<tr class="even">
<td style="text-align: left;">accuracy</td>
<td style="text-align: left;">5 NM / 2,000 ft</td>
<td style="text-align: right;">66.84%</td>
<td style="text-align: right;">99.24%</td>
<td style="text-align: right;">66.33%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">overall</td>
<td style="text-align: left;">80 NM / 30,000 ft</td>
<td style="text-align: right;">85.63%</td>
<td style="text-align: right;">94.19%</td>
<td style="text-align: right;">80.66%</td>
</tr>
<tr class="even">
<td style="text-align: left;">—</td>
<td style="text-align: left;">trend (production)</td>
<td style="text-align: right;">68.72%</td>
<td style="text-align: right;">98.82%</td>
<td style="text-align: right;">67.91%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">—</td>
<td style="text-align: left;">nearest (no abstention)</td>
<td style="text-align: right;">91.68%</td>
<td style="text-align: right;">87.78%</td>
<td style="text-align: right;">80.48%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Arrivals: the same. Note that no <code>endpoint</code> cell reaches <code>nearest</code>’s overall correctness.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Optimising</th>
<th style="text-align: left;">Parameters</th>
<th style="text-align: right;">Coverage</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">coverage</td>
<td style="text-align: left;">110 NM / unrestricted</td>
<td style="text-align: right;">87.75%</td>
<td style="text-align: right;">79.53%</td>
<td style="text-align: right;">69.79%</td>
</tr>
<tr class="even">
<td style="text-align: left;">accuracy</td>
<td style="text-align: left;">5 NM / 500 ft</td>
<td style="text-align: right;">52.03%</td>
<td style="text-align: right;">99.15%</td>
<td style="text-align: right;">51.59%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">overall</td>
<td style="text-align: left;">100 NM / unrestricted</td>
<td style="text-align: right;">87.44%</td>
<td style="text-align: right;">79.82%</td>
<td style="text-align: right;">69.79%</td>
</tr>
<tr class="even">
<td style="text-align: left;">—</td>
<td style="text-align: left;">trend (production)</td>
<td style="text-align: right;">68.06%</td>
<td style="text-align: right;">97.87%</td>
<td style="text-align: right;">66.61%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">—</td>
<td style="text-align: left;">nearest (no abstention)</td>
<td style="text-align: right;">88.56%</td>
<td style="text-align: right;">79.41%</td>
<td style="text-align: right;">70.33%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each of these is degenerate in its own way.</p>
<p><strong>Maximising accuracy produces a rule quieter than the one it replaces.</strong> The best-accuracy departure cell answers 66.84% of flights against production’s 68.72%. It is more accurate and <em>less useful</em>: fewer flights labelled, for a fraction of a point. For arrivals it is starker still, at 52.03% coverage.</p>
<p><strong>Maximising coverage switches abstention off.</strong> The best-coverage cell reaches 91.41% against <code>nearest</code>’s 91.68% — the residual is only the aerodromes with no elevation in OurAirports. At that setting <code>endpoint</code> <em>is</em> <code>nearest</code>, and the reason for choosing it has been configured away.</p>
<p><strong>Maximising overall correctness is maximising coverage in disguise.</strong> Across the grid, overall correctness correlates <strong>+0.988 with coverage</strong> and <strong>-0.439 with accuracy</strong> for departures (+0.951 and -0.584 for arrivals). Coverage spans 60.27% across the grid and accuracy only 11.33%, so the product tracks the wider factor. And for arrivals the verdict of overall correctness is explicitly <em>do not abstain</em>: <code>nearest</code> scores 70.33%, above every <code>endpoint</code> cell.</p>
<p><strong>It is also too flat to discriminate.</strong> 30 of the 126 departure cells sit within half a point of the best overall correctness, spanning 40–110 NM and 20,000–40,000 ft. Those statistically indistinguishable cells differ by <strong>thousands of wrong labels</strong>. Overall correctness cannot see the thing that separates them.</p>
</section>
<section id="sec-op-choice" class="level3" data-number="9.4">
<h3 data-number="9.4" class="anchored" data-anchor-id="sec-op-choice"><span class="header-section-number">9.4</span> The exchange rate, and the choice</h3>
<p>What remains is a policy question that the data can inform but not settle: how many extra wrong labels is one extra correct label worth?</p>
<p>There is a structural asymmetry that argues for pricing errors above correct answers. <strong>A wrong aerodrome corrupts two movement counts</strong> — the aerodrome that loses the flight and the aerodrome that wrongly gains it — and it is invisible to a consumer, indistinguishable from a correct label. <strong>A silent flight depresses one count and is explicit</strong>: it arrives as a null the consumer can filter, and <a href="#sec-crosscheck" class="quarto-xref">Section&nbsp;8</a>’s undercount is correctable in a way an inflated count is not. Tenerife North makes the point concretely: a count ratio of 0.99 that looks healthy, on a recall of 23.75%.</p>
<p>On that reasoning an error is worth at least two correct labels, and the departure ladder stops at the last step above 2:1.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The operating point this study recommends
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Departures: <code>endpoint</code> at 30 NM, 15,000 ft, 10 NM scheduled-service penalty.</strong> 10,993 correct departure labels against production for 645 wrong ones.</p>
<p><strong>Arrivals: keep <code>trend</code>.</strong> Nothing measured here improves on it, and the cells that add correct labels add errors seven to seventeen times faster.</p>
<p>At a stricter exchange rate the departure answer moves inward — 5:1 gives 20 NM / 10,000 ft, 10:1 gives 20 NM / 8,000 ft — and at 1:1 it moves out to 40 NM / 20,000 ft. The rate is the decision; the parameters follow from it.</p>
</div>
</div>
<p>The penalty of 10 NM is carried over from <a href="#sec-penalty" class="quarto-xref">Section&nbsp;6</a>, where it was swept at 40 NM and 15,000 ft. It has not been re-verified at 30 NM, and should be before this is published.</p>
</section>
</section>
<section id="sec-hybrid" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="sec-hybrid"><span class="header-section-number">10</span> What <code>endpoint</code> could borrow from <code>trend</code></h2>
<p><a href="#sec-op-arr" class="quarto-xref">Section&nbsp;9.2</a> leaves an uncomfortable result: for arrivals, the algorithm this study has been arguing for loses to the one it proposed to replace, at every setting measured. That is worth understanding rather than working around, because the reason points at what a better rule would look like.</p>
<section id="sec-why-trend" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="sec-why-trend"><span class="header-section-number">10.1</span> Why <code>trend</code> wins arrivals</h3>
<p>The two rules differ in how much of the trajectory they read.</p>
<p><strong><code>endpoint</code> reads one sample.</strong> The first or last fix of the track, its distance to each candidate, its height above field elevation, its ground flag. Nothing else.</p>
<p><strong><code>trend</code> reads every sample below FL40 inside the zone.</strong> For each (track, aerodrome) pair it smooths altitude over five samples and counts rises against falls. It sees a descent, not a point.</p>
<p>For departures that difference barely matters. A departure’s first sample is near the field whatever else is true, so one sample locates it almost as well as fifty — which is why <code>endpoint</code> beats <code>trend</code> on departures by 10,993 correct labels.</p>
<p>For arrivals it matters a great deal, for the reason <a href="#sec-radius" class="quarto-xref">Section&nbsp;5</a> identified: <strong>an arrival’s last sample is where reception died, which is a property of the receiver network rather than of the flight.</strong> The samples <em>before</em> it still describe an approach. <code>endpoint</code> throws them away; <code>trend</code> uses them.</p>
<p>There is a second difference, and it is the more important one. <code>trend</code>’s altitude vote is evaluated <strong>per candidate aerodrome</strong> — it asks “is this aircraft descending toward <em>this</em> aerodrome”, which discriminates between candidates. <code>endpoint</code>’s thresholds are a <strong>gate</strong>: as <a href="#sec-modes" class="quarto-xref">Section&nbsp;3</a> puts it, the abstention decides <em>whether</em> to answer, never <em>what</em> to answer. Naming is left entirely to effective distance.</p>
<p>That matters because the dominant arrival failure is misnaming, not silence. <a href="#sec-outliers" class="quarto-xref">Section&nbsp;8.2</a> found Bilbao answering 90.64% of its arrivals and placing only 38 of 235 correctly. <strong>No gate can fix a naming error.</strong> Tightening the thresholds makes the rule answer less; it does not make it answer better.</p>
</section>
<section id="sec-cone" class="level3" data-number="10.2">
<h3 data-number="10.2" class="anchored" data-anchor-id="sec-cone"><span class="header-section-number">10.2</span> Tested: an approach cone instead of a rectangle</h3>
<p>The first idea to try is the cheapest, because it needs no new data — only a different shape for the same two numbers.</p>
<p>The current rule accepts an endpoint inside <code>radius_nm</code> <strong>and</strong> below <code>height_ft</code>, treating distance and height as independent. On an approach they are not: an aircraft descending toward an aerodrome trades height for distance at roughly a constant rate. The 3° glideslope is 318 ft/NM and the “three times the flight level” descent rule of thumb is about 333 ft/NM. So the endpoints that genuinely belong to an aerodrome should lie in a <strong>cone</strong>, <code>agl_ft ≤ k · dist_nm</code>, not a box.</p>
<p>The two shapes disagree in both corners:</p>
<ul>
<li><strong>close and high</strong> is inside the box, outside the cone. An aircraft at 15,000 ft overhead an aerodrome is overflying it. The box accepts this, and it is a pure source of wrong labels.</li>
<li><strong>far and low</strong> is outside the box, inside the cone. An arrival whose reception dies at 8,000 ft and 30 NM is on profile and is a good candidate.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The approach cone at a 40 NM outer cap, against the rectangle <strong>at matched coverage</strong> – the only fair comparison between two acceptance shapes. <em>box acc</em> is the rectangle’s accuracy interpolated to the cone’s coverage; <em>cone gain</em> is positive where the cone is better.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Slope</th>
<th style="text-align: right;">ADEP cov</th>
<th style="text-align: right;">ADEP acc</th>
<th style="text-align: right;">box acc</th>
<th style="text-align: right;">cone gain</th>
<th style="text-align: right;">ADES cov</th>
<th style="text-align: right;">ADES acc</th>
<th style="text-align: right;">box acc</th>
<th style="text-align: right;">cone gain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">150 ft/NM</td>
<td style="text-align: right;">56.76%</td>
<td style="text-align: right;">98.81%</td>
<td style="text-align: right;">98.94%</td>
<td style="text-align: right;">-0.13 pp</td>
<td style="text-align: right;">57.34%</td>
<td style="text-align: right;">98.22%</td>
<td style="text-align: right;">98.48%</td>
<td style="text-align: right;">-0.26 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">200 ft/NM</td>
<td style="text-align: right;">56.80%</td>
<td style="text-align: right;">98.75%</td>
<td style="text-align: right;">98.94%</td>
<td style="text-align: right;">-0.19 pp</td>
<td style="text-align: right;">57.60%</td>
<td style="text-align: right;">98.12%</td>
<td style="text-align: right;">98.46%</td>
<td style="text-align: right;">-0.34 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">250 ft/NM</td>
<td style="text-align: right;">56.87%</td>
<td style="text-align: right;">98.65%</td>
<td style="text-align: right;">98.94%</td>
<td style="text-align: right;">-0.29 pp</td>
<td style="text-align: right;">58.89%</td>
<td style="text-align: right;">98.01%</td>
<td style="text-align: right;">98.39%</td>
<td style="text-align: right;">-0.38 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">300 ft/NM</td>
<td style="text-align: right;">57.01%</td>
<td style="text-align: right;">98.49%</td>
<td style="text-align: right;">98.94%</td>
<td style="text-align: right;">-0.45 pp</td>
<td style="text-align: right;">62.09%</td>
<td style="text-align: right;">97.90%</td>
<td style="text-align: right;">98.05%</td>
<td style="text-align: right;">-0.15 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">333 ft/NM</td>
<td style="text-align: right;">57.16%</td>
<td style="text-align: right;">98.36%</td>
<td style="text-align: right;">98.94%</td>
<td style="text-align: right;">-0.58 pp</td>
<td style="text-align: right;">63.37%</td>
<td style="text-align: right;">97.80%</td>
<td style="text-align: right;">97.89%</td>
<td style="text-align: right;">-0.09 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">400 ft/NM</td>
<td style="text-align: right;">57.67%</td>
<td style="text-align: right;">98.29%</td>
<td style="text-align: right;">98.94%</td>
<td style="text-align: right;">-0.65 pp</td>
<td style="text-align: right;">65.22%</td>
<td style="text-align: right;">97.56%</td>
<td style="text-align: right;">97.42%</td>
<td style="text-align: right;">+0.14 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">500 ft/NM</td>
<td style="text-align: right;">60.06%</td>
<td style="text-align: right;">98.12%</td>
<td style="text-align: right;">98.95%</td>
<td style="text-align: right;">-0.83 pp</td>
<td style="text-align: right;">66.71%</td>
<td style="text-align: right;">96.93%</td>
<td style="text-align: right;">96.92%</td>
<td style="text-align: right;">+0.02 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">650 ft/NM</td>
<td style="text-align: right;">66.92%</td>
<td style="text-align: right;">97.59%</td>
<td style="text-align: right;">98.98%</td>
<td style="text-align: right;">-1.39 pp</td>
<td style="text-align: right;">68.14%</td>
<td style="text-align: right;">95.79%</td>
<td style="text-align: right;">96.24%</td>
<td style="text-align: right;">-0.45 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">800 ft/NM</td>
<td style="text-align: right;">73.44%</td>
<td style="text-align: right;">97.06%</td>
<td style="text-align: right;">98.77%</td>
<td style="text-align: right;">-1.72 pp</td>
<td style="text-align: right;">69.34%</td>
<td style="text-align: right;">94.62%</td>
<td style="text-align: right;">95.49%</td>
<td style="text-align: right;">-0.87 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">1000 ft/NM</td>
<td style="text-align: right;">78.92%</td>
<td style="text-align: right;">95.86%</td>
<td style="text-align: right;">98.41%</td>
<td style="text-align: right;">-2.55 pp</td>
<td style="text-align: right;">70.97%</td>
<td style="text-align: right;">92.72%</td>
<td style="text-align: right;">94.01%</td>
<td style="text-align: right;">-1.29 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1500 ft/NM</td>
<td style="text-align: right;">84.45%</td>
<td style="text-align: right;">93.65%</td>
<td style="text-align: right;">95.20%</td>
<td style="text-align: right;">-1.55 pp</td>
<td style="text-align: right;">74.06%</td>
<td style="text-align: right;">89.32%</td>
<td style="text-align: right;">90.94%</td>
<td style="text-align: right;">-1.62 pp</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>It does not work.</strong> For departures the cone is worse at every slope — by up to 2.55 pp of accuracy at matched coverage. For arrivals it is a wash: negative at most slopes, and the largest positive figure is a tenth of a point, which is noise on this sample.</p>
<p>The departure failure is physical and worth stating, because it explains why the box is the right shape there. <strong>Climb gradients are far steeper than descent gradients.</strong> A departure 10 NM out is routinely at 6,000–8,000 ft — 600 to 800 ft/NM, against the glideslope’s 318 — so a cone tuned to descent excludes precisely the departures it should keep. The box’s permissiveness close to the field is not an oversight; it is what departures need. To reach the coverage the box gives at 15,000 ft, the cone needs a slope above 1,000 ft/NM, at which point it is no longer a cone in any meaningful sense.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The negative result that matters most
</div>
</div>
<div class="callout-body-container callout-body">
<p>Neither shape closes the arrival gap. At the coverage where production sits, the cone reaches 95.79% accuracy against <code>trend</code>’s 97.87%.</p>
<p>Box and cone are both <strong>acceptance regions defined on the distance and height of a single endpoint</strong>, and this experiment suggests that family is exhausted. No rearrangement of those two numbers recovers what <code>trend</code> has. The remaining gains have to come from somewhere else: <strong>more evidence</strong>, or <strong>a naming rule</strong>.</p>
</div>
</div>
</section>
<section id="sec-untested" class="level3" data-number="10.3">
<h3 data-number="10.3" class="anchored" data-anchor-id="sec-untested"><span class="header-section-number">10.3</span> Untested, in order of expected value</h3>
<p><strong>1. A descent-direction tie-break — a naming rule, not a gate.</strong> Rank candidates by effective distance as now, but when the top two are within a small margin, break the tie on which aerodrome the aircraft is descending <em>toward</em>, using the vertical rate at the endpoint and the bearing to each candidate. This is the smallest piece of <code>trend</code> that can be borrowed, and it is the only proposal here that attacks misnaming. It fires only on the ambiguous pairs, so it cannot damage the flights that are already unambiguous — which is exactly the property <a href="#sec-penalty" class="quarto-xref">Section&nbsp;6</a> found made the scheduled-service penalty safe. The candidate cache would need <code>vert_rate</code> and a bearing, both available in the state vectors at no join cost.</p>
<p><strong>2. Closest approach below FL40, instead of the last sample.</strong> Replace “the last fix” with “the fix of closest approach among those below FL40”. For an arrival whose reception fails on the approach, the closest approach is a far better locator than the last recorded point. The cost is real: the candidate builder currently emits two rows per track, which is what makes the sweeps in this paper affordable (<a href="#sec-preprocessing" class="quarto-xref">Section&nbsp;1</a>), and this would emit more. A middle course is to keep the two endpoints and add the closest-approach fix as a third.</p>
<p><strong>3. Re-testing the cascade — but read version 1 first.</strong> The obvious move is to take <code>trend</code>’s answer when it has one and fall through to <code>endpoint</code>. <strong>Version 1 tested exactly this and it failed</strong>, and the way it failed is the caution: every rung had <em>negative lift</em>, meaning the trend rungs fired on easy flights where nearest was already right, and overwrote better answers. The cascade collapsed onto its fallback rung.</p>
<p>Whether that still holds is an open question rather than a settled one, because version 1 measured it in the pre-H3 architecture and on departures, and this version’s arrival result is new. The diagnostic is cheap and decisive: attribute each cascade answer to the rung that supplied it, and score that rung against <code>endpoint</code> <strong>on the same flights</strong>. If <code>trend</code>’s arrival advantage comes from answering <em>different</em> flights, a cascade will help; if it comes from being better on <em>shared</em> flights, <code>trend</code> should simply replace <code>endpoint</code> for arrivals, which is what <a href="#sec-op-arr" class="quarto-xref">Section&nbsp;9.2</a> already recommends. Version 1’s harness has the attribution code (<code>--diagnose-cascade</code>).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Not this: extrapolating the trajectory
</div>
</div>
<div class="callout-body-container callout-body">
<p>The intuitive fix for an arrival whose reception dies at 8,000 ft is to project the descent forward to the ground. <strong>Do not.</strong> Version 2 of this study implemented trajectory extrapolation and it failed, and the 2025 PRC Data Challenge reached the same conclusion independently and more strongly: <em>“attempts to complete the trajectory always lead to worse result”</em>. Two independent negative results on the same idea is enough.</p>
</div>
</div>
</section>
<section id="sec-hybrid-dep" class="level3" data-number="10.4">
<h3 data-number="10.4" class="anchored" data-anchor-id="sec-hybrid-dep"><span class="header-section-number">10.4</span> Should any of this apply to departures too?</h3>
<p>The tie-break of proposal 1 should, and for the same reason it helps arrivals: <a href="#sec-penalty" class="quarto-xref">Section&nbsp;6</a> showed the largest identified departure error class was a neighbouring-aerodrome confusion, and the scheduled-service penalty only fixed the subset where the neighbour was military. A descent-direction test — inverted, a <em>climb</em>-direction test — discriminates on physics rather than on aerodrome metadata, and would catch confusions the penalty cannot.</p>
<p>Proposals 2 and 3 should not. Departures do not have the evidence problem: one sample already locates them, <code>endpoint</code> already beats <code>trend</code> there by 10,993 correct labels, and adding trajectory evidence to a rule that is not short of evidence is how the version 1 cascade lost accuracy.</p>
</section>
</section>
<section id="recommendation" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="recommendation"><span class="header-section-number">11</span> Recommendation</h2>
<p><strong>Adopt <code>endpoint</code> for departures if coverage matters more than the last point of accuracy.</strong> It adds +12.47 pp of coverage for -0.84 pp, and it is a smaller algorithm than the one it replaces — no smoothing window, no margin parameter, no per-aerodrome vote. If accuracy is paramount, keep <code>trend</code>; it is genuinely the more accurate rule now.</p>
<p><strong>Use 20–40 NM and a scheduled-service penalty of 10 NM.</strong> Both are on plateaus, so neither is delicate.</p>
<p><strong>Do not change the arrivals algorithm on this evidence.</strong> Arrivals are weaker on every measure and every version of this study has found the same.</p>
<p><strong>Publish the provenance column.</strong> <code>adep_source</code> / <code>ades_source</code> distinguish “named an aerodrome”, “outside the observed area” and “could not determine”. Today all three are a single null in the published flight list, and they mean entirely different things to a consumer. This is the highest-value change per line of code in the whole study.</p>
<p><strong>Make abstention aware of what the reference contains.</strong> Flights to and from small aerodromes and heliports are answered about half the time and are wrong every time (<a href="#sec-per-type" class="quarto-xref">Section&nbsp;8.1</a>). They are a small share of movements but they are false statements rather than gaps, and they are indistinguishable in the output from correct answers. Either extend the reference to small aerodromes or abstain when the nearest candidate is far enough away to suggest the real aerodrome is one the reference does not hold.</p>
</section>
<section id="sec-limitations" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="sec-limitations"><span class="header-section-number">12</span> Limitations</h2>
<ul>
<li><strong>Three days</strong>, one sample. Versions 2 and 3 used two samples a year apart; this version re-runs the whole pipeline, which is expensive, so it uses one. The mode ranking is robust across earlier versions, but the exact figures here have not been validated on a second period.</li>
<li><strong>Out-of-area recall is low.</strong> The geometric border test is the wrong instrument; the phase-based test in <a href="#sec-ooa" class="quarto-xref">Section&nbsp;7</a> is the successor.</li>
<li><strong>The detection reference holds large and medium aerodromes only</strong>, so accuracy on any other class is zero by construction rather than by measurement. The per-class table quantifies this; it does not fix it.</li>
<li><strong>The scheduled-service preference has a cost</strong> that these accuracy figures include but do not itemise: movements at non-scheduled aerodromes are pulled to nearby hubs.</li>
<li><strong>The sweep re-implements the endpoint rule</strong> as a DataFrame operation instead of calling the pipeline’s <code>classify_endpoints</code>, because a sweep cell needs only <code>(track_id, adep, ades)</code> while the pipeline method builds a whole flight list. The headline <code>endpoint</code> row <em>does</em> come from the pipeline path, so a divergence between the two would surface as the sweep disagreeing with its own mode — but this is a duplication and worth removing.</li>
<li><strong><code>track_id</code> is taken as given</strong>, with the fragmentation and merging rates version 2 measured.</li>
</ul>
</section>
<section id="reproducing" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="reproducing"><span class="header-section-number">13</span> Reproducing</h2>
<p>Reference zones, state vectors and tracks, in the <code>opdi</code> repository:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">RANGE</span><span class="op">=</span><span class="st">"--env opensky --start 2025-06-05 --end 2025-06-08"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">opdi</span> run <span class="va">$RANGE</span> <span class="at">--step</span> 00a   <span class="co"># zones: 5 NM bands to 110 NM</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">opdi</span> run <span class="va">$RANGE</span> <span class="at">--step</span> 01    <span class="co"># state vectors, bbox and 5 s applied at ingest</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="ex">opdi</span> run <span class="va">$RANGE</span> <span class="at">--step</span> 02    <span class="co"># tracks, with H3 res 7 and 12</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Candidates once, then a flight list per mode:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> date</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> opdi.pipeline.flights <span class="im">import</span> FlightListProcessor</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>fp <span class="op">=</span> FlightListProcessor(spark, config)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>fp.build_endpoint_candidates(date(<span class="dv">2025</span>, <span class="dv">6</span>, <span class="dv">1</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mode <span class="kw">in</span> (<span class="st">"trend"</span>, <span class="st">"nearest"</span>, <span class="st">"endpoint"</span>):</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    fp.process_dai(date(<span class="dv">2025</span>, <span class="dv">6</span>, <span class="dv">1</span>), mode<span class="op">=</span>mode, skip_if_processed<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                   abstention_radius_nm<span class="op">=</span><span class="dv">40</span>, abstention_height_ft<span class="op">=</span><span class="dv">15000</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                   sched_penalty_nm<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                   table_name<span class="op">=</span><span class="ss">f"research/flight_list_</span><span class="sc">{</span>mode<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>                   write_mode<span class="op">=</span><span class="st">"overwrite"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Scoring and both sweeps. This runs locally: the inputs are small once the candidates are cached, and the cluster namespace is shared.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> benchmarks/benchmark_modes.py <span class="at">--months</span> 202506 <span class="dt">\</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">--days</span> 2025-06-05 2025-06-06 2025-06-07 <span class="at">--local</span> <span class="at">--results-dir</span> <span class="op">&lt;</span>dir<span class="op">&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Rendering this page needs no credentials, no database and no cluster.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>